"""Android UI strings. Separate copy from desktop and web."""
UI = {
    "en": {
        "title": "Ultra Calculator",
        "calc": "Calculator",
        "formulas": "Formulas",
        "poly": "Polynomial",
        "numeric": "Numerical",
        "algo": "Algorithms",
        "pick_algo": "Pick an algorithm.",
        "algo_hint": "Fill the fields and press Enter. Matrices: 1, 2; 3, 4. Lists: 1, 2, 3.",
        "search": "Search",
        "categories": "Categories",
        "all": "All",
        "solve": "Solve",
        "unknown": "Unknown",
        "single": "One unknown",
        "system": "Several equations",
        "add": "Add equation",
        "remove": "Remove equation",
        "result": "Result",
        "deg": "DEG",
        "rad": "RAD",
        "eng": "ENG",
        "evaluate": "Evaluate",
        "roots": "Roots",
        "run": "Run",
        "root": "Root",
        "integral": "Integral",
        "deriv": "Derivative",
        "ode": "ODE",
        "history": "History",
        "ready": "Ready",
        "pick": "Pick a formula.",
        "lang": "Language",
        "chem": "Chemistry",
        "elements": "Elements",
        "balance": "Balance",
        "molar": "Molar mass",
        "atomic_n": "Z",
        "atomic_m": "Mass",
        "isotopes": "Isotopes",
        "sources": "Sources",
        "lookup": "Lookup",
        "lookup_hint": "H2O, Fe, Fe-56, R, g",
        "insert": "Insert",
        "lookup_need_field": "Click the field you want, then insert.",
        "kbd_hint": "Type on the screen. The phone keyboard works. You can type summation(k,k,1,100), diff(x**3,x), integrate(x**2,x,0,1).",
        "back": "Back",
        "clear": "AC",
        "equals": "=",
        "steps": "Steps",
        "problems": "Problems",
        "inverse": "Inverse",
        "at_value": "at",
        "problem_hint": "Type an equation such as 2*x+3=11 or x**2-5*x+6=0. Solve finds the unknown. Inverse finds the inverse function. Fill at to evaluate the inverse at that value. Matrices: 1, 2; 3, 4.",
        "circuits": "Circuits",
        "circuit_freq": "f (Hz)",
        "circuit_hint": "Type a netlist (node 0 is ground): V1 1 0 12 / R1 1 2 1k / R2 2 0 2k. Or series 1k 2k, parallel 1k 1k, divider 12 1k 2k, V=12 R=1k.",
    },
    "fa": {
        "title": "ماشین حساب اولترا",
        "calc": "ماشین حساب",
        "formulas": "فرمول ها",
        "poly": "چندجمله ای",
        "numeric": "عددی",
        "algo": "الگوریتم ها",
        "pick_algo": "یک الگوریتم انتخاب کن.",
        "algo_hint": "خانه‌ها را پر کن و Enter بزن. ماتریس: 1, 2; 3, 4.",
        "search": "جستجو",
        "categories": "دسته ها",
        "all": "همه",
        "solve": "حل",
        "unknown": "مجهول",
        "single": "یک مجهول",
        "system": "چند معادله",
        "add": "افزودن معادله",
        "remove": "حذف معادله",
        "result": "نتیجه",
        "deg": "درجه",
        "rad": "رادیان",
        "eng": "مهندسی",
        "evaluate": "مقدار",
        "roots": "ریشه ها",
        "run": "اجرا",
        "root": "ریشه",
        "integral": "انتگرال",
        "deriv": "مشتق",
        "ode": "دیفرانسیل",
        "history": "تاریخچه",
        "ready": "آماده",
        "pick": "یک فرمول انتخاب کن.",
        "lang": "زبان",
        "chem": "شیمی",
        "elements": "عنصرها",
        "balance": "موازنه",
        "molar": "جرم مولی",
        "atomic_n": "Z",
        "atomic_m": "جرم",
        "isotopes": "ایزوتوپ",
        "sources": "منبع ها",
        "lookup": "جستجوی سریع",
        "lookup_hint": "H2O, Fe, Fe-56, R, g",
        "insert": "بگذار",
        "lookup_need_field": "اول خانه را انتخاب کن، بعد بگذار.",
        "kbd_hint": "توی صفحه تایپ کن. کیبورد گوشی کار می‌کند. می‌توانی بنویسی summation(k,k,1,100) یا diff(x**3,x).",
        "back": "بازگشت",
        "clear": "پاک",
        "equals": "=",
        "steps": "مراحل",
        "problems": "مسائل",
        "inverse": "حل عکس",
        "at_value": "در",
        "problem_hint": "معادله را بنویس، مثلاً 2*x+3=11 یا x**2-5*x+6=0. حل، مجهول را پیدا می‌کند. حل عکس، تابع وارون را می‌دهد. اگر «در» را پر کنی، وارون را در همان نقطه حساب می‌کند. ماتریس: 1, 2; 3, 4.",
        "circuits": "مدارها",
        "circuit_freq": "f (هرتز)",
        "circuit_hint": "نت‌لیست بنویس (گره ۰ زمین است): V1 1 0 12 سپس R1 1 2 1k سپس R2 2 0 2k. یا series 1k 2k یا V=12 R=1k.",
    },
    "fi": {
        "title": "Ultra-laskin",
        "calc": "Laskin",
        "formulas": "Kaavat",
        "poly": "Polynomi",
        "numeric": "Numeerinen",
        "search": "Haku",
        "categories": "Luokat",
        "all": "Kaikki",
        "solve": "Ratkaise",
        "unknown": "Tuntematon",
        "single": "Yksi tuntematon",
        "system": "Useita yhtaloita",
        "add": "Lisaa yhtalo",
        "remove": "Poista yhtalo",
        "result": "Tulos",
        "deg": "ASTE",
        "rad": "RAD",
        "eng": "ENG",
        "evaluate": "Laske",
        "roots": "Juuret",
        "run": "Suorita",
        "root": "Juuri",
        "integral": "Integraali",
        "deriv": "Derivaatta",
        "ode": "DY",
        "history": "Historia",
        "ready": "Valmis",
        "pick": "Valitse kaava.",
        "lang": "Kieli",
        "chem": "Kemia",
        "elements": "Alkuaineet",
        "balance": "Tasapainota",
        "molar": "Moolimassa",
        "atomic_n": "Z",
        "atomic_m": "Massa",
        "isotopes": "Isotoopit",
        "sources": "Lahteet",
        "lookup": "Haku",
        "lookup_hint": "H2O, Fe, Fe-56, R, g",
        "insert": "Lisaa",
        "lookup_need_field": "Napsauta kenttaa, sitten Lisaa.",
        "kbd_hint": "Kirjoita nayttoon. Puhelimen nappaimisto toimii. Voit kirjoittaa summation(k,k,1,100) tai diff(x**3,x).",
        "back": "Takaisin",
        "clear": "AC",
        "equals": "=",
        "steps": "Askeleet",
        "algo": "Algoritmit",
        "problems": "Tehtavat",
        "inverse": "Kaanteinen",
        "at_value": "kohdassa",
        "problem_hint": "Kirjoita yhtalo, esim. 2*x+3=11. Ratkaise etsii tuntemattoman. Kaanteinen etsii kaanteisfunktion. Jos taytat kohdan, se lasketaan siina pisteessa. Matriisit: 1, 2; 3, 4.",
    },
}


def ui_text(lang, key):
    pack = UI.get(lang) or UI["en"]
    return pack.get(key) or UI["en"].get(key, key)
