plugins {
    id "com.android.application"
}
android {
    compileSdk 33
    namespace "org.capzx545.ultracalculator"
    defaultConfig {
        applicationId "org.capzx545.ultracalculator"
        minSdk 24
        targetSdk 33
        versionCode 13
        versionName "1.8.4"
    }
    buildTypes {
        release { minifyEnabled false }
        debug { minifyEnabled false }
    }
    aaptOptions {
        noCompress "wasm", "whl", "zip"
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}
