"""Unique extra identities: networks, power laws, multiple-angle, more named textbook."""

from __future__ import annotations

import sympy as sp

from add_textbook_formulas import V, row


def networks_and_powers():
    R = []
    a = R.append
    for n in range(3, 81):
        a(row(f"tx_rser_{n}", "eng.elec",
              f"{n} equal resistors in series", f"{n} مقاومت مساوی سری", f"{n} vastusta sarjassa",
              f"R = {n}*R0",
              V(("R", "ohm", "equivalent", "معادل", "ekv"), ("R0", "ohm", "each R", "هر مقاومت", "kukin"))))
        a(row(f"tx_rpar_{n}", "eng.elec",
              f"{n} equal resistors in parallel", f"{n} مقاومت مساوی موازی", f"{n} vastusta rinnan",
              f"R = R0/{n}",
              V(("R", "ohm", "equivalent", "معادل", "ekv"), ("R0", "ohm", "each R", "هر مقاومت", "kukin"))))
    for n in range(3, 41):
        a(row(f"tx_cpar_{n}", "physics.circuits",
              f"{n} equal capacitors in parallel", f"{n} خازن مساوی موازی", f"{n} kondensaattoria rinnan",
              f"C = {n}*C0",
              V(("C", "F", "equivalent", "معادل", "ekv"), ("C0", "F", "each C", "هر خازن", "kukin"))))
        a(row(f"tx_cser_{n}", "physics.circuits",
              f"{n} equal capacitors in series", f"{n} خازن مساوی سری", f"{n} kondensaattoria sarjassa",
              f"C = C0/{n}",
              V(("C", "F", "equivalent", "معادل", "ekv"), ("C0", "F", "each C", "هر خازن", "kukin"))))
    for n in range(3, 25):
        a(row(f"tx_lser_{n}", "physics.circuits",
              f"{n} equal inductors in series", f"{n} سلف مساوی سری", f"{n} kelaa sarjassa",
              f"L = {n}*L0",
              V(("L", "H", "equivalent", "معادل", "ekv"), ("L0", "H", "each L", "هر سلف", "kukin"))))
        a(row(f"tx_lpar_{n}", "physics.circuits",
              f"{n} equal inductors in parallel", f"{n} سلف مساوی موازی", f"{n} kelaa rinnan",
              f"L = L0/{n}",
              V(("L", "H", "equivalent", "معادل", "ekv"), ("L0", "H", "each L", "هر سلف", "kukin"))))
        a(row(f"tx_cells_ser_{n}", "eng.power",
              f"{n} equal cells in series", f"{n} سلول سری", f"{n} kennoa sarjassa",
              f"V = {n}*V0",
              V(("V", "V", "pack voltage", "ولتاژ بسته", "jannite"), ("V0", "V", "cell", "سلول", "kenno"))))
        a(row(f"tx_cells_par_{n}", "eng.power",
              f"{n} equal cells in parallel current", f"{n} سلول موازی جریان", f"{n} kennoa rinnan",
              f"i = {n}*i0",
              V(("i", "A", "pack current", "جریان بسته", "virta"), ("i0", "A", "cell current", "جریان سلول", "kennovirta"))))
    for n in range(2, 41):
        a(row(f"tx_powerlaw_{n}", "math.algebra",
              f"Power law degree {n}", f"قانون توانی درجه {n}", f"Potenssilaki {n}",
              f"y = a*x**{n}",
              V(("y", "1", "y", "y", "y"), ("a", "1", "coefficient", "ضریب", "kerroin"), ("x", "1", "x", "x", "x"))))
    for n in range(2, 21):
        a(row(f"tx_rootlaw_{n}", "math.algebra",
              f"Root law n={n}", f"قانون ریشه n={n}", f"Juuri n={n}",
              f"y = a*x**(1/{n})",
              V(("y", "1", "y", "y", "y"), ("a", "1", "coefficient", "ضریب", "kerroin"), ("x", "1", "x", "x", "x"))))
        a(row(f"tx_exp_base_{n}", "math.algebra",
              f"Exponential base {n}", f"نمایی پایه {n}", f"Eksponentti kanta {n}",
              f"y = {n}**x",
              V(("y", "1", "y", "y", "y"), ("x", "1", "x", "x", "x"))))
    for n in range(2, 16):
        a(row(f"tx_log_base_{n}", "math.algebra",
              f"Log base {n}", f"لگاریتم پایه {n}", f"Log kanta {n}",
              f"y = log(x)/log({n})",
              V(("y", "1", "log", "لگاریتم", "log"), ("x", "1", "x", "x", "x"))))
    return R


def multi_angle():
    R = []
    a = R.append
    x = sp.symbols("x")
    for n in range(3, 13):
        s = sp.expand(sp.sin(n * x))
        c = sp.expand(sp.cos(n * x))
        # write in sin/cos of x
        s = sp.trigsimp(s)
        c = sp.trigsimp(c)
        # better expand in powers
        s = sp.expand_trig(sp.sin(n * x))
        c = sp.expand_trig(sp.cos(n * x))
        sex = str(s).replace("**", "**")
        cex = str(c).replace("**", "**")
        a(row(f"tx_sin{n}x", "math.trig",
              f"sin({n}x) multiple-angle", f"سینوس {n}برابر زاویه", f"sin({n}x)",
              f"y = {sex}",
              V(("y", "1", f"sin({n}x)", f"sin({n}x)", f"sin({n}x)"), ("x", "rad", "x", "x", "x"))))
        a(row(f"tx_cos{n}x", "math.trig",
              f"cos({n}x) multiple-angle", f"کسینوس {n}برابر زاویه", f"cos({n}x)",
              f"y = {cex}",
              V(("y", "1", f"cos({n}x)", f"cos({n}x)", f"cos({n}x)"), ("x", "rad", "x", "x", "x"))))
    # Chebyshev T_n(x)
    z = sp.symbols("z")
    for n in range(2, 11):
        Tn = sp.chebyshevt(n, z)
        a(row(f"tx_chebT_{n}", "spec.poly",
              f"Chebyshev T_{n}(z)", f"چبیشف T_{n}", f"Tshebyshov T_{n}",
              f"y = {Tn}",
              V(("y", "1", f"T_{n}", f"T_{n}", f"T_{n}"), ("z", "1", "z", "z", "z"))))
        Un = sp.chebyshevu(n, z)
        a(row(f"tx_chebU_{n}", "spec.poly",
              f"Chebyshev U_{n}(z)", f"چبیشف U_{n}", f"Tshebyshov U_{n}",
              f"y = {Un}",
              V(("y", "1", f"U_{n}", f"U_{n}", f"U_{n}"), ("z", "1", "z", "z", "z"))))
    for n in range(2, 9):
        Pn = sp.legendre(n, z)
        a(row(f"tx_legendre_{n}", "spec.poly",
              f"Legendre P_{n}(z)", f"لژاندر P_{n}", f"Legendre P_{n}",
              f"y = {Pn}",
              V(("y", "1", f"P_{n}", f"P_{n}", f"P_{n}"), ("z", "1", "z", "z", "z"))))
    for n in range(2, 8):
        Hn = sp.hermite(n, z)
        a(row(f"tx_hermite_{n}", "spec.poly",
              f"Hermite H_{n}(z)", f"هرمیت H_{n}", f"Hermite H_{n}",
              f"y = {Hn}",
              V(("y", "1", f"H_{n}", f"H_{n}", f"H_{n}"), ("z", "1", "z", "z", "z"))))
        Ln = sp.laguerre(n, z)
        a(row(f"tx_laguerre_{n}", "spec.poly",
              f"Laguerre L_{n}(z)", f"لاگر L_{n}", f"Laguerre L_{n}",
              f"y = {Ln}",
              V(("y", "1", f"L_{n}", f"L_{n}", f"L_{n}"), ("z", "1", "z", "z", "z"))))
    return R


def more_named():
    R = []
    a = R.append
    extra = [
        ("tx_bragg_n", "physics.optics", "Bragg n lambda", "براگ", "Bragg",
         "n*lam = 2*d*sin(th)",
         V(("n", "1", "order", "مرتبه", "kertaluku"), ("lam", "m", "wavelength", "طول موج", "aallonpituus"),
           ("d", "m", "spacing", "فاصله صفحات", "vali"), ("th", "rad", "angle", "زاویه", "kulma"))),
        ("tx_rydberg", "physics.modern", "Rydberg general", "ریدبرگ", "Rydberg",
         "inv = Rinf*(1/n1**2 - 1/n2**2)",
         V(("inv", "1/m", "1/lambda", "۱/لامبدا", "1/lambda"), ("Rinf", "1/m", "Rydberg", "ریدبرگ", "Rydberg"),
           ("n1", "1", "n1", "n1", "n1"), ("n2", "1", "n2", "n2", "n2"))),
        ("tx_compton", "physics.modern", "Compton shift", "کامپتون", "Compton",
         "dlam = lamc*(1 - cos(th))",
         V(("dlam", "m", "delta lambda", "دلتا لامبدا", "d lambda"), ("lamc", "m", "lambda_C", "لامبدای کامپتون", "lambda_C"),
           ("th", "rad", "angle", "زاویه", "kulma"))),
        ("tx_photo_max", "physics.modern", "Photoelectric max KE", "فوتوالکتریک", "Valosahko",
         "K = h*f - W",
         V(("K", "J", "Kmax", "Kmax", "Kmax"), ("h", "J*s", "h", "h", "h"),
           ("f", "Hz", "f", "f", "f"), ("W", "J", "work function", "تابع کار", "irtoutumistyo"))),
        ("tx_debroglie", "physics.modern", "de Broglie", "دوبروی", "de Broglie",
         "lam = h/p",
         V(("lam", "m", "lambda", "لامبدا", "lambda"), ("h", "J*s", "h", "h", "h"), ("p", "kg*m/s", "p", "p", "p"))),
        ("tx_planck_e", "physics.modern", "Planck E=hf", "پلانک", "Planck",
         "En = h*f",
         V(("En", "J", "energy", "انرژی", "energia"), ("h", "J*s", "h", "h", "h"), ("f", "Hz", "f", "f", "f"))),
        ("tx_stefan", "physics.thermo", "Stefan-Boltzmann", "استفان-بولتزمن", "Stefan-Boltzmann",
         "P = e*sigma*A*T**4",
         V(("P", "W", "P", "P", "P"), ("e", "1", "emissivity", "گسیلندگی", "emissiivisyys"),
           ("sigma", "W/(m^2*K^4)", "sigma", "سیگما", "sigma"), ("A", "m^2", "A", "A", "A"), ("T", "K", "T", "T", "T"))),
        ("tx_wien", "physics.thermo", "Wien displacement", "وین", "Wien",
         "lam = b/T",
         V(("lam", "m", "lambda_max", "لامبدای بیشینه", "lambda_max"), ("b", "m*K", "Wien b", "وین", "Wien"),
           ("T", "K", "T", "T", "T"))),
        ("tx_ideal_sound", "phys.acoust", "Ideal gas sound speed", "سرعت صوت گاز آرمانی", "Aanen n. kaasussa",
         "v = sqrt(gam*Rgas*T/M)",
         V(("v", "m/s", "v", "v", "v"), ("gam", "1", "gamma", "گاما", "gamma"),
           ("Rgas", "J/(mol*K)", "R", "R", "R"), ("T", "K", "T", "T", "T"), ("M", "kg/mol", "M", "M", "M"))),
        ("tx_db_spl20", "phys.acoust", "SPL from p_rms", "تراز فشار صدا", "Aanenpainetaso",
         "L = 20*log(p/p0)/log(10)",
         V(("L", "dB", "SPL", "SPL", "SPL"), ("p", "Pa", "p_rms", "p", "p"), ("p0", "Pa", "p0", "p0", "p0"))),
        ("tx_lensmaker", "physics.optics", "Lensmaker thin lens", "سازنده عدسی", "Linssintekija",
         "Pwr = (n - 1)*(1/R1 - 1/R2)",
         V(("Pwr", "1/m", "power", "توان", "teho"), ("n", "1", "n", "n", "n"),
           ("R1", "m", "R1", "R1", "R1"), ("R2", "m", "R2", "R2", "R2"))),
        ("tx_magnification", "physics.optics", "Lateral magnification", "بزرگنمایی عرضی", "Suurennos",
         "m = -di/do",
         V(("m", "1", "m", "m", "m"), ("di", "m", "image", "تصویر", "kuva"), ("do", "m", "object", "شیء", "kohde"))),
        ("tx_critical", "physics.optics", "Critical angle", "زاویه حد", "Kokonaisheijastuskulma",
         "ic = asin(n2/n1)",
         V(("ic", "rad", "critical", "حد", "kriittinen"), ("n2", "1", "n2", "n2", "n2"), ("n1", "1", "n1", "n1", "n1"))),
        ("tx_brewster", "physics.optics", "Brewster angle", "بروستر", "Brewster",
         "th = atan(n2/n1)",
         V(("th", "rad", "Brewster", "بروستر", "Brewster"), ("n2", "1", "n2", "n2", "n2"), ("n1", "1", "n1", "n1", "n1"))),
        ("tx_na_fiber", "physics.optics", "Fiber numerical aperture", "دهانه عددی فیبر", "NA",
         "NA = sqrt(n1**2 - n2**2)",
         V(("NA", "1", "NA", "NA", "NA"), ("n1", "1", "core", "هسته", "ydin"), ("n2", "1", "cladding", "غلاف", "vaippa"))),
        ("tx_malus", "physics.optics", "Malus law", "مالوس", "Malus",
         "Iout = Iin*cos(th)**2",
         V(("Iout", "W/m^2", "out", "خروجی", "lahto"), ("Iin", "W/m^2", "in", "ورودی", "otto"),
           ("th", "rad", "angle", "زاویه", "kulma"))),
        ("tx_thin_film", "physics.optics", "Thin film 2nt", "لایه نازک", "Ohut kalvo",
         "dpath = 2*n*t",
         V(("dpath", "m", "path", "مسیر", "tie"), ("n", "1", "n", "n", "n"), ("t", "m", "thickness", "ضخامت", "paksuus"))),
        ("tx_coulomb", "physics.electro", "Coulomb", "کولن", "Coulomb",
         "F = ke*q1*q2/r**2",
         V(("F", "N", "F", "F", "F"), ("ke", "N*m^2/C^2", "k", "k", "k"),
           ("q1", "C", "q1", "q1", "q1"), ("q2", "C", "q2", "q2", "q2"), ("r", "m", "r", "r", "r"))),
        ("tx_point_E", "physics.electro", "Point charge E", "میدان بار نقطه‌ای", "Pistevarauksen E",
         "Ef = ke*q/r**2",
         V(("Ef", "V/m", "E", "E", "E"), ("ke", "N*m^2/C^2", "k", "k", "k"),
           ("q", "C", "q", "q", "q"), ("r", "m", "r", "r", "r"))),
        ("tx_cap_energy_Q", "physics.electro", "Capacitor U=Q^2/2C", "انرژی خازن Q", "Kondensaattori Q",
         "U = Q**2/(2*C)",
         V(("U", "J", "U", "U", "U"), ("Q", "C", "Q", "Q", "Q"), ("C", "F", "C", "C", "C"))),
        ("tx_biot_wire", "physics.magnet", "Biot-Savart long wire", "بیو-ساوار سیم", "Biot-Savart",
         "B = mu0*i/(2*pi*r)",
         V(("B", "T", "B", "B", "B"), ("mu0", "N/A^2", "mu0", "مو۰", "mu0"),
           ("i", "A", "current", "جریان", "virta"), ("r", "m", "r", "r", "r"))),
        ("tx_solenoid", "physics.magnet", "Long solenoid B", "سلونوئید", "Solenoidi",
         "B = mu0*n*i",
         V(("B", "T", "B", "B", "B"), ("mu0", "N/A^2", "mu0", "مو۰", "mu0"),
           ("n", "1/m", "n", "n", "n"), ("i", "A", "current", "جریان", "virta"))),
        ("tx_faraday", "physics.magnet", "Faraday emf", "فارادی", "Faraday",
         "emf = -N*dphi/dt",
         V(("emf", "V", "emf", "نیروی محرکه", "jannite"), ("N", "1", "turns", "دور", "kierrokset"),
           ("dphi", "Wb", "d(phi)", "d فی", "d phi"), ("dt", "s", "dt", "dt", "dt"))),
        ("tx_cyclotron", "physics.magnet", "Cyclotron radius", "شعاع سیکلوترون", "Syklotroni",
         "r = m*v/(q*B)",
         V(("r", "m", "r", "r", "r"), ("m", "kg", "m", "m", "m"), ("v", "m/s", "v", "v", "v"),
           ("q", "C", "q", "q", "q"), ("B", "T", "B", "B", "B"))),
        ("tx_ideal_opamp", "eng.elec", "Inverting op-amp gain", "بهره معکوس‌کننده", "Kaantava vahvistin",
         "G = -Rf/Rin",
         V(("G", "1", "gain", "بهره", "vahvistus"), ("Rf", "ohm", "Rf", "Rf", "Rf"), ("Rin", "ohm", "Rin", "Rin", "Rin"))),
        ("tx_noninv_opamp", "eng.elec", "Noninverting op-amp gain", "بهره غیرمعکوس", "Ei-kaantava",
         "G = 1 + Rf/Rg",
         V(("G", "1", "gain", "بهره", "vahvistus"), ("Rf", "ohm", "Rf", "Rf", "Rf"), ("Rg", "ohm", "Rg", "Rg", "Rg"))),
        ("tx_diffamp", "eng.elec", "Differential amp ideal", "تقویت‌کننده تفاضلی", "Erotusvahvistin",
         "Vo = (R2/R1)*(Vp - Vm)",
         V(("Vo", "V", "Vo", "Vo", "Vo"), ("R2", "ohm", "R2", "R2", "R2"), ("R1", "ohm", "R1", "R1", "R1"),
           ("Vp", "V", "V+", "V+", "V+"), ("Vm", "V", "V-", "V-", "V-"))),
        ("tx_integrator_rc", "eng.elec", "RC integrator tau", "انتگرال‌گیر RC", "RC-integraattori",
         "tau = Rf*C",
         V(("tau", "s", "tau", "تاو", "tau"), ("Rf", "ohm", "Rf", "Rf", "Rf"), ("C", "F", "C", "C", "C"))),
        ("tx_schmitt", "eng.elec", "Schmitt upper threshold", "آستانه اشمیت بالا", "Schmitt yla",
         "Vut = Vref*(R1 + R2)/R2",
         V(("Vut", "V", "upper", "بالا", "yla"), ("Vref", "V", "Vref", "مرجع", "viite"),
           ("R1", "ohm", "R1", "R1", "R1"), ("R2", "ohm", "R2", "R2", "R2"))),
        ("tx_buck_v", "eng.power", "Buck converter V", "باک", "Buck",
         "Vo = D*Vin",
         V(("Vo", "V", "Vo", "Vo", "Vo"), ("D", "1", "duty", "وظیفه", "suhde"), ("Vin", "V", "Vin", "Vin", "Vin"))),
        ("tx_boost_v", "eng.power", "Boost converter V", "بوست", "Boost",
         "Vo = Vin/(1 - D)",
         V(("Vo", "V", "Vo", "Vo", "Vo"), ("Vin", "V", "Vin", "Vin", "Vin"), ("D", "1", "duty", "وظیفه", "suhde"))),
        ("tx_sync_speed", "eng.motor", "Sync speed rpm", "سرعت سنکرون", "Tahtinopeus",
         "ns = 120*f/p",
         V(("ns", "1/min", "rpm", "دور بر دقیقه", "rpm"), ("f", "Hz", "f", "f", "f"), ("p", "1", "poles", "قطب", "navat"))),
        ("tx_slip", "eng.motor", "Induction slip", "لغزش", "Slip",
         "s = (ns - n)/ns",
         V(("s", "1", "slip", "لغزش", "slip"), ("ns", "1/min", "sync", "سنکرون", "tahti"),
           ("n", "1/min", "rotor", "روتور", "roottori"))),
        ("tx_motor_t", "eng.motor", "Motor torque from power", "گشتاور موتور", "Moottorin momentti",
         "Tq = P*60/(2*pi*n)",
         V(("Tq", "N*m", "torque", "گشتاور", "momentti"), ("P", "W", "P", "P", "P"),
           ("n", "1/min", "rpm", "دور", "rpm"))),
        ("tx_pf_angle", "eng.power", "Power factor from angle", "ضریب توان از زاویه", "Tehokerroin",
         "pf = cos(th)",
         V(("pf", "1", "pf", "ضریب توان", "tehokerroin"), ("th", "rad", "phi", "فی", "phi"))),
        ("tx_reactive", "eng.power", "Reactive power", "توان راکتیو", "Loisteho",
         "Q = V*i*sin(th)",
         V(("Q", "var", "Q", "Q", "Q"), ("V", "V", "V", "V", "V"), ("i", "A", "I", "جریان", "virta"),
           ("th", "rad", "phi", "فی", "phi"))),
        ("tx_apparent", "eng.power", "Apparent power", "توان ظاهری", "Nateho",
         "S = V*i",
         V(("S", "VA", "S", "S", "S"), ("V", "V", "V", "V", "V"), ("i", "A", "I", "جریان", "virta"))),
        ("tx_skin", "eng.elec", "Skin depth", "عمق پوستی", "Skin-syvyys",
         "delta = sqrt(2/(w*mu*sig))",
         V(("delta", "m", "delta", "دلتا", "delta"), ("w", "rad/s", "omega", "امگا", "omega"),
           ("mu", "H/m", "mu", "مو", "mu"), ("sig", "S/m", "sigma", "سیگما", "sigma"))),
        ("tx_coax_C", "eng.tl", "Coax capacitance", "خازن کواکس", "Koaksiaalin C",
         "C = 2*pi*eps/log(b/a)",
         V(("C", "F/m", "C'", "C'", "C'"), ("eps", "F/m", "eps", "اپسیلون", "eps"),
           ("b", "m", "b", "b", "b"), ("a", "m", "a", "a", "a"))),
        ("tx_coax_L", "eng.tl", "Coax inductance", "سلف کواکس", "Koaksiaalin L",
         "L = mu*log(b/a)/(2*pi)",
         V(("L", "H/m", "L'", "L'", "L'"), ("mu", "H/m", "mu", "مو", "mu"),
           ("b", "m", "b", "b", "b"), ("a", "m", "a", "a", "a"))),
        ("tx_snr_shannon_min", "cs.infotheory", "Min SNR from capacity", "حداقل SNR از ظرفیت", "Min SNR",
         "snr = 2**(C/B) - 1",
         V(("snr", "1", "S/N", "S/N", "S/N"), ("C", "bit/s", "C", "C", "C"), ("B", "Hz", "B", "B", "B"))),
        ("tx_hhi", "econ.micro", "HHI two firms", "HHI دو بنگاه", "HHI",
         "H = s1**2 + s2**2",
         V(("H", "1", "HHI", "HHI", "HHI"), ("s1", "1", "share1", "سهم ۱", "osuus1"),
           ("s2", "1", "share2", "سهم ۲", "osuus2"))),
        ("tx_lerner", "econ.micro", "Lerner index", "لرنر", "Lerner",
         "L = (p - mc)/p",
         V(("L", "1", "Lerner", "لرنر", "Lerner"), ("p", "1", "price", "قیمت", "hinta"),
           ("mc", "1", "marginal cost", "هزینه نهایی", "rajakustannus"))),
        ("tx_okun", "econ.macro", "Okun gap piece", "اوکان", "Okun",
         "gap = k*(u - ustar)",
         V(("gap", "1", "output gap", "شکاف تولید", "tuottokuilu"), ("k", "1", "Okun k", "k", "k"),
           ("u", "1", "u", "بیکاری", "tyottomyys"), ("ustar", "1", "u*", "u*", "u*"))),
        ("tx_taylor_rule", "econ.macro", "Taylor rule simple", "تیلور", "Taylor",
         "i = rstar + pi_ + 0.5*(pi_ - pit) + 0.5*gap",
         V(("i", "1", "policy rate", "نرخ سیاستی", "korko"), ("rstar", "1", "r*", "r*", "r*"),
           ("pi_", "1", "inflation", "تورم", "inflaatio"), ("pit", "1", "target", "هدف", "tavoite"),
           ("gap", "1", "gap", "شکاف", "kuilu"))),
        ("tx_ev_pe", "fin.market", "Forward P/E", "نسبت قیمت به سود پیشرو", "P/E",
         "pe = P/eps",
         V(("pe", "1", "P/E", "P/E", "P/E"), ("P", "1", "price", "قیمت", "hinta"),
           ("eps", "1", "EPS", "سود هر سهم", "EPS"))),
        ("tx_div_yield", "fin.market", "Dividend yield", "بازده سود نقدی", "Osinkotuotto",
         "y = D/P",
         V(("y", "1", "yield", "بازده", "tuotto"), ("D", "1", "dividend", "سود", "osinko"),
           ("P", "1", "price", "قیمت", "hinta"))),
        ("tx_peg", "fin.market", "PEG ratio", "PEG", "PEG",
         "peg = pe/g",
         V(("peg", "1", "PEG", "PEG", "PEG"), ("pe", "1", "P/E", "P/E", "P/E"),
           ("g", "1", "growth %", "رشد", "kasvu"))),
        ("tx_irr_one", "fin.invest", "IRR one inflow", "IRR یک ورود", "IRR",
         "r = C1/C0 - 1",
         V(("r", "1", "IRR", "IRR", "IRR"), ("C1", "1", "inflow", "ورود", "tulo"),
           ("C0", "1", "outlay", "خروج", "sijoitus"))),
        ("tx_payback", "fin.invest", "Simple payback", "دوره بازگشت", "Takaisinmaksu",
         "t = C0/Cbar",
         V(("t", "yr", "years", "سال", "vuodet"), ("C0", "1", "investment", "سرمایه", "sijoitus"),
           ("Cbar", "1", "annual CF", "جریان سالانه", "vuosikate"))),
        ("tx_eoq", "ind.ops", "EOQ", "مقدار اقتصادی سفارش", "EOQ",
         "q = sqrt(2*D*S/H)",
         V(("q", "1", "EOQ", "EOQ", "EOQ"), ("D", "1/yr", "demand", "تقاضا", "kysynta"),
           ("S", "1", "order cost", "هزینه سفارش", "tilaus"), ("H", "1", "hold cost", "نگهداری", "sailytys"))),
        ("tx_newsvendor", "ind.ops", "Newsvendor critical fractile", "کسر بحرانی روزنامه‌فروش", "Newsvendor",
         "cu = p - c",
         V(("cu", "1", "underage", "کمبود", "vajaus"), ("p", "1", "price", "قیمت", "hinta"),
           ("c", "1", "cost", "هزینه", "kustannus"))),
        ("tx_littles_inv", "ind.ops", "Inventory Little", "موجودی لیتل", "Varasto Little",
         "Iinv = lam*W",
         V(("Iinv", "1", "inventory", "موجودی", "varasto"), ("lam", "1/s", "throughput", "نرخ", "virta"),
           ("W", "s", "flow time", "زمان جریان", "virta-aika"))),
        ("tx_oee", "ind.ops", "OEE", "اثربخشی کلی تجهیزات", "OEE",
         "oee = A*P*Q",
         V(("oee", "1", "OEE", "OEE", "OEE"), ("A", "1", "availability", "دسترس", "kaytettavyys"),
           ("P", "1", "performance", "عملکرد", "suoritus"), ("Q", "1", "quality", "کیفیت", "laatu"))),
        ("tx_cpk", "ind.ops", "Cpk one-sided min", "Cpk", "Cpk",
         "cpk = (USL - mu)/(3*sigma)",
         V(("cpk", "1", "Cpk", "Cpk", "Cpk"), ("USL", "1", "USL", "حد بالا", "yla"),
           ("mu", "1", "mean", "میانگین", "ka"), ("sigma", "1", "sigma", "سیگما", "sigma"))),
        ("tx_spc_ucl", "ind.ops", "Xbar UCL 3 sigma", "حد کنترل بالا", "UCL",
         "ucl = mu + 3*sigma/sqrt(n)",
         V(("ucl", "1", "UCL", "UCL", "UCL"), ("mu", "1", "mean", "میانگین", "ka"),
           ("sigma", "1", "sigma", "سیگما", "sigma"), ("n", "1", "n", "n", "n"))),
        ("tx_learning", "ind.ops", "Learning curve time", "منحنی یادگیری", "Oppimiskayra",
         "T = T1*n**b",
         V(("T", "h", "time unit n", "زمان واحد n", "aika"), ("T1", "h", "first unit", "اولین", "ensimmainen"),
           ("n", "1", "n", "n", "n"), ("b", "1", "learning exp", "توان یادگیری", "eksponentti"))),
        ("tx_dewpoint_approx", "meteo.air", "Magnus dewpoint approx", "نقطه شبنم", "Kastepiste",
         "td = (b*alpha)/(a - alpha)",
         V(("td", "C", "dewpoint", "شبنم", "kaste"), ("b", "1", "Magnus b", "b", "b"),
           ("alpha", "1", "alpha(T,RH)", "آلفا", "alpha"), ("a", "1", "Magnus a", "a", "a"))),
        ("tx_relhum", "meteo.air", "RH from e/es", "رطوبت نسبی", "Suhteellinen kosteus",
         "rh = 100*e/es",
         V(("rh", "1", "RH %", "رطوبت ٪", "RH %"), ("e", "Pa", "vapor p", "فشار بخار", "hoyry"),
           ("es", "Pa", "sat p", "اشباع", "kyllastys"))),
        ("tx_clausius_es", "meteo.air", "Clausius es over water piece", "فشار اشباع", "Kyllastyspaine",
         "es = e0*exp(L*(1/T0 - 1/T)/Rv)",
         V(("es", "Pa", "es", "es", "es"), ("e0", "Pa", "e0", "e0", "e0"),
           ("L", "J/kg", "Lv", "Lv", "Lv"), ("T0", "K", "T0", "T0", "T0"),
           ("T", "K", "T", "T", "T"), ("Rv", "J/(kg*K)", "Rv", "Rv", "Rv"))),
        ("tx_coriolis", "geo.earth", "Coriolis parameter", "کوریولیس", "Coriolis",
         "f = 2*Omega*sin(lat)",
         V(("f", "1/s", "f", "f", "f"), ("Omega", "1/s", "Omega", "امگا زمین", "Omega"),
           ("lat", "rad", "latitude", "عرض", "leveys"))),
        ("tx_geostrophic", "geo.earth", "Geostrophic wind", "باد زمین‌گرد", "Geostrofinen tuuli",
         "v = (1/(f*rho))*dpdx",
         V(("v", "m/s", "v_g", "v_g", "v_g"), ("f", "1/s", "f", "f", "f"),
           ("rho", "kg/m^3", "rho", "رو", "rho"), ("dpdx", "Pa/m", "dp/dn", "گرادیان فشار", "painegrad"))),
        ("tx_kepler_mu", "physics.astro", "Vis-viva", "ویس-ویوا", "Vis-viva",
         "v = sqrt(mu*(2/r - 1/a))",
         V(("v", "m/s", "v", "v", "v"), ("mu", "m^3/s^2", "GM", "GM", "GM"),
           ("r", "m", "r", "r", "r"), ("a", "m", "a", "a", "a"))),
        ("tx_escape", "physics.gravity", "Escape speed", "سرعت گریز", "Pakonopeus",
         "v = sqrt(2*G*M/r)",
         V(("v", "m/s", "v_esc", "گریز", "pako"), ("G", "m^3/(kg*s^2)", "G", "G", "G"),
           ("M", "kg", "M", "M", "M"), ("r", "m", "r", "r", "r"))),
        ("tx_orbit_circ", "physics.gravity", "Circular orbit speed", "مدار دایره‌ای", "Ympyrarata",
         "v = sqrt(G*M/r)",
         V(("v", "m/s", "v", "v", "v"), ("G", "m^3/(kg*s^2)", "G", "G", "G"),
           ("M", "kg", "M", "M", "M"), ("r", "m", "r", "r", "r"))),
        ("tx_tide_a", "physics.gravity", "Tidal acceleration scale", "شتاب جزر و مد", "Vuorovesi",
         "a = 2*G*M*R/d**3",
         V(("a", "m/s^2", "delta g", "دلتا g", "dg"), ("G", "m^3/(kg*s^2)", "G", "G", "G"),
           ("M", "kg", "M", "M", "M"), ("R", "m", "body radius", "شعاع جسم", "sade"),
           ("d", "m", "separation", "فاصله", "etaisyys"))),
        ("tx_hill", "physics.astro", "Hill radius", "شعاع هیل", "Hill",
         "r = a*(m/(3*M))**(1/3)",
         V(("r", "m", "r_H", "r_H", "r_H"), ("a", "m", "a", "a", "a"),
           ("m", "kg", "small mass", "جرم کوچک", "pieni"), ("M", "kg", "primary", "اصلی", "paa"))),
        ("tx_roche", "physics.astro", "Roche limit fluid", "حد روش", "Roche",
         "d = R*(2*M/m)**(1/3)",
         V(("d", "m", "d", "d", "d"), ("R", "m", "primary R", "شعاع اصلی", "sade"),
           ("M", "kg", "primary", "اصلی", "paa"), ("m", "kg", "satellite", "قمر", "kuu"))),
        ("tx_redshift", "physics.astro", "Redshift z", "انتقال به سرخ", "Punasiirtyma",
         "z = (lam - lam0)/lam0",
         V(("z", "1", "z", "z", "z"), ("lam", "m", "observed", "مشاهده", "havaittu"),
           ("lam0", "m", "rest", "سکون", "lepo"))),
        ("tx_abs_mag", "physics.astro", "Absolute from apparent", "قدر مطلق", "Absoluuttinen kirkkaus",
         "M = m - 5*log(d/10)/log(10)",
         V(("M", "1", "M", "M", "M"), ("m", "1", "m", "m", "m"), ("d", "pc", "d", "d", "d"))),
        ("tx_flux_mag", "physics.astro", "Magnitude from flux ratio", "قدر از شار", "Kirkkaus vuosta",
         "dm = -2.5*log(F1/F0)/log(10)",
         V(("dm", "1", "delta m", "دلتا m", "dm"), ("F1", "W/m^2", "F1", "F1", "F1"),
           ("F0", "W/m^2", "F0", "F0", "F0"))),
        ("tx_jeans", "physics.astro", "Jeans mass scale", "جرم جینز", "Jeans",
         "M = (5*k*T/(G*mu))**(1.5)/sqrt(rho)",
         V(("M", "kg", "M_J", "M_J", "M_J"), ("k", "J/K", "k", "k", "k"),
           ("T", "K", "T", "T", "T"), ("G", "m^3/(kg*s^2)", "G", "G", "G"),
           ("mu", "kg", "mean mass", "جرم میانگین", "massa"), ("rho", "kg/m^3", "rho", "رو", "rho"))),
        ("tx_binding", "physics.nuclear", "Binding per nucleon", "انرژی بستگی هر نوکلئون", "Sidos per nukleoni",
         "b = BE/A",
         V(("b", "MeV", "BE/A", "BE/A", "BE/A"), ("BE", "MeV", "BE", "BE", "BE"), ("A", "1", "A", "A", "A"))),
        ("tx_decay_const", "physics.nuclear", "lambda from half-life", "لامبدا از نیمه‌عمر", "lambda",
         "lam = log(2)/th",
         V(("lam", "1/s", "lambda", "لامبدا", "lambda"), ("th", "s", "t1/2", "t1/2", "t1/2"))),
        ("tx_mean_life", "physics.nuclear", "Mean life", "عمر میانگین", "Keskim. elinaika",
         "tau = 1/lam",
         V(("tau", "s", "tau", "تاو", "tau"), ("lam", "1/s", "lambda", "لامبدا", "lambda"))),
        ("tx_range_nuclear", "physics.nuclear", "Activity remaining", "فعالیت باقی", "Jaljella aktiivisuus",
         "A = A0*exp(-lam*t)",
         V(("A", "Bq", "A", "A", "A"), ("A0", "Bq", "A0", "A0", "A0"),
           ("lam", "1/s", "lambda", "لامبدا", "lambda"), ("t", "s", "t", "t", "t"))),
        ("tx_qvalue_u", "physics.nuclear", "Mass defect energy MeV", "نقص جرم", "Massavaje",
         "E = dm*931.494",
         V(("E", "MeV", "E", "E", "E"), ("dm", "u", "delta m", "دلتا m", "dm"))),
        ("tx_hardy_q", "bio.genetics", "q = 1-p", "q = 1-p", "q = 1-p",
         "q = 1 - p",
         V(("q", "1", "q", "q", "q"), ("p", "1", "p", "p", "p"))),
        ("tx_se_p", "math.stats", "SE of a proportion", "خطای معیار نسبت", "Osuuden keskivirhe",
         "se = sqrt(p*(1 - p)/n)",
         V(("se", "1", "SE", "SE", "SE"), ("p", "1", "p", "p", "p"), ("n", "1", "n", "n", "n"))),
        ("tx_wilson_center", "math.stats", "Wilson center piece", "مرکز ویلسون", "Wilson",
         "c = (p + z**2/(2*n))/(1 + z**2/n)",
         V(("c", "1", "center", "مرکز", "keski"), ("p", "1", "p-hat", "p", "p"),
           ("z", "1", "z", "z", "z"), ("n", "1", "n", "n", "n"))),
        ("tx_fisher_z", "math.stats", "Fisher z of r", "z فیشر", "Fisher z",
         "z = 0.5*log((1 + r)/(1 - r))",
         V(("z", "1", "z", "z", "z"), ("r", "1", "r", "r", "r"))),
        ("tx_cronbach_2", "math.stats", "Cronbach 2 items", "کرونباخ دو گویه", "Cronbach",
         "a0 = 2*r/(1 + r)",
         V(("a0", "1", "alpha", "آلفا", "alpha"), ("r", "1", "inter item r", "همبستگی", "r"))),
        ("tx_icc", "math.stats", "ICC one-way piece", "ICC", "ICC",
         "icc = (msb - msw)/(msb + (k - 1)*msw)",
         V(("icc", "1", "ICC", "ICC", "ICC"), ("msb", "1", "MSB", "MSB", "MSB"),
           ("msw", "1", "MSW", "MSW", "MSW"), ("k", "1", "raters", "ارزیاب", "arvioijat"))),
        ("tx_entropy_nats", "cs.infotheory", "Entropy nats two", "آنتروپی نات", "Entropia nat",
         "H = -p*log(p) - (1 - p)*log(1 - p)",
         V(("H", "nat", "H", "H", "H"), ("p", "1", "p", "p", "p"))),
        ("tx_jsd_def", "cs.infotheory", "JS midpoint", "نقطه میانی جنسن-شانون", "JS keski",
         "m = (p + q)/2",
         V(("m", "1", "m", "m", "m"), ("p", "1", "p", "p", "p"), ("q", "1", "q", "q", "q"))),
        ("tx_tfidf", "cs.infotheory", "idf", "idf", "idf",
         "idf = log(N/df)/log(10)",
         V(("idf", "1", "idf", "idf", "idf"), ("N", "1", "docs", "اسناد", "dokumentit"),
           ("df", "1", "df", "df", "df"))),
        ("tx_perplexity", "cs.infotheory", "Perplexity from H bits", "سرگشتگی", "Perplexity",
         "pp = 2**H",
         V(("pp", "1", "perplexity", "سرگشتگی", "perplexity"), ("H", "bit", "entropy", "آنتروپی", "entropia"))),
        ("tx_f1", "cs.infotheory", "F1 score", "F1", "F1",
         "f1 = 2*p*r/(p + r)",
         V(("f1", "1", "F1", "F1", "F1"), ("p", "1", "precision", "دقت", "tarkkuus"),
           ("r", "1", "recall", "یادآوری", "saanti"))),
        ("tx_accuracy", "cs.infotheory", "Accuracy two-class", "صحت", "Tarkkuus",
         "acc = (tp + tn)/(tp + tn + fp + fn)",
         V(("acc", "1", "accuracy", "صحت", "oikeellisuus"), ("tp", "1", "TP", "TP", "TP"),
           ("tn", "1", "TN", "TN", "TN"), ("fp", "1", "FP", "FP", "FP"), ("fn", "1", "FN", "FN", "FN"))),
        ("tx_mcc", "cs.infotheory", "MCC piece denom", "MCC مخرج", "MCC",
         "den = sqrt((tp + fp)*(tp + fn)*(tn + fp)*(tn + fn))",
         V(("den", "1", "denom", "مخرج", "nimittaja"), ("tp", "1", "TP", "TP", "TP"),
           ("fp", "1", "FP", "FP", "FP"), ("fn", "1", "FN", "FN", "FN"), ("tn", "1", "TN", "TN", "TN"))),
        ("tx_iou", "cs.infotheory", "IoU", "اشتراک بر اجتماع", "IoU",
         "iou = inter/union",
         V(("iou", "1", "IoU", "IoU", "IoU"), ("inter", "1", "intersection", "اشتراک", "leikkaus"),
           ("union", "1", "union", "اجتماع", "yhdiste"))),
        ("tx_softmax2", "cs.infotheory", "Softmax two logits", "سافت‌مکس دو تا", "Softmax",
         "p = exp(a)/(exp(a) + exp(b))",
         V(("p", "1", "p_a", "p_a", "p_a"), ("a", "1", "logit a", "لوجیت a", "logit a"),
           ("b", "1", "logit b", "لوجیت b", "logit b"))),
        ("tx_crossent2", "cs.infotheory", "Binary cross-entropy", "آنتروپی متقابل دودویی", "Ristiinentropia",
         "L = -y*log(p) - (1 - y)*log(1 - p)",
         V(("L", "1", "loss", "زیان", "tappio"), ("y", "1", "label", "برچسب", "luokka"),
           ("p", "1", "p", "p", "p"))),
        ("tx_l2_reg", "math.opt", "L2 ridge penalty", "جریمه ریج", "L2-sakko",
         "p = lam*w**2",
         V(("p", "1", "penalty", "جریمه", "sakko"), ("lam", "1", "lambda", "لامبدا", "lambda"),
           ("w", "1", "weight", "وزن", "paino"))),
        ("tx_hinge", "math.opt", "Hinge slack", "hinge", "Hinge",
         "xi = Max(0, 1 - y*s)",
         V(("xi", "1", "slack", "slack", "slack"), ("y", "1", "label", "برچسب", "luokka"),
           ("s", "1", "score", "امتیاز", "piste"))),
        ("tx_kmeans_2", "math.opt", "Two-point 1D k-means center", "مرکز k-means", "k-means keskus",
         "c = (x1 + x2)/2",
         V(("c", "1", "center", "مرکز", "keskus"), ("x1", "1", "x1", "x1", "x1"),
           ("x2", "1", "x2", "x2", "x2"))),
        ("tx_pca_var", "math.stats", "Explained variance ratio", "سهم واریانس", "Selitetty varianssi",
         "r = lam1/(lam1 + lam2)",
         V(("r", "1", "ratio", "سهم", "osuus"), ("lam1", "1", "lambda1", "لامبدا۱", "l1"),
           ("lam2", "1", "lambda2", "لامبدا۲", "l2"))),
        ("tx_mae", "math.stats", "MAE two points", "MAE", "MAE",
         "mae = (abs(y1 - yhat1) + abs(y2 - yhat2))/2",
         V(("mae", "1", "MAE", "MAE", "MAE"), ("y1", "1", "y1", "y1", "y1"),
           ("yhat1", "1", "yhat1", "yhat1", "yhat1"), ("y2", "1", "y2", "y2", "y2"),
           ("yhat2", "1", "yhat2", "yhat2", "yhat2"))),
        ("tx_mse", "math.stats", "MSE two points", "MSE", "MSE",
         "mse = ((y1 - yhat1)**2 + (y2 - yhat2)**2)/2",
         V(("mse", "1", "MSE", "MSE", "MSE"), ("y1", "1", "y1", "y1", "y1"),
           ("yhat1", "1", "yhat1", "yhat1", "yhat1"), ("y2", "1", "y2", "y2", "y2"),
           ("yhat2", "1", "yhat2", "yhat2", "yhat2"))),
        ("tx_mape", "math.stats", "MAPE one point", "MAPE", "MAPE",
         "mape = 100*abs((y - yhat)/y)",
         V(("mape", "1", "MAPE %", "MAPE", "MAPE"), ("y", "1", "y", "y", "y"),
           ("yhat", "1", "yhat", "yhat", "yhat"))),
        ("tx_huber_quad", "math.opt", "Huber quadratic piece", "هوبر مربعی", "Huber",
         "L = 0.5*a**2",
         V(("L", "1", "loss", "زیان", "tappio"), ("a", "1", "residual", "باقیمانده", "jaannos"))),
        ("tx_elastic", "econ.micro", "Arc elasticity", "کشش کمانی", "Kaarijousto",
         "e = ((q2 - q1)/(q2 + q1))/((p2 - p1)/(p2 + p1))",
         V(("e", "1", "e", "e", "e"), ("q2", "1", "q2", "q2", "q2"), ("q1", "1", "q1", "q1", "q1"),
           ("p2", "1", "p2", "p2", "p2"), ("p1", "1", "p1", "p1", "p1"))),
        ("tx_markup", "econ.micro", "Markup from elasticity", "مارکاپ از کشش", "Kate joustosta",
         "m = 1/abs(e)",
         V(("m", "1", "markup", "مارکاپ", "kate"), ("e", "1", "elasticity", "کشش", "jousto"))),
        ("tx_gini2", "soc.demo", "Gini two equal groups", "جینی دو گروه", "Gini",
         "g = abs(s1 - s2)",
         V(("g", "1", "Gini piece", "جینی", "Gini"), ("s1", "1", "share1", "سهم ۱", "osuus1"),
           ("s2", "1", "share2", "سهم ۲", "osuus2"))),
        ("tx_tfr", "soc.demo", "TFR from 7 ASFR*5", "باروری کل", "TFR",
         "tfr = 5*s",
         V(("tfr", "1", "TFR", "TFR", "TFR"), ("s", "1", "sum ASFR", "جمع ASFR", "ASFR-summa"))),
        ("tx_doubling_pop", "soc.demo", "Population doubling", "دو برابر جمعیت", "Vaeston kahdentuminen",
         "t = log(2)/r",
         V(("t", "yr", "years", "سال", "vuodet"), ("r", "1/yr", "growth rate", "نرخ رشد", "kasvu"))),
        ("tx_cbr", "soc.demo", "Crude birth rate", "نرخ خام موالید", "Syntyvyys",
         "cbr = 1000*B/P",
         V(("cbr", "1", "CBR", "CBR", "CBR"), ("B", "1", "births", "موالید", "syntyneet"),
           ("P", "1", "population", "جمعیت", "vaesto"))),
        ("tx_imr", "soc.demo", "Infant mortality", "مرگ‌ومیر نوزاد", "Imevaiskuolleisuus",
         "imr = 1000*D/B",
         V(("imr", "1", "IMR", "IMR", "IMR"), ("D", "1", "infant deaths", "مرگ نوزاد", "kuolemat"),
           ("B", "1", "births", "موالید", "syntyneet"))),
        ("tx_ndvi", "geo.earth", "NDVI", "NDVI", "NDVI",
         "n = (nir - red)/(nir + red)",
         V(("n", "1", "NDVI", "NDVI", "NDVI"), ("nir", "1", "NIR", "فروسرخ نزدیک", "NIR"),
           ("red", "1", "red", "قرمز", "punainen"))),
        ("tx_beer_atm", "meteo.air", "Beer optical depth I", "بیر جو", "Beer ilmakeha",
         "Iout = Iin*exp(-tau)",
         V(("Iout", "W/m^2", "I", "I", "I"), ("Iin", "W/m^2", "I0", "I0", "I0"),
           ("tau", "1", "optical depth", "عمق نوری", "optinen syvyys"))),
        ("tx_albedo_net", "geo.earth", "Net shortwave", "خورشید خالص", "Netto lyhytaalto",
         "Snet = (1 - a)*Sdown",
         V(("Snet", "W/m^2", "Snet", "Snet", "Snet"), ("a", "1", "albedo", "آلبدو", "albedo"),
           ("Sdown", "W/m^2", "Sdown", "فرودی", "tuleva"))),
        ("tx_penman_simp", "geo.hydro", "Priestley-Taylor", "پریستلی-تیلور", "Priestley-Taylor",
         "ET = 1.26*(s/(s + gam))*Rn/L",
         V(("ET", "W/m^2", "ET energy", "ET", "ET"), ("s", "Pa/K", "slope", "شیب", "kaltevuus"),
           ("gam", "Pa/K", "psychrometric", "سایکرومتریک", "psykrometrinen"),
           ("Rn", "W/m^2", "net rad", "تابش خالص", "nettosateily"), ("L", "J/kg", "Lv", "Lv", "Lv"))),
        ("tx_infil_horton", "geo.hydro", "Horton infiltration f_c piece", "هورتون", "Horton",
         "f = fc + (f0 - fc)*exp(-k*t)",
         V(("f", "m/s", "f", "f", "f"), ("fc", "m/s", "fc", "fc", "fc"),
           ("f0", "m/s", "f0", "f0", "f0"), ("k", "1/s", "k", "k", "k"), ("t", "s", "t", "t", "t"))),
        ("tx_manning_Q", "geo.hydro", "Manning discharge", "دبی مانینگ", "Manning Q",
         "Q = A*(1/n)*Rh**(2/3)*S**0.5",
         V(("Q", "m^3/s", "Q", "Q", "Q"), ("A", "m^2", "A", "A", "A"),
           ("n", "1", "n", "n", "n"), ("Rh", "m", "Rh", "Rh", "Rh"), ("S", "1", "S", "S", "S"))),
        ("tx_chezy_Q", "geo.hydro", "Chezy discharge", "دبی شزی", "Chezy Q",
         "Q = A*C*sqrt(Rh*S)",
         V(("Q", "m^3/s", "Q", "Q", "Q"), ("A", "m^2", "A", "A", "A"),
           ("C", "m^0.5/s", "C", "C", "C"), ("Rh", "m", "Rh", "Rh", "Rh"), ("S", "1", "S", "S", "S"))),
        ("tx_dupuit", "geo.hydro", "Dupuit unconfined well", "دوپویی", "Dupuit",
         "Q = pi*K*(H2**2 - H1**2)/log(R/r)",
         V(("Q", "m^3/s", "Q", "Q", "Q"), ("K", "m/s", "K", "K", "K"),
           ("H2", "m", "H2", "H2", "H2"), ("H1", "m", "H1", "H1", "H1"),
           ("R", "m", "R", "R", "R"), ("r", "m", "r", "r", "r"))),
        ("tx_theis_u", "geo.hydro", "Theis u", "تایس u", "Theis u",
         "u = r**2*S/(4*T*t)",
         V(("u", "1", "u", "u", "u"), ("r", "m", "r", "r", "r"), ("S", "1", "S", "S", "S"),
           ("T", "m^2/s", "T", "T", "T"), ("t", "s", "t", "t", "t"))),
        ("tx_concrete_wc", "eng.conc", "w/c ratio", "نسبت آب به سیمان", "v/s",
         "wc = w/c",
         V(("wc", "1", "w/c", "آب/سیمان", "v/s"), ("w", "kg", "water", "آب", "vesi"),
           ("c", "kg", "cement", "سیمان", "sementti"))),
        ("tx_ Abrams", "eng.conc", "Abrams strength piece", "آبرامز", "Abrams",
         "fc = A/B**wc",
         V(("fc", "Pa", "f'c", "مقاومت", "lujuus"), ("A", "Pa", "A", "A", "A"),
           ("B", "1", "B", "B", "B"), ("wc", "1", "w/c", "آب/سیمان", "v/s"))),
        ("tx_rebar_as", "eng.conc", "Steel ratio rho", "نسبت فولاد", "Terassuhde",
         "rho = As/b/d",
         V(("rho", "1", "rho", "رو", "rho"), ("As", "m^2", "As", "As", "As"),
           ("b", "m", "b", "b", "b"), ("d", "m", "d", "d", "d"))),
        ("tx_Mn_singly", "eng.conc", "Singly reinforced Mn", "لنگر اسمی", "Mn",
         "Mn = As*fy*(d - a/2)",
         V(("Mn", "N*m", "Mn", "Mn", "Mn"), ("As", "m^2", "As", "As", "As"),
           ("fy", "Pa", "fy", "fy", "fy"), ("d", "m", "d", "d", "d"), ("a", "m", "a", "a", "a"))),
        ("tx_whitney_a", "eng.conc", "Whitney a from beta1", "ارتفاع بلوک ویتنی", "Whitney a",
         "a = beta1*c",
         V(("a", "m", "a", "a", "a"), ("beta1", "1", "beta1", "بتا۱", "beta1"), ("c", "m", "c", "c", "c"))),
        ("tx_steel_Ix", "eng.steel", "Rectangle I", "اینرسی مستطیل", "Suorakaiteen I",
         "Izz = b*h**3/12",
         V(("Izz", "m^4", "I", "I", "I"), ("b", "m", "b", "b", "b"), ("h", "m", "h", "h", "h"))),
        ("tx_steel_S", "eng.steel", "Elastic section modulus", "مدول مقطع", "Taivutusvastus",
         "S = Izz/c",
         V(("S", "m^3", "S", "S", "S"), ("Izz", "m^4", "I", "I", "I"), ("c", "m", "c", "c", "c"))),
        ("tx_steel_Zrect", "eng.steel", "Plastic Z rectangle", "مدول پلاستیک", "Plastinen Z",
         "Z = b*h**2/4",
         V(("Z", "m^3", "Z", "Z", "Z"), ("b", "m", "b", "b", "b"), ("h", "m", "h", "h", "h"))),
        ("tx_rgyr", "eng.steel", "Radius of gyration", "شعاع ژیراسیون", "Hitaussade",
         "k = sqrt(Izz/A)",
         V(("k", "m", "k", "k", "k"), ("Izz", "m^4", "I", "I", "I"), ("A", "m^2", "A", "A", "A"))),
        ("tx_weld_throat", "eng.weld", "Fillet throat", "گلوگاه جوش گوشه‌ای", "Hitsin kurkku",
         "t = 0.707*w",
         V(("t", "m", "throat", "گلوگاه", "kurkku"), ("w", "m", "leg", "ساق", "kateetti"))),
        ("tx_weld_stress", "eng.weld", "Fillet weld stress", "تنش جوش", "Hitsijannitys",
         "tau = P/(0.707*w*L)",
         V(("tau", "Pa", "tau", "تنش", "jannitys"), ("P", "N", "P", "P", "P"),
           ("w", "m", "leg", "ساق", "kateetti"), ("L", "m", "length", "طول", "pituus"))),
        ("tx_heat_input", "eng.weld", "Welding heat input", "ورودی گرمای جوش", "Hitsauslampo",
         "H = eta*V*i/s",
         V(("H", "J/m", "H", "H", "H"), ("eta", "1", "efficiency", "بازده", "hyotysuhde"),
           ("V", "V", "V", "V", "V"), ("i", "A", "current", "جریان", "virta"), ("s", "m/s", "speed", "سرعت", "nopeus"))),
        ("tx_psych_w", "eng.hvac2", "Humidity ratio from pv", "نسبت رطوبت", "Kosteussuhde",
         "w = 0.622*pv/(P - pv)",
         V(("w", "1", "w", "w", "w"), ("pv", "Pa", "vapor p", "فشار بخار", "hoyry"),
           ("P", "Pa", "total p", "فشار کل", "kokonaispaine"))),
        ("tx_relhum_hvac", "eng.hvac2", "RH from pv/pws", "رطوبت نسبی HVAC", "RH",
         "rh = pv/pws",
         V(("rh", "1", "RH", "RH", "RH"), ("pv", "Pa", "pv", "pv", "pv"), ("pws", "Pa", "pws", "pws", "pws"))),
        ("tx_wetbulb_approx", "eng.hvac2", "Wet-bulb depression piece", "افت دمای حباب تر", "Markalampotila",
         "tw = t - k*(es - e)",
         V(("tw", "C", "Twb", "حباب تر", "Twb"), ("t", "C", "Tdb", "حباب خشک", "Tdb"),
           ("k", "K/Pa", "k", "k", "k"), ("es", "Pa", "es(T)", "es", "es"), ("e", "Pa", "e", "e", "e"))),
        ("tx_enth_moist", "eng.hvac2", "Moist air enthalpy SI", "آنتالپی هوای مرطوب", "Kostean ilman H",
         "h = 1.006*t + w*(2501 + 1.86*t)",
         V(("h", "kJ/kg", "h", "h", "h"), ("t", "C", "Tdb", "حباب خشک", "Tdb"),
           ("w", "1", "humidity ratio", "نسبت رطوبت", "kosteussuhde"))),
        ("tx_sens_heat", "eng.hvac", "Sensible heat air", "گرمای محسوس هوا", "Tuntoinen lampo",
         "q = 1.006*m*dT",
         V(("q", "kW", "q", "q", "q"), ("m", "kg/s", "mass flow", "دبی", "virta"),
           ("dT", "K", "dT", "dT", "dT"))),
        ("tx_lat_heat", "eng.hvac", "Latent heat air", "گرمای نهان هوا", "Piileva lampo",
         "q = m*hfg*dw",
         V(("q", "kW", "q", "q", "q"), ("m", "kg/s", "m", "m", "m"),
           ("hfg", "kJ/kg", "hfg", "hfg", "hfg"), ("dw", "1", "dw", "dw", "dw"))),
        ("tx_degree_day", "eng.hvac", "Heating degree-days", "درجه-روز گرمایش", "Lammitystarveluku",
         "HDD = n*(Tbase - Tavg)",
         V(("HDD", "K*d", "HDD", "HDD", "HDD"), ("n", "d", "days", "روز", "paivat"),
           ("Tbase", "C", "base", "پایه", "perus"), ("Tavg", "C", "mean T", "میانگین", "ka T"))),
        ("tx_uvalue", "eng.hvac", "U from R", "U از R", "U R:sta",
         "U = 1/Rtot",
         V(("U", "W/(m^2*K)", "U", "U", "U"), ("Rtot", "m^2*K/W", "Rtot", "Rtot", "Rtot"))),
        ("tx_r_layer", "eng.hvac", "Layer R", "R لایه", "Kerroksen R",
         "R = L/k",
         V(("R", "m^2*K/W", "R", "R", "R"), ("L", "m", "thickness", "ضخامت", "paksuus"),
           ("k", "W/(m*K)", "k", "k", "k"))),
        ("tx_infil_q", "eng.hvac", "Infiltration sensible", "نفوذ هوا", "Vuotoilma",
         "q = 1.2*Q*dT",
         V(("q", "W", "q", "q", "q"), ("Q", "m^3/s", "Q", "Q", "Q"), ("dT", "K", "dT", "dT", "dT"))),
        ("tx_ach", "eng.hvac", "Air changes per hour", "تعویض هوا در ساعت", "Ilmanvaihtokerroin",
         "ach = 3600*Q/V",
         V(("ach", "1/h", "ACH", "ACH", "ACH"), ("Q", "m^3/s", "Q", "Q", "Q"), ("V", "m^3", "volume", "حجم", "tilavuus"))),
        ("tx_cop_hp", "eng.hvac", "Heat pump COP", "COP پمپ گرما", "Lampopumpun COP",
         "COP = Qh/W",
         V(("COP", "1", "COP", "COP", "COP"), ("Qh", "W", "heat out", "گرمای خروجی", "lampo"),
           ("W", "W", "work in", "کار ورودی", "tyo"))),
        ("tx_eer", "eng.hvac", "EER from COP", "EER", "EER",
         "eer = 3.412*COP",
         V(("eer", "1", "EER", "EER", "EER"), ("COP", "1", "COP", "COP", "COP"))),
        ("tx_seer_approx", "eng.hvac", "SEER from EER approx", "SEER", "SEER",
         "seer = 1.12*eer - 0.02*eer**2",
         V(("seer", "1", "SEER", "SEER", "SEER"), ("eer", "1", "EER", "EER", "EER"))),
        ("tx_fan_law_q", "eng.hvac", "Fan law flow", "قانون فن دبی", "Puhallin Q",
         "Q2 = Q1*(n2/n1)",
         V(("Q2", "m^3/s", "Q2", "Q2", "Q2"), ("Q1", "m^3/s", "Q1", "Q1", "Q1"),
           ("n2", "1/s", "n2", "n2", "n2"), ("n1", "1/s", "n1", "n1", "n1"))),
        ("tx_fan_law_p", "eng.hvac", "Fan law pressure", "قانون فن فشار", "Puhallin p",
         "p2 = p1*(n2/n1)**2",
         V(("p2", "Pa", "p2", "p2", "p2"), ("p1", "Pa", "p1", "p1", "p1"),
           ("n2", "1/s", "n2", "n2", "n2"), ("n1", "1/s", "n1", "n1", "n1"))),
        ("tx_fan_law_W", "eng.hvac", "Fan law power", "قانون فن توان", "Puhallin teho",
         "W2 = W1*(n2/n1)**3",
         V(("W2", "W", "W2", "W2", "W2"), ("W1", "W", "W1", "W1", "W1"),
           ("n2", "1/s", "n2", "n2", "n2"), ("n1", "1/s", "n1", "n1", "n1"))),
        ("tx_duct_eq", "eng.hvac", "Equivalent round duct", "کانال گرد معادل", "Ympyrikanava",
         "D = 1.3*(a*b)**0.625/(a + b)**0.25",
         V(("D", "m", "Deq", "معادل", "ekv"), ("a", "m", "a", "a", "a"), ("b", "m", "b", "b", "b"))),
        ("tx_coil_q", "eng.hvac", "Coil load air", "بار کویل", "Patterin teho",
         "q = m*(h1 - h2)",
         V(("q", "kW", "q", "q", "q"), ("m", "kg/s", "m", "m", "m"),
           ("h1", "kJ/kg", "h1", "h1", "h1"), ("h2", "kJ/kg", "h2", "h2", "h2"))),
        ("tx_shr", "eng.hvac", "Sensible heat ratio", "نسبت گرمای محسوس", "Tuntoisen lampo-osuus",
         "shr = qs/qt",
         V(("shr", "1", "SHR", "SHR", "SHR"), ("qs", "W", "sensible", "محسوس", "tuntoinen"),
           ("qt", "W", "total", "کل", "kokonais"))),
        ("tx_bypass", "eng.hvac", "Bypass factor", "ضریب کنارگذر", "Ohituskerroin",
         "bf = (t2 - tc)/(t1 - tc)",
         V(("bf", "1", "BF", "BF", "BF"), ("t2", "C", "leaving", "خروجی", "lahto"),
           ("tc", "C", "coil", "کویل", "patteri"), ("t1", "C", "entering", "ورود", "tulo"))),
        ("tx_adp", "eng.hvac", "Apparatus dew point mix", "نقطه شبنم دستگاه", "Laitteen kaste",
         "t2 = bf*t1 + (1 - bf)*tadp",
         V(("t2", "C", "leaving", "خروجی", "lahto"), ("bf", "1", "BF", "BF", "BF"),
           ("t1", "C", "entering", "ورود", "tulo"), ("tadp", "C", "ADP", "ADP", "ADP"))),
        ("tx_ventilation_rp", "eng.hvac", "ASHRAE people+area", "تهویه افراد+مساحت", "Ilmanvaihto",
         "Q = Rp*Pz + Ra*Az",
         V(("Q", "L/s", "Q", "Q", "Q"), ("Rp", "L/s", "Rp", "Rp", "Rp"),
           ("Pz", "1", "people", "افراد", "ihmiset"), ("Ra", "L/(s*m^2)", "Ra", "Ra", "Ra"),
           ("Az", "m^2", "area", "مساحت", "pinta"))),
    ]
    # drop malformed id
    extra = [e for e in extra if e[0] != "tx_ Abrams"]
    extra.append(("tx_abrams", "eng.conc", "Abrams strength piece", "آبرامز", "Abrams",
                  "fc = A/B**wc",
                  V(("fc", "Pa", "f'c", "مقاومت", "lujuus"), ("A", "Pa", "A", "A", "A"),
                    ("B", "1", "B", "B", "B"), ("wc", "1", "w/c", "آب/سیمان", "v/s"))))
    for it in extra:
        a(row(*it))
    return R
