"""More textbook formula rows. Imported by add_textbook_formulas.py."""

from __future__ import annotations

from add_textbook_formulas import V, row


def stats_prob():
    R = []
    a = R.append
    items = [
        ("tx_zscore", "math.stats", "z-score", "نمره استاندارد", "z-arvo",
         "z = (x - mu)/sigma",
         V(("z", "1", "z", "z", "z"), ("x", "1", "value", "مقدار", "arvo"),
           ("mu", "1", "mean", "میانگین", "keskiarvo"), ("sigma", "1", "stdev", "انحراف معیار", "keskihajonta"))),
        ("tx_tscore", "math.stats", "t statistic one sample", "آماره t یک نمونه", "t-arvo",
         "t = (xbar - mu)/(s/sqrt(n))",
         V(("t", "1", "t", "t", "t"), ("xbar", "1", "sample mean", "میانگین نمونه", "otoksen ka"),
           ("mu", "1", "hypothesized mean", "میانگین فرض", "oletettu ka"), ("s", "1", "sample sd", "انحراف نمونه", "otoksen kh"),
           ("n", "1", "n", "n", "n"))),
        ("tx_se_mean", "math.stats", "Standard error of the mean", "خطای معیار میانگین", "Keskivirhe",
         "se = s/sqrt(n)",
         V(("se", "1", "SE", "خطای معیار", "keskivirhe"), ("s", "1", "sd", "انحراف", "kh"), ("n", "1", "n", "n", "n"))),
        ("tx_ci_half", "math.stats", "CI half-width known sigma", "نیم‌عرض فاصله اطمینان", "Luottamusvalin puolileveys",
         "h = z*sigma/sqrt(n)",
         V(("h", "1", "half-width", "نیم‌عرض", "puolileveys"), ("z", "1", "z critical", "z بحرانی", "z-kriittinen"),
           ("sigma", "1", "sigma", "سیگما", "sigma"), ("n", "1", "n", "n", "n"))),
        ("tx_sample_size_mean", "math.stats", "Sample size for mean", "حجم نمونه میانگین", "Otoskoko keskiarvolle",
         "n = (z*sigma/Eerr)**2",
         V(("n", "1", "n", "n", "n"), ("z", "1", "z", "z", "z"), ("sigma", "1", "sigma", "سیگما", "sigma"),
           ("Eerr", "1", "margin", "حاشیه", "virhemarginaali"))),
        ("tx_sample_size_p", "math.stats", "Sample size for proportion", "حجم نمونه نسبت", "Otoskoko osuudelle",
         "n = z**2*p*(1 - p)/Eerr**2",
         V(("n", "1", "n", "n", "n"), ("z", "1", "z", "z", "z"), ("p", "1", "p", "p", "p"),
           ("Eerr", "1", "margin", "حاشیه", "virhemarginaali"))),
        ("tx_pooled_p", "math.stats", "Pooled proportion", "نسبت ادغام‌شده", "Yhdistetty osuus",
         "p = (x1 + x2)/(n1 + n2)",
         V(("p", "1", "pooled p", "p ادغام", "yhdistetty p"), ("x1", "1", "successes 1", "موفقیت ۱", "onnistumiset 1"),
           ("x2", "1", "successes 2", "موفقیت ۲", "onnistumiset 2"), ("n1", "1", "n1", "n1", "n1"), ("n2", "1", "n2", "n2", "n2"))),
        ("tx_chi2_cell", "math.stats", "Chi-square cell", "خانه خی‌دو", "Khiin nelio solu",
         "c = (o - e)**2/e",
         V(("c", "1", "cell", "خانه", "solu"), ("o", "1", "observed", "مشاهده", "havaittu"), ("e", "1", "expected", "انتظار", "odotettu"))),
        ("tx_cramers_v", "math.stats", "Cramer's V 2x2", "وی کرامر", "Cramerin V",
         "v = sqrt(chi/(n*1))",
         V(("v", "1", "V", "V", "V"), ("chi", "1", "chi-square", "خی‌دو", "khi2"), ("n", "1", "n", "n", "n"))),
        ("tx_pearson_r", "math.stats", "Pearson r from cov", "همبستگی پیرسون", "Pearson r",
         "r = cov/(sx*sy)",
         V(("r", "1", "r", "r", "r"), ("cov", "1", "covariance", "کوواریانس", "kovarianssi"),
           ("sx", "1", "sx", "sx", "sx"), ("sy", "1", "sy", "sy", "sy"))),
        ("tx_spearman_simple", "math.stats", "Spearman from rank diffs", "اسپیرمن", "Spearman",
         "r = 1 - 6*s/(n*(n**2 - 1))",
         V(("r", "1", "rho", "رو", "rho"), ("s", "1", "sum d^2", "جمع مربع اختلاف رتبه", "sijoituserojen neliot"),
           ("n", "1", "n", "n", "n"))),
        ("tx_reg_slope", "math.stats", "OLS slope one predictor", "شیب رگرسیون", "Regressiokulmakerroin",
         "b = r*sy/sx",
         V(("b", "1", "slope", "شیب", "kulmakerroin"), ("r", "1", "r", "r", "r"),
           ("sy", "1", "sy", "sy", "sy"), ("sx", "1", "sx", "sx", "sx"))),
        ("tx_reg_int", "math.stats", "OLS intercept", "عرض از مبدأ رگرسیون", "Regressiovakiotermi",
         "a0 = ybar - b*xbar",
         V(("a0", "1", "intercept", "عرض از مبدأ", "vakiotermi"), ("ybar", "1", "mean y", "میانگین y", "y-ka"),
           ("b", "1", "slope", "شیب", "kulmakerroin"), ("xbar", "1", "mean x", "میانگین x", "x-ka"))),
        ("tx_r2_from_r", "math.stats", "R-squared from r", "ضریب تعیین", "Selitysaste",
         "R2 = r**2",
         V(("R2", "1", "R^2", "R^2", "R^2"), ("r", "1", "r", "r", "r"))),
        ("tx_resid_var", "math.stats", "Residual variance simple", "واریانس باقیمانده", "Jaannosvarianssi",
         "s2 = sse/(n - 2)",
         V(("s2", "1", "s^2", "s^2", "s^2"), ("sse", "1", "SSE", "SSE", "SSE"), ("n", "1", "n", "n", "n"))),
        ("tx_iqr", "math.stats", "Interquartile range", "دامنه میان‌چارکی", "Kvartilivali",
         "iqr = q3 - q1",
         V(("iqr", "1", "IQR", "IQR", "IQR"), ("q3", "1", "Q3", "Q3", "Q3"), ("q1", "1", "Q1", "Q1", "Q1"))),
        ("tx_cv", "math.stats", "Coefficient of variation", "ضریب تغییرات", "Variaatiokerroin",
         "cv = 100*s/m",
         V(("cv", "1", "CV percent", "درصد CV", "CV %"), ("s", "1", "sd", "انحراف", "kh"), ("m", "1", "mean", "میانگین", "ka"))),
        ("tx_skew_moment", "math.stats", "Moment skewness", "چولگی گشتاوری", "Vinous",
         "g = m3/s**3",
         V(("g", "1", "skewness", "چولگی", "vinous"), ("m3", "1", "3rd central moment", "گشتاور سوم", "3. momentti"),
           ("s", "1", "sd", "انحراف", "kh"))),
        ("tx_kurt_moment", "math.stats", "Moment excess kurtosis", "کشیدگی اضافی", "Huipukkuus",
         "g = m4/s**4 - 3",
         V(("g", "1", "excess kurtosis", "کشیدگی اضافی", "huipukkuus"), ("m4", "1", "4th moment", "گشتاور چهارم", "4. momentti"),
           ("s", "1", "sd", "انحراف", "kh"))),
        ("tx_weighted_mean", "math.stats", "Weighted mean two", "میانگین وزنی دو تا", "Painotettu keskiarvo",
         "m = (w1*x1 + w2*x2)/(w1 + w2)",
         V(("m", "1", "mean", "میانگین", "ka"), ("w1", "1", "w1", "وزن ۱", "p1"), ("x1", "1", "x1", "x1", "x1"),
           ("w2", "1", "w2", "وزن ۲", "p2"), ("x2", "1", "x2", "x2", "x2"))),
        ("tx_pop_var_def", "math.stats", "Population variance two pts", "واریانس جامعه دو نقطه", "Perusjoukon varianssi",
         "v = ((x1 - m)**2 + (x2 - m)**2)/2",
         V(("v", "1", "variance", "واریانس", "varianssi"), ("x1", "1", "x1", "x1", "x1"), ("x2", "1", "x2", "x2", "x2"),
           ("m", "1", "mean", "میانگین", "ka"))),
        ("tx_sd_from_var", "math.stats", "SD from variance", "انحراف از واریانس", "Keskihajonta varianssista",
         "s = sqrt(v)",
         V(("s", "1", "sd", "انحراف", "kh"), ("v", "1", "variance", "واریانس", "varianssi"))),
        ("tx_anova_ssb", "math.stats", "ANOVA SSB two groups", "مجموع مربعات بین", "ANOVA SSB",
         "ssb = n1*(m1 - m)**2 + n2*(m2 - m)**2",
         V(("ssb", "1", "SSB", "SSB", "SSB"), ("n1", "1", "n1", "n1", "n1"), ("m1", "1", "mean 1", "میانگین ۱", "ka1"),
           ("n2", "1", "n2", "n2", "n2"), ("m2", "1", "mean 2", "میانگین ۲", "ka2"), ("m", "1", "grand mean", "میانگین کل", "yleiska"))),
        ("tx_cohens_d", "math.stats", "Cohen d two groups", "d کوهن", "Cohenin d",
         "d = (m1 - m2)/s",
         V(("d", "1", "d", "d", "d"), ("m1", "1", "mean 1", "میانگین ۱", "ka1"), ("m2", "1", "mean 2", "میانگین ۲", "ka2"),
           ("s", "1", "pooled sd", "انحراف ادغام", "yhdistetty kh"))),
        ("tx_odds", "math.stats", "Odds from probability", "شانس از احتمال", "Vedonlyontikerroin",
         "o = p/(1 - p)",
         V(("o", "1", "odds", "شانس", "kerroin"), ("p", "1", "probability", "احتمال", "tn"))),
        ("tx_logit", "math.stats", "Logit", "لوجیت", "Logit",
         "L = log(p/(1 - p))",
         V(("L", "1", "logit", "لوجیت", "logit"), ("p", "1", "p", "p", "p"))),
        ("tx_logistic", "math.stats", "Logistic function", "تابع لجستیک", "Logistinen funktio",
         "p = 1/(1 + exp(-L))",
         V(("p", "1", "p", "p", "p"), ("L", "1", "logit", "لوجیت", "logit"))),
        ("tx_mad", "math.stats", "Mean absolute deviation two", "انحراف مطلق میانگین", "Keskim. itseisarvopoikkeama",
         "mad = (abs(x1 - m) + abs(x2 - m))/2",
         V(("mad", "1", "MAD", "MAD", "MAD"), ("x1", "1", "x1", "x1", "x1"), ("x2", "1", "x2", "x2", "x2"),
           ("m", "1", "mean", "میانگین", "ka"))),
    ]
    for it in items:
        a(row(*it))

    # distribution moments
    dists = [
        ("binom", "Binomial", "دوجمله‌ای", "Binomi", "n*p", "n*p*(1 - p)",
         V(("n", "1", "n", "n", "n"), ("p", "1", "p", "p", "p"))),
        ("poiss", "Poisson", "پواسون", "Poisson", "lam", "lam",
         V(("lam", "1", "lambda", "لامبدا", "lambda"))),
        ("geom", "Geometric (trials)", "هندسی", "Geometrinen", "1/p", "(1 - p)/p**2",
         V(("p", "1", "p", "p", "p"))),
        ("nbinom", "Neg. binomial (failures)", "دوجمله‌ای منفی", "Neg.binomi", "k*(1 - p)/p", "k*(1 - p)/p**2",
         V(("k", "1", "successes k", "موفقیت", "onnistumiset"), ("p", "1", "p", "p", "p"))),
        ("unif", "Continuous uniform", "یکنواخت پیوسته", "Tasainen", "(a + b)/2", "(b - a)**2/12",
         V(("a", "1", "a", "a", "a"), ("b", "1", "b", "b", "b"))),
        ("expd", "Exponential", "نمایی", "Eksponentti", "1/lam", "1/lam**2",
         V(("lam", "1/s", "rate", "نرخ", "nopeus"))),
        ("gamma", "Gamma (shape-rate)", "گاما", "Gamma", "k/lam", "k/lam**2",
         V(("k", "1", "shape", "شکل", "muoto"), ("lam", "1", "rate", "نرخ", "nopeus"))),
        ("weib", "Weibull 2-param mean", "وایبل میانگین", "Weibull ka", "lam*exp(log(1 + 1/k))", "0",
         V(("lam", "1", "scale", "مقیاس", "skaala"), ("k", "1", "shape", "شکل", "muoto"))),
        ("logn", "Lognormal mean", "لگ‌نرمال میانگین", "Lognorm. ka", "exp(mu + sig**2/2)", "exp(2*mu + sig**2)*(exp(sig**2) - 1)",
         V(("mu", "1", "mu", "مو", "mu"), ("sig", "1", "sigma", "سیگما", "sigma"))),
        ("beta", "Beta mean", "بتا میانگین", "Beta ka", "a/(a + b)", "a*b/((a + b)**2*(a + b + 1))",
         V(("a", "1", "alpha", "آلفا", "alpha"), ("b", "1", "beta shape", "بتا شکل", "beta"))),
        ("pareto", "Pareto mean xm,a>1", "پارتو میانگین", "Pareto ka", "a*xm/(a - 1)", "a*xm**2/((a - 1)**2*(a - 2))",
         V(("a", "1", "shape", "شکل", "muoto"), ("xm", "1", "xmin", "xmin", "xmin"))),
        ("rayl", "Rayleigh mean", "رِیلی میانگین", "Rayleigh ka", "sig*sqrt(pi/2)", "sig**2*(4 - pi)/2",
         V(("sig", "1", "sigma", "سیگما", "sigma"))),
        ("chi2", "Chi-square mean", "خی‌دو میانگین", "Khi2 ka", "k", "2*k",
         V(("k", "1", "df", "درجه آزادی", "vapausasteet"))),
        ("studt", "Student t variance df>2", "واریانس t", "t-varianssi", "0", "k/(k - 2)",
         V(("k", "1", "df", "درجه آزادی", "vapausasteet"))),
        ("fdist", "F mean d2>2", "میانگین F", "F-ka", "d2/(d2 - 2)", "0",
         V(("d2", "1", "df2", "درجه ۲", "vapaus2"))),
        ("hyper", "Hypergeometric mean", "فوق‌هندسی میانگین", "Hypergeom. ka", "n*K/N", "n*(K/N)*(1 - K/N)*(N - n)/(N - 1)",
         V(("n", "1", "draws", "برداشت", "nostot"), ("K", "1", "success states", "موفق در ظرف", "onnistuvat"),
           ("N", "1", "population", "جامعه", "perusjoukko"))),
    ]
    # skip weib mean with incomplete gamma - use closed form only when simple
    skip_var_zero = {"weib", "studt", "fdist"}
    for key, en, fa, fi, mean_e, var_e, vs in dists:
        if key == "weib":
            continue  # incomplete
        mean_vars = dict(vs)
        # add mu as output
        mean_vars = {"mu": {"unit": "1", "name": {"en": "mean", "fa": "میانگین", "fi": "keskiarvo"}}, **vs}
        a(row(f"tx_{key}_mean", "math.prob", f"{en} mean", f"میانگین {fa}", f"{fi} odotusarvo",
              f"mu = {mean_e}", mean_vars))
        if key not in skip_var_zero and var_e != "0":
            var_vars = {"v": {"unit": "1", "name": {"en": "variance", "fa": "واریانس", "fi": "varianssi"}}, **vs}
            a(row(f"tx_{key}_var", "math.prob", f"{en} variance", f"واریانس {fa}", f"{fi} varianssi",
                  f"v = {var_e}", var_vars))

    # more probability
    morep = [
        ("tx_bayes", "Bayes theorem", "بیز", "Bayes",
         "post = like*prior/evid",
         V(("post", "1", "posterior", "پسین", "posteriori"), ("like", "1", "likelihood", "درستنمایی", "uskottavuus"),
           ("prior", "1", "prior", "پیشین", "priori"), ("evid", "1", "evidence", "شواهد", "evidenssi"))),
        ("tx_total_prob", "Total probability two", "احتمال کل دو راه", "Kokonaistodennakoisyys",
         "p = p1*h1 + p2*h2",
         V(("p", "1", "P(A)", "P(A)", "P(A)"), ("p1", "1", "P(A|H1)", "P(A|H1)", "P(A|H1)"),
           ("h1", "1", "P(H1)", "P(H1)", "P(H1)"), ("p2", "1", "P(A|H2)", "P(A|H2)", "P(A|H2)"),
           ("h2", "1", "P(H2)", "P(H2)", "P(H2)"))),
        ("tx_indep_and", "Independent AND", "و مستقل", "Riippumaton JA",
         "p = p1*p2",
         V(("p", "1", "P both", "هر دو", "molemmat"), ("p1", "1", "P1", "P1", "P1"), ("p2", "1", "P2", "P2", "P2"))),
        ("tx_indep_or", "Independent OR", "یا مستقل", "Riippumaton TAI",
         "p = p1 + p2 - p1*p2",
         V(("p", "1", "P either", "حداقل یکی", "jompikumpi"), ("p1", "1", "P1", "P1", "P1"), ("p2", "1", "P2", "P2", "P2"))),
        ("tx_complement", "Complement", "متمم", "Komplementti",
         "q = 1 - p",
         V(("q", "1", "P(not A)", "نقیض", "ei A"), ("p", "1", "P(A)", "P(A)", "P(A)"))),
        ("tx_cond", "Conditional probability", "احتمال شرطی", "Ehdollinen tn",
         "p = both/given",
         V(("p", "1", "P(A|B)", "P(A|B)", "P(A|B)"), ("both", "1", "P(A and B)", "اشتراک", "leikkaus"),
           ("given", "1", "P(B)", "P(B)", "P(B)"))),
        ("tx_binom_pmf", "Binomial P(X=k)", "احتمال دوجمله‌ای", "Binomitn",
         "p = binomial(n, k)*q**k*(1 - q)**(n - k)",
         V(("p", "1", "P", "P", "P"), ("n", "1", "n", "n", "n"), ("k", "1", "k", "k", "k"), ("q", "1", "success p", "p موفقیت", "p"))),
        ("tx_poiss_pmf", "Poisson P(X=k)", "احتمال پواسون", "Poisson tn",
         "p = exp(-lam)*lam**k/factorial(k)",
         V(("p", "1", "P", "P", "P"), ("lam", "1", "lambda", "لامبدا", "lambda"), ("k", "1", "k", "k", "k"))),
        ("tx_exp_cdf", "Exponential CDF", "CDF نمایی", "Eksponentin kertyma",
         "F = 1 - exp(-lam*t)",
         V(("F", "1", "F(t)", "F(t)", "F(t)"), ("lam", "1/s", "rate", "نرخ", "nopeus"), ("t", "s", "t", "t", "t"))),
        ("tx_exp_sf", "Exponential survival", "بقا نمایی", "Eksponentin elossaolo",
         "S = exp(-lam*t)",
         V(("S", "1", "S(t)", "S(t)", "S(t)"), ("lam", "1/s", "rate", "نرخ", "nopeus"), ("t", "s", "t", "t", "t"))),
        ("tx_norm_pdf_mean", "Normal pdf at the mean", "چگالی نرمال در میانگین", "Normaalin tiheys keskiarvossa",
         "p = 1/(sigma*sqrt(2*pi))",
         V(("p", "1", "pdf", "چگالی", "tiheys"), ("sigma", "1", "sigma", "سیگما", "sigma"))),
        ("tx_chebyshev", "Chebyshev bound", "چبیشف", "Tshebyshov",
         "p = 1 - 1/k**2",
         V(("p", "1", "min prob inside k sd", "حداقل احتمال", "min tn"), ("k", "1", "k", "k", "k"))),
        ("tx_markov_ineq", "Markov inequality bound", "مارکوف", "Markov",
         "p = mu/a",
         V(("p", "1", "P(X>=a) bound", "کران", "yla raja"), ("mu", "1", "E[X]", "امید", "odotusarvo"), ("a", "1", "a", "a", "a"))),
        ("tx_entropy2", "Binary entropy", "آنتروپی دودویی", "Binäärientropia",
         "H = -p*log(p)/log(2) - (1 - p)*log(1 - p)/log(2)",
         V(("H", "bit", "H", "H", "H"), ("p", "1", "p", "p", "p"))),
        ("tx_entropy_unif", "Uniform entropy n outcomes", "آنتروپی یکنواخت", "Tasan entropia",
         "H = log(n)/log(2)",
         V(("H", "bit", "H", "H", "H"), ("n", "1", "outcomes", "پیشامد", "tulokset"))),
        ("tx_mi_def", "Mutual information I=H-Hcond", "اطلاعات متقابل", "Keskinainen informaatio",
         "Ixy = Hx - Hxy",
         V(("Ixy", "bit", "I(X;Y)", "I(X;Y)", "I(X;Y)"), ("Hx", "bit", "H(X)", "H(X)", "H(X)"),
           ("Hxy", "bit", "H(X|Y)", "H(X|Y)", "H(X|Y)"))),
        ("tx_kl_bern", "KL two Bernoullis piece", "واگرایی KL برنولی", "KL Bernoulli",
         "d = p*log(p/q)/log(2) + (1 - p)*log((1 - p)/(1 - q))/log(2)",
         V(("d", "bit", "KL", "KL", "KL"), ("p", "1", "p", "p", "p"), ("q", "1", "q", "q", "q"))),
        ("tx_cov_def", "Covariance two pairs mean-centered", "کوواریانس", "Kovarianssi",
         "c = ((x1 - mx)*(y1 - my) + (x2 - mx)*(y2 - my))/2",
         V(("c", "1", "cov", "کوواریانس", "kovarianssi"), ("x1", "1", "x1", "x1", "x1"), ("x2", "1", "x2", "x2", "x2"),
           ("y1", "1", "y1", "y1", "y1"), ("y2", "1", "y2", "y2", "y2"), ("mx", "1", "mean x", "میانگین x", "x-ka"),
           ("my", "1", "mean y", "میانگین y", "y-ka"))),
    ]
    for it in morep:
        a(row(it[0], "math.prob", it[1], it[2], it[3], it[4], it[5]))
    return R


def engmath_and_opt():
    R = []
    a = R.append
    # Laplace table
    laps = [
        ("tx_lap_1", "L{1} = 1/s", "لاپلاس ۱", "L{1}",
         "F = 1/s", V(("F", "1", "F(s)", "F(s)", "F(s)"), ("s", "1/s", "s", "s", "s"))),
        ("tx_lap_exp", "L{e^{-at}}", "لاپلاس نمایی", "L{exp}",
         "F = 1/(s + a)", V(("F", "1", "F(s)", "F(s)", "F(s)"), ("s", "1/s", "s", "s", "s"), ("a", "1/s", "a", "a", "a"))),
        ("tx_lap_sin", "L{sin at}", "لاپلاس سینوس", "L{sin}",
         "F = a/(s**2 + a**2)", V(("F", "1", "F(s)", "F(s)", "F(s)"), ("a", "1/s", "a", "a", "a"), ("s", "1/s", "s", "s", "s"))),
        ("tx_lap_cos", "L{cos at}", "لاپلاس کسینوس", "L{cos}",
         "F = s/(s**2 + a**2)", V(("F", "1", "F(s)", "F(s)", "F(s)"), ("s", "1/s", "s", "s", "s"), ("a", "1/s", "a", "a", "a"))),
        ("tx_lap_t", "L{t}", "لاپلاس t", "L{t}",
         "F = 1/s**2", V(("F", "1", "F(s)", "F(s)", "F(s)"), ("s", "1/s", "s", "s", "s"))),
        ("tx_lap_tn", "L{t^n} n=2", "لاپلاس t^2", "L{t^2}",
         "F = 2/s**3", V(("F", "1", "F(s)", "F(s)", "F(s)"), ("s", "1/s", "s", "s", "s"))),
        ("tx_lap_sinh", "L{sinh at}", "لاپلاس سینوس هذلولوی", "L{sinh}",
         "F = a/(s**2 - a**2)", V(("F", "1", "F(s)", "F(s)", "F(s)"), ("a", "1/s", "a", "a", "a"), ("s", "1/s", "s", "s", "s"))),
        ("tx_lap_cosh", "L{cosh at}", "لاپلاس کسینوس هذلولوی", "L{cosh}",
         "F = s/(s**2 - a**2)", V(("F", "1", "F(s)", "F(s)", "F(s)"), ("s", "1/s", "s", "s", "s"), ("a", "1/s", "a", "a", "a"))),
        ("tx_lap_step", "L{u(t-c)}", "لاپلاس پله تأخیر", "L{porras}",
         "F = exp(-c*s)/s", V(("F", "1", "F(s)", "F(s)", "F(s)"), ("c", "s", "delay", "تأخیر", "viive"), ("s", "1/s", "s", "s", "s"))),
        ("tx_lap_ramp", "L{t e^{-at}}", "لاپلاس t نمایی", "L{t exp}",
         "F = 1/(s + a)**2", V(("F", "1", "F(s)", "F(s)", "F(s)"), ("s", "1/s", "s", "s", "s"), ("a", "1/s", "a", "a", "a"))),
        ("tx_final_value", "Final value theorem", "قضیه مقدار نهایی", "Loppuarvolause",
         "yinf = s*Y", V(("yinf", "1", "y(inf)", "y بی‌نهایت", "y(inf)"), ("s", "1/s", "s at 0 limit product", "sY", "sY"),
                         ("Y", "1", "Y(s) already *s omitted use product", "Y", "Y"))),
        ("tx_init_value", "Initial value theorem piece", "قضیه مقدار اولیه", "Alkuarvolause",
         "y0 = s*Y", V(("y0", "1", "y(0+)", "y(0)", "y(0)"), ("s", "1/s", "s", "s", "s"), ("Y", "1", "Y(s)", "Y(s)", "Y(s)"))),
    ]
    for it in laps:
        a(row(it[0], "engmath.laplace", it[1], it[2], it[3], it[4], it[5]))

    # Fourier harmonics
    for n in range(1, 21):
        a(row(f"tx_fourier_sq_{n}", "engmath.fourier",
              f"Square-wave sine coeff n={n}", f"ضریب فوریه موج مربعی n={n}", f"Kanttiaallon kerroin n={n}",
              f"b = 4*A/({n}*pi)" if n % 2 == 1 else "b = 0*A",
              V(("b", "1", "b_n", "b_n", "b_n"), ("A", "1", "amplitude", "دامنه", "amplitudi"))))
        a(row(f"tx_fourier_saw_{n}", "engmath.fourier",
              f"Sawtooth sine coeff n={n}", f"ضریب دندانه‌اره‌ای n={n}", f"Sahahampaan kerroin n={n}",
              f"b = 2*A*((-1)**({n}+1))/{n}",
              V(("b", "1", "b_n", "b_n", "b_n"), ("A", "1", "amplitude", "دامنه", "amplitudi"))))

    a(row("tx_parseval_2", "engmath.fourier", "Parseval two harmonics", "پارسوال دو هارمونیک", "Parseval",
          "P = A0**2/2 + (A1**2 + B1**2)/2",
          V(("P", "1", "mean square", "میانگین مربع", "teho"), ("A0", "1", "DC", "DC", "DC"),
            ("A1", "1", "a1", "a1", "a1"), ("B1", "1", "b1", "b1", "b1"))))
    a(row("tx_fourier_omega", "engmath.fourier", "Fundamental angular freq", "بسامد زاویه‌ای پایه", "Peruskulmataajuus",
          "w = 2*pi/T",
          V(("w", "rad/s", "omega0", "امگا", "omega"), ("T", "s", "period", "دوره", "jakso"))))
    a(row("tx_dft_bin", "engmath.fourier", "DFT bin frequency", "بسامد بین DFT", "DFT-taajuus",
          "f = k*fs/N",
          V(("f", "Hz", "frequency", "بسامد", "taajuus"), ("k", "1", "bin", "بین", "bin"),
            ("fs", "Hz", "sample rate", "نمونه‌برداری", "nayte"), ("N", "1", "N", "N", "N"))))

    # ODE
    odes = [
        ("tx_rc_ode_tau", "First-order time constant", "ثابت زمانی مرتبه ۱", "1. kertaluvun aikavakio",
         "tau = 1/a", V(("tau", "s", "tau", "تاو", "tau"), ("a", "1/s", "coeff of y", "ضریب y", "kerroin"))),
        ("tx_exp_decay_sol", "y'=-ky solution", "جواب y'=-ky", "Eksponenttiratkaisu",
         "y = y0*exp(-k*t)", V(("y", "1", "y", "y", "y"), ("y0", "1", "y0", "y0", "y0"),
                               ("k", "1/s", "k", "k", "k"), ("t", "s", "t", "t", "t"))),
        ("tx_logistic_ode", "Logistic closed form", "لجستیک بسته", "Logistinen ratkaisu",
         "y = K/(1 + (K/y0 - 1)*exp(-r*t))",
         V(("y", "1", "y", "y", "y"), ("K", "1", "carrying K", "ظرفیت", "kantokyky"),
           ("y0", "1", "y0", "y0", "y0"), ("r", "1/s", "r", "r", "r"), ("t", "s", "t", "t", "t"))),
        ("tx_sho_w", "SHO angular frequency", "بسامد نوسانگر", "Harmonisen taajuus",
         "w = sqrt(k/m)", V(("w", "rad/s", "omega", "امگا", "omega"), ("k", "N/m", "stiffness", "سختی", "jousivakio"),
                            ("m", "kg", "mass", "جرم", "massa"))),
        ("tx_damped_wn", "Damped natural frequency", "بسامد طبیعی میرا", "Vaimennettu ominaistaajuus",
         "wd = wn*sqrt(1 - z**2)", V(("wd", "rad/s", "wd", "wd", "wd"), ("wn", "rad/s", "wn", "wn", "wn"),
                                     ("z", "1", "damping ratio", "نسبت میرایی", "vaimennussuhde"))),
        ("tx_zeta_def", "Damping ratio from c", "نسبت میرایی از c", "Vaimennussuhde",
         "z = c/(2*sqrt(k*m))", V(("z", "1", "zeta", "زتا", "zeta"), ("c", "N*s/m", "damping", "میرایی", "vaimennus"),
                                  ("k", "N/m", "k", "k", "k"), ("m", "kg", "mass", "جرم", "massa"))),
        ("tx_sep_int", "Separable integral form", "جداشدنی", "Erotettava",
         "t = (y - y0)/k", V(("t", "s", "time", "زمان", "aika"), ("y", "1", "y", "y", "y"),
                             ("y0", "1", "y0", "y0", "y0"), ("k", "1/s", "constant speed", "سرعت ثابت", "vakionopeus"))),
        ("tx_euler_step", "Forward Euler step", "گام اویلر", "Euler-askel",
         "y1 = y0 + h*f0", V(("y1", "1", "y_{n+1}", "بعدی", "seuraava"), ("y0", "1", "y_n", "فعلی", "nykyinen"),
                             ("h", "1", "step", "گام", "askel"), ("f0", "1", "f_n", "f", "f"))),
        ("tx_heun_step", "Heun predictor-corrector", "هون", "Heun",
         "y1 = y0 + h*(f0 + fpred)/2", V(("y1", "1", "y new", "جدید", "uusi"), ("y0", "1", "y", "y", "y"),
                                         ("h", "1", "h", "h", "h"), ("f0", "1", "f_n", "f_n", "f_n"),
                                         ("fpred", "1", "f predicted", "f پیش‌بین", "ennuste"))),
        ("tx_char_quad", "2nd order char r", "ریشه مشخصه مرتبه ۲", "Karakteristinen juuri",
         "r = (-b + sqrt(b**2 - 4*a*c))/(2*a)",
         V(("r", "1", "root", "ریشه", "juuri"), ("a", "1", "a", "a", "a"), ("b", "1", "b", "b", "b"), ("c", "1", "c", "c", "c"))),
    ]
    for it in odes:
        a(row(it[0], "engmath.ode", it[1], it[2], it[3], it[4], it[5]))

    pdes = [
        ("tx_wave_c", "1D wave speed", "سرعت موج یک‌بعدی", "Aallon nopeus",
         "c = sqrt(Tens/mu)", V(("c", "m/s", "speed", "سرعت", "nopeus"), ("Tens", "N", "tension", "کشش", "jannitys"),
                                ("mu", "kg/m", "linear density", "چگالی خطی", "tiheys"))),
        ("tx_heat_diff", "Thermal diffusivity", "پخشندگی گرمایی", "Lampodiffuusio",
         "alpha = k/(rho*c)", V(("alpha", "m^2/s", "alpha", "آلفا", "alpha"), ("k", "W/(m*K)", "conductivity", "رسانایی", "johtavuus"),
                                ("rho", "kg/m^3", "density", "چگالی", "tiheys"), ("c", "J/(kg*K)", "specific heat", "گرمای ویژه", "lampokapasiteetti"))),
        ("tx_laplace_polar", "Laplace radial 2D power", "جواب شعاعی لاپلاس", "Laplacen sateratkaisu",
         "u = A + B*log(r)", V(("u", "1", "u", "u", "u"), ("A", "1", "A", "A", "A"), ("B", "1", "B", "B", "B"),
                               ("r", "m", "r", "r", "r"))),
    ]
    for it in pdes:
        a(row(it[0], "engmath.pde", it[1], it[2], it[3], it[4], it[5]))

    nums = [
        ("tx_rel_err", "Relative error", "خطای نسبی", "Suhteellinen virhe",
         "e = abs(x - xt)/abs(xt)", V(("e", "1", "relative error", "خطای نسبی", "suhteellinen virhe"),
                                      ("x", "1", "approx", "تقریب", "likiarvo"), ("xt", "1", "true", "واقعی", "tosi"))),
        ("tx_abs_err", "Absolute error", "خطای مطلق", "Absoluuttinen virhe",
         "e = abs(x - xt)", V(("e", "1", "abs error", "خطای مطلق", "itseisarvoinen virhe"),
                              ("x", "1", "approx", "تقریب", "likiarvo"), ("xt", "1", "true", "واقعی", "tosi"))),
        ("tx_bisection_iter", "Bisection iterations", "تعداد تکرار دو بخشی", "Puolitushaun kierrokset",
         "n = log((b - a)/eps)/log(2)", V(("n", "1", "iterations", "تکرار", "kierrokset"),
                                          ("b", "1", "b", "b", "b"), ("a", "1", "a", "a", "a"), ("eps", "1", "tolerance", "تلرانس", "tarkkuus"))),
        ("tx_newton_step", "Newton step", "گام نیوتن", "Newton-askel",
         "x1 = x0 - f0/fp", V(("x1", "1", "next", "بعدی", "seuraava"), ("x0", "1", "current", "فعلی", "nykyinen"),
                              ("f0", "1", "f", "f", "f"), ("fp", "1", "f'", "f'", "f'"))),
        ("tx_secant_step", "Secant step", "گام وتری", "Sekanttiaskel",
         "x2 = x1 - f1*(x1 - x0)/(f1 - f0)", V(("x2", "1", "next", "بعدی", "seuraava"), ("x1", "1", "x1", "x1", "x1"),
                                               ("x0", "1", "x0", "x0", "x0"), ("f1", "1", "f1", "f1", "f1"), ("f0", "1", "f0", "f0", "f0"))),
        ("tx_trap_err", "Trapezoid error one panel", "خطای ذوزنقه", "Trapetsivirhe",
         "e = -(b - a)**3*fpp/12", V(("e", "1", "error", "خطا", "virhe"), ("b", "1", "b", "b", "b"),
                                     ("a", "1", "a", "a", "a"), ("fpp", "1", "f''", "f''", "f''"))),
        ("tx_cond_fn", "Function condition number", "عدد حالت تابع", "Funktion kuntoluku",
         "k = abs(x*fp/f)", V(("k", "1", "condition", "عدد حالت", "kuntoluku"), ("x", "1", "x", "x", "x"),
                              ("fp", "1", "f'", "f'", "f'"), ("f", "1", "f", "f", "f"))),
        ("tx_fixed_point_lip", "Fixed-point Lipschitz need", "لیپ‌شیتس نقطه ثابت", "Kiintopisteen Lipschitz",
         "ok = abs(gp)", V(("ok", "1", "|g'|", "|g'|", "|g'|"), ("gp", "1", "g'", "g'", "g'"))),
    ]
    for it in nums:
        a(row(it[0], "engmath.numeric", it[1], it[2], it[3], it[4], it[5]))

    vec = [
        ("tx_grad_2norm", "2D gradient magnitude", "اندازه گرادیان ۲بعدی", "Gradientin itseisarvo",
         "g = sqrt(fx**2 + fy**2)", V(("g", "1", "|grad|", "|گرادیان|", "|grad|"), ("fx", "1", "df/dx", "df/dx", "df/dx"),
                                      ("fy", "1", "df/dy", "df/dy", "df/dy"))),
        ("tx_div2", "2D divergence", "واگرایی ۲بعدی", "2D divergenssi",
         "d = dPdx + dQdy", V(("d", "1", "div", "واگرایی", "div"), ("dPdx", "1", "dP/dx", "dP/dx", "dP/dx"),
                              ("dQdy", "1", "dQ/dy", "dQ/dy", "dQ/dy"))),
        ("tx_curl2", "2D curl k-component", "کرل ۲بعدی", "2D roottori",
         "c = dQdx - dPdy", V(("c", "1", "curl k", "کرل", "roottori"), ("dQdx", "1", "dQ/dx", "dQ/dx", "dQ/dx"),
                              ("dPdy", "1", "dP/dy", "dP/dy", "dP/dy"))),
        ("tx_dir_deriv", "Directional derivative", "مشتق سویی", "Suunnattu derivaatta",
         "d = fx*ux + fy*uy", V(("d", "1", "D_u f", "مشتق سویی", "suunnattu"), ("fx", "1", "fx", "fx", "fx"),
                                ("fy", "1", "fy", "fy", "fy"), ("ux", "1", "ux", "ux", "ux"), ("uy", "1", "uy", "uy", "uy"))),
        ("tx_green_rect", "Green rectangle flux piece", "گرین مستطیل", "Green suorakulmio",
         "I = Pdx + Qdy", V(("I", "1", "circulation piece", "گردش", "kierto"), ("P", "1", "P", "P", "P"),
                            ("dx", "1", "dx", "dx", "dx"), ("Q", "1", "Q", "Q", "Q"), ("dy", "1", "dy", "dy", "dy"))),
        ("tx_line_work", "Line work F·dr", "کار خطی", "Viivatyo",
         "W = Fx*dx + Fy*dy", V(("W", "J", "work", "کار", "tyo"), ("Fx", "N", "Fx", "Fx", "Fx"),
                                ("dx", "m", "dx", "dx", "dx"), ("Fy", "N", "Fy", "Fy", "Fy"), ("dy", "m", "dy", "dy", "dy"))),
    ]
    for it in vec:
        a(row(it[0], "engmath.vector", it[1], it[2], it[3], it[4], it[5]))

    opts = [
        ("tx_amgm", "AM-GM equality two", "برابری میانگین حسابی هندسی", "AM-GM",
         "am = gm", V(("am", "1", "arithmetic mean", "میانگین حسابی", "aritm. ka"),
                      ("gm", "1", "geometric mean", "میانگین هندسی", "geom. ka"))),
        ("tx_goldensection", "Golden-section interior", "نقطه داخلی نسبت طلایی", "Kultainen leikkaus",
         "x = a + (b - a)*phi", V(("x", "1", "interior", "داخلی", "sisapiste"), ("a", "1", "a", "a", "a"),
                                  ("b", "1", "b", "b", "b"), ("phi", "1", "0.382 or 0.618", "نسبت", "suhde"))),
        ("tx_lagrange_2", "Lagrange one constraint stationarity x", "لاگرانژ x", "Lagrange x",
         "fx = lam*gx", V(("fx", "1", "df/dx", "df/dx", "df/dx"), ("lam", "1", "multiplier", "ضریب", "kerroin"),
                          ("gx", "1", "dg/dx", "dg/dx", "dg/dx"))),
        ("tx_kkt_comp", "Complementary slackness", " slack مکمل", "Komplementaarinen hoyly",
         "mu = 0", V(("mu", "1", "inequality multiplier at interior", "ضریب نامساوی", "kerroin"),)),
        ("tx_quad_prog_1d", "1D quadratic vertex min", "رأس سهمی کمینه", "Paraabelin minimi",
         "x = -b/(2*a)", V(("x", "1", "argmin", "کمینه‌ساز", "minimi"), ("b", "1", "b", "b", "b"), ("a", "1", "a>0", "a", "a"))),
        ("tx_lp_value", "LP objective 2-var", "تابع هدف LP", "LP-kohde",
         "z = c1*x + c2*y", V(("z", "1", "objective", "هدف", "kohde"), ("c1", "1", "c1", "c1", "c1"),
                              ("x", "1", "x", "x", "x"), ("c2", "1", "c2", "c2", "c2"), ("y", "1", "y", "y", "y"))),
        ("tx_grad_desc", "Gradient descent step", "گام گرادیان کاهشی", "Gradienttimenetelma",
         "x1 = x0 - eta*g", V(("x1", "1", "next", "بعدی", "seuraava"), ("x0", "1", "x", "x", "x"),
                              ("eta", "1", "step size", "اندازه گام", "askel"), ("g", "1", "gradient", "گرادیان", "gradientti"))),
        ("tx_newton_opt", "Newton optimization 1D", "نیوتن بهینه‌سازی", "Newton-optimointi",
         "x1 = x0 - g/H", V(("x1", "1", "next", "بعدی", "seuraava"), ("x0", "1", "x", "x", "x"),
                            ("g", "1", "f'", "f'", "f'"), ("H", "1", "f''", "f''", "f''"))),
        ("tx_elastic_net", "Elastic-net penalty two terms", "جریمه الستیک‌نت", "Elastic net",
         "p = a*L1 + b*L2", V(("p", "1", "penalty", "جریمه", "sakko"), ("a", "1", "L1 weight", "وزن L1", "L1"),
                              ("L1", "1", "||w||1", "L1", "L1"), ("b", "1", "L2 weight", "وزن L2", "L2"),
                              ("L2", "1", "||w||2^2", "L2", "L2"))),
    ]
    for it in opts:
        a(row(it[0], "math.opt", it[1], it[2], it[3], it[4], it[5]))

    cplx = [
        ("tx_euler_id", "Euler formula real part", "جزء حقیقی اویلر", "Eulerin reaaliosa",
         "x = r*cos(t)", V(("x", "1", "real", "حقیقی", "reaali"), ("r", "1", "modulus", "قدر مطلق", "moduuli"),
                           ("t", "rad", "arg", "آرگومان", "arg"))),
        ("tx_mod_prod", "Modulus of product", "قدر مطلق حاصل‌ضرب", "Tulon moduli",
         "r = r1*r2", V(("r", "1", "|zw|", "|zw|", "|zw|"), ("r1", "1", "|z|", "|z|", "|z|"), ("r2", "1", "|w|", "|w|", "|w|"))),
        ("tx_arg_sum", "Argument of product", "آرگومان حاصل‌ضرب", "Tulon argumentti",
         "t = t1 + t2", V(("t", "rad", "arg(zw)", "arg", "arg"), ("t1", "rad", "arg z", "arg z", "arg z"),
                          ("t2", "rad", "arg w", "arg w", "arg w"))),
        ("tx_de_moivre_r", "De Moivre modulus", "دموآور قدر مطلق", "De Moivre moduli",
         "rn = r**n", V(("rn", "1", "|z^n|", "|z^n|", "|z^n|"), ("r", "1", "|z|", "|z|", "|z|"), ("n", "1", "n", "n", "n"))),
        ("tx_cauchy_riemann_u", "Cauchy-Riemann ux=vy", "کوشی-ریمان", "Cauchy-Riemann",
         "ux = vy", V(("ux", "1", "u_x", "u_x", "u_x"), ("vy", "1", "v_y", "v_y", "v_y"))),
        ("tx_complex_mult_x", "Complex product real", "جزء حقیقی ضرب مختلط", "Kompleksitulon reaaliosa",
         "x = a*c - b*d", V(("x", "1", "Re(zw)", "حقیقی", "reaali"), ("a", "1", "Re z", "Re z", "Re z"),
                            ("b", "1", "Im z", "Im z", "Im z"), ("c", "1", "Re w", "Re w", "Re w"), ("d", "1", "Im w", "Im w", "Im w"))),
        ("tx_residue_simple", "Simple pole residue", "مانده قطب ساده", "Yksinkertaisen navan jaannos",
         "Res = p/qprime", V(("Res", "1", "residue", "مانده", "jaannos"), ("p", "1", "numerator at pole", "صورت", "osoittaja"),
                             ("qprime", "1", "denom derivative", "مشتق مخرج", "nimittajan derivaatta"))),
    ]
    for it in cplx:
        a(row(it[0], "math.complex", it[1], it[2], it[3], it[4], it[5]))

    return R


def info_queue_rel():
    R = []
    a = R.append
    info = [
        ("tx_shannon_cap", "Shannon AWGN capacity", "ظرفیت شانون", "Shannonin kapasiteetti",
         "C = B*log(1 + S/N)/log(2)",
         V(("C", "bit/s", "capacity", "ظرفیت", "kapasiteetti"), ("B", "Hz", "bandwidth", "پهنای باند", "kaista"),
           ("S", "1", "signal", "سیگنال", "signaali"), ("N", "1", "noise", "نوفه", "kohina"))),
        ("tx_nyquist", "Nyquist rate", "نرخ نایکوئیست", "Nyquistin tahti",
         "R = 2*B*log(M)/log(2)",
         V(("R", "bit/s", "rate", "نرخ", "nopeus"), ("B", "Hz", "bandwidth", "پهنای باند", "kaista"),
           ("M", "1", "levels", "تراز", "tasot"))),
        ("tx_snr_db", "SNR in decibels", "SNR دسی‌بل", "SNR desibeleina",
         "snr = 10*log(S/N)/log(10)",
         V(("snr", "dB", "SNR", "SNR", "SNR"), ("S", "W", "signal", "سیگنال", "signaali"), ("N", "W", "noise", "نوفه", "kohina"))),
        ("tx_ebn0", "Eb/N0 from SNR", "Eb/N0", "Eb/N0",
         "eb = snr*B/R",
         V(("eb", "1", "Eb/N0", "Eb/N0", "Eb/N0"), ("snr", "1", "S/N", "S/N", "S/N"),
           ("B", "Hz", "bandwidth", "پهنای باند", "kaista"), ("R", "bit/s", "bit rate", "نرخ بیت", "bittinopeus"))),
        ("tx_huffman_avg", "Average code length two symbols", "طول میانگین کد", "Keskimaarainen koodipituus",
         "L = p1*l1 + p2*l2",
         V(("L", "bit", "L", "L", "L"), ("p1", "1", "p1", "p1", "p1"), ("l1", "bit", "l1", "l1", "l1"),
           ("p2", "1", "p2", "p2", "p2"), ("l2", "bit", "l2", "l2", "l2"))),
        ("tx_redundancy", "Code redundancy", "افزونگی کد", "Redundanssi",
         "r = L - H",
         V(("r", "bit", "redundancy", "افزونگی", "redundanssi"), ("L", "bit", "avg length", "طول میانگین", "pituus"),
           ("H", "bit", "entropy", "آنتروپی", "entropia"))),
        ("tx_hamming_bound_simp", "Hamming distance min detect", "فاصله همینگ کشف", "Hamming-etaisyys",
         "d = t + 1",
         V(("d", "1", "min distance", "حداقل فاصله", "min etaisyys"), ("t", "1", "detectable errors", "خطای قابل کشف", "havaittavat"))),
        ("tx_hamming_corr", "Hamming distance correct", "فاصله همینگ تصحیح", "Korjaava Hamming",
         "d = 2*t + 1",
         V(("d", "1", "min distance", "حداقل فاصله", "min etaisyys"), ("t", "1", "correctable", "قابل تصحیح", "korjattavat"))),
        ("tx_crc_bits", "CRC leftover bits n", "بیت باقی CRC", "CRC-bitit",
         "r = n - k",
         V(("r", "1", "parity bits", "بیت توازن", "tarkistusbitit"), ("n", "1", "code length", "طول کد", "pituus"),
           ("k", "1", "data bits", "بیت داده", "databitit"))),
    ]
    for it in info:
        a(row(it[0], "cs.infotheory", it[1], it[2], it[3], it[4], it[5]))

    qitems = [
        ("tx_mm1_rho", "M/M/1 utilization", "بهره‌برداری M/M/1", "M/M/1 kuormitus",
         "rho = lam/mu",
         V(("rho", "1", "rho", "رو", "rho"), ("lam", "1/s", "arrival", "ورود", "saapuminen"),
           ("mu", "1/s", "service", "خدمت", "palvelu"))),
        ("tx_mm1_L", "M/M/1 mean in system", "میانگین در سیستم M/M/1", "M/M/1 jonossa+palvelussa",
         "L = rho/(1 - rho)",
         V(("L", "1", "L", "L", "L"), ("rho", "1", "rho", "رو", "rho"))),
        ("tx_mm1_Lq", "M/M/1 mean queue", "میانگین صف M/M/1", "M/M/1 jono",
         "Lq = rho**2/(1 - rho)",
         V(("Lq", "1", "Lq", "Lq", "Lq"), ("rho", "1", "rho", "رو", "rho"))),
        ("tx_mm1_W", "M/M/1 sojourn", "زمان ماندن M/M/1", "M/M/1 viipya",
         "W = 1/(mu - lam)",
         V(("W", "s", "W", "W", "W"), ("mu", "1/s", "mu", "مو", "mu"), ("lam", "1/s", "lambda", "لامبدا", "lambda"))),
        ("tx_mm1_Wq", "M/M/1 wait", "انتظار M/M/1", "M/M/1 odotus",
         "Wq = lam/(mu*(mu - lam))",
         V(("Wq", "s", "Wq", "Wq", "Wq"), ("lam", "1/s", "lambda", "لامبدا", "lambda"), ("mu", "1/s", "mu", "مو", "mu"))),
        ("tx_little", "Little's law", "قانون لیتل", "Littlen laki",
         "L = lam*W",
         V(("L", "1", "L", "L", "L"), ("lam", "1/s", "throughput", "نرخ", "virta"), ("W", "s", "sojourn", "ماندن", "viipya"))),
        ("tx_md1_Wq", "M/D/1 wait", "انتظار M/D/1", "M/D/1 odotus",
         "Wq = lam/(2*mu*(mu - lam))",
         V(("Wq", "s", "Wq", "Wq", "Wq"), ("lam", "1/s", "lambda", "لامبدا", "lambda"), ("mu", "1/s", "mu", "مو", "mu"))),
        ("tx_pollaczek", "PK formula residual", "پولاچک-خینچین باقی", "Pollaczek-Khintchine",
         "Wq = lam*x2/(2*(1 - rho))",
         V(("Wq", "s", "Wq", "Wq", "Wq"), ("lam", "1/s", "lambda", "لامبدا", "lambda"),
           ("x2", "s^2", "E[S^2]", "E[S^2]", "E[S^2]"), ("rho", "1", "rho", "رو", "rho"))),
        ("tx_mmc_rho", "M/M/c utilization", "بهره‌برداری M/M/c", "M/M/c kuormitus",
         "rho = lam/(c*mu)",
         V(("rho", "1", "rho", "رو", "rho"), ("lam", "1/s", "lambda", "لامبدا", "lambda"),
           ("c", "1", "servers", "خدمت‌دهنده", "palvelijat"), ("mu", "1/s", "mu", "مو", "mu"))),
        ("tx_finite_pop", "Finite population arrival", "ورود جمعیت محدود", "Aarellinen populaatio",
         "lam = (M - n)*alpha",
         V(("lam", "1/s", "arrival", "ورود", "saapuminen"), ("M", "1", "population", "جمعیت", "populaatio"),
           ("n", "1", "in system", "در سیستم", "jarjestelmassa"), ("alpha", "1/s", "per customer", "هر مشتری", "asiakas"))),
    ]
    for it in qitems:
        a(row(it[0], "eng.queue", it[1], it[2], it[3], it[4], it[5]))

    rel = [
        ("tx_rel_series", "Series reliability two", "پایایی سری دو تا", "Sarjaluotettavuus",
         "R = R1*R2",
         V(("R", "1", "system R", "پایایی سیستم", "jarjestelma"), ("R1", "1", "R1", "R1", "R1"), ("R2", "1", "R2", "R2", "R2"))),
        ("tx_rel_par", "Parallel reliability two", "پایایی موازی دو تا", "Rinnakkaisluotettavuus",
         "R = 1 - (1 - R1)*(1 - R2)",
         V(("R", "1", "system R", "پایایی سیستم", "jarjestelma"), ("R1", "1", "R1", "R1", "R1"), ("R2", "1", "R2", "R2", "R2"))),
        ("tx_rel_exp", "Exponential reliability", "پایایی نمایی", "Eksponenttiluotettavuus",
         "R = exp(-lam*t)",
         V(("R", "1", "R(t)", "R(t)", "R(t)"), ("lam", "1/h", "failure rate", "نرخ خرابی", "vikaantuminen"),
           ("t", "h", "time", "زمان", "aika"))),
        ("tx_mtbf", "MTBF from rate", "MTBF", "MTBF",
         "m = 1/lam",
         V(("m", "h", "MTBF", "MTBF", "MTBF"), ("lam", "1/h", "lambda", "لامبدا", "lambda"))),
        ("tx_unavail", "Unavailability", "عدم دسترس‌پذیری", "Kayttamattomyys",
         "U = lam/(lam + mu)",
         V(("U", "1", "unavailability", "عدم دسترس", "kayttamattomyys"), ("lam", "1/h", "fail rate", "نرخ خرابی", "vika"),
           ("mu", "1/h", "repair rate", "نرخ تعمیر", "korjaus"))),
        ("tx_avail", "Availability", "دسترس‌پذیری", "Kaytettavyys",
         "A = mu/(lam + mu)",
         V(("A", "1", "availability", "دسترس", "kaytettavyys"), ("mu", "1/h", "repair", "تعمیر", "korjaus"),
           ("lam", "1/h", "fail", "خرابی", "vika"))),
        ("tx_weibull_R", "Weibull reliability", "پایایی وایبل", "Weibull-luotettavuus",
         "R = exp(-(t/eta)**bet)",
         V(("R", "1", "R(t)", "R(t)", "R(t)"), ("t", "h", "t", "t", "t"),
           ("eta", "h", "scale", "مقیاس", "skaala"), ("bet", "1", "shape", "شکل", "muoto"))),
        ("tx_kofn_3of3", "3-of-3 series already", "۳ از ۳", "3/3",
         "R = R1*R2*R3",
         V(("R", "1", "R", "R", "R"), ("R1", "1", "R1", "R1", "R1"), ("R2", "1", "R2", "R2", "R2"), ("R3", "1", "R3", "R3", "R3"))),
        ("tx_kofn_1of3", "1-of-3 parallel", "۱ از ۳ موازی", "1/3 rinnan",
         "R = 1 - (1 - R1)*(1 - R2)*(1 - R3)",
         V(("R", "1", "R", "R", "R"), ("R1", "1", "R1", "R1", "R1"), ("R2", "1", "R2", "R2", "R2"), ("R3", "1", "R3", "R3", "R3"))),
        ("tx_kofn_2of3_eq", "2-of-3 identical", "۲ از ۳ یکسان", "2/3 identtinen",
         "R = 3*r**2*(1 - r) + r**3",
         V(("R", "1", "system", "سیستم", "jarjestelma"), ("r", "1", "unit R", "پایایی واحد", "yksikko"))),
        ("tx_hazard_exp", "Constant hazard", "نرخ خطر ثابت", "Vakiohasardi",
         "h = lam",
         V(("h", "1/h", "h(t)", "h(t)", "h(t)"), ("lam", "1/h", "lambda", "لامبدا", "lambda"))),
        ("tx_bath_weib", "Weibull hazard", "خطر وایبل", "Weibull-hasardi",
         "h = (bet/eta)*(t/eta)**(bet - 1)",
         V(("h", "1/h", "h(t)", "h(t)", "h(t)"), ("bet", "1", "shape", "شکل", "muoto"),
           ("eta", "h", "scale", "مقیاس", "skaala"), ("t", "h", "t", "t", "t"))),
    ]
    for it in rel:
        a(row(it[0], "eng.reliability", it[1], it[2], it[3], it[4], it[5]))
    return R
