"""Physics, chemistry, engineering textbook rows."""

from __future__ import annotations

from add_textbook_formulas import V, row


def physics():
    R = []
    a = R.append
    kin = [
        ("tx_rel_vel_1d", "1D relative velocity", "سرعت نسبی یک‌بعدی", "Suhteellinen nopeus",
         "vr = va - vb", V(("vr", "m/s", "relative", "نسبی", "suhteellinen"), ("va", "m/s", "va", "va", "va"),
                           ("vb", "m/s", "vb", "vb", "vb"))),
        ("tx_avg_vel", "Average velocity endpoints", "سرعت متوسط دو سر", "Keskinopeus",
         "vavg = (u + v)/2", V(("vavg", "m/s", "average", "متوسط", "keski"), ("u", "m/s", "u", "u", "u"),
                               ("v", "m/s", "v", "v", "v"))),
        ("tx_const_a_t", "Time from u,v,a", "زمان از u,v,a", "Aika u,v,a",
         "t = (v - u)/a", V(("t", "s", "t", "t", "t"), ("v", "m/s", "v", "v", "v"),
                            ("u", "m/s", "u", "u", "u"), ("a", "m/s^2", "a", "a", "a"))),
        ("tx_horiz_range_cliff", "Cliff horizontal range", "برد افقی از لبه", "Jyrkanteen kantama",
         "R = v*sqrt(2*h/g)", V(("R", "m", "range", "برد", "kantama"), ("v", "m/s", "horizontal speed", "سرعت افقی", "vaakanopeus"),
                                ("h", "m", "height", "ارتفاع", "korkeus"), ("g", "m/s^2", "g", "g", "g"))),
        ("tx_circ_period", "Uniform circular period", "دوره حرکت دایره‌ای", "Ympyraliikkeen jakso",
         "T = 2*pi*r/v", V(("T", "s", "period", "دوره", "jakso"), ("r", "m", "radius", "شعاع", "sade"),
                           ("v", "m/s", "speed", "سرعت", "nopeus"))),
        ("tx_circ_freq", "Circular frequency from speed", "بسامد از سرعت دایره‌ای", "Taajuus ympyrasta",
         "f = v/(2*pi*r)", V(("f", "Hz", "f", "f", "f"), ("v", "m/s", "v", "v", "v"), ("r", "m", "r", "r", "r"))),
        ("tx_proj_x", "Projectile x", "پرتابه x", "Heittoliike x",
         "x = v*cos(th)*t", V(("x", "m", "x", "x", "x"), ("v", "m/s", "v", "v", "v"),
                              ("th", "rad", "angle", "زاویه", "kulma"), ("t", "s", "t", "t", "t"))),
        ("tx_proj_y", "Projectile y", "پرتابه y", "Heittoliike y",
         "y = v*sin(th)*t - g*t**2/2", V(("y", "m", "y", "y", "y"), ("v", "m/s", "v", "v", "v"),
                                         ("th", "rad", "angle", "زاویه", "kulma"), ("t", "s", "t", "t", "t"),
                                         ("g", "m/s^2", "g", "g", "g"))),
        ("tx_stop_dist", "Stopping distance", "مسافت توقف", "Pysahdysmatka",
         "s = v**2/(2*a)", V(("s", "m", "distance", "مسافت", "matka"), ("v", "m/s", "speed", "سرعت", "nopeus"),
                             ("a", "m/s^2", "deceleration", "شتاب منفی", "jarrutus"))),
        ("tx_avg_acc", "Average acceleration", "شتاب متوسط", "Keskikiihtyvyys",
         "a = (v - u)/t", V(("a", "m/s^2", "a", "a", "a"), ("v", "m/s", "v", "v", "v"),
                            ("u", "m/s", "u", "u", "u"), ("t", "s", "t", "t", "t"))),
    ]
    for it in kin:
        a(row(it[0], "physics.kinematics", it[1], it[2], it[3], it[4], it[5]))

    dyn = [
        ("tx_weight", "Weight", "وزن", "Paino",
         "W = m*g", V(("W", "N", "weight", "وزن", "paino"), ("m", "kg", "mass", "جرم", "massa"), ("g", "m/s^2", "g", "g", "g"))),
        ("tx_friction_kin", "Kinetic friction", "اصطکاک جنبشی", "Liukukitka",
         "f = mu*N", V(("f", "N", "friction", "اصطکاک", "kitka"), ("mu", "1", "mu_k", "مو", "mu"), ("N", "N", "normal", "عمودی", "normaali"))),
        ("tx_incline_a", "Frictionless incline accel", "شتاب سطح شیب‌دار بی‌اصطکاک", "Kaltevan tason kiihtyvyys",
         "a = g*sin(th)", V(("a", "m/s^2", "a", "a", "a"), ("g", "m/s^2", "g", "g", "g"), ("th", "rad", "angle", "زاویه", "kulma"))),
        ("tx_incline_fric", "Incline with friction down", "سطح شیب‌دار با اصطکاک", "Kalteva kitkalla",
         "a = g*(sin(th) - mu*cos(th))", V(("a", "m/s^2", "a", "a", "a"), ("g", "m/s^2", "g", "g", "g"),
                                           ("th", "rad", "angle", "زاویه", "kulma"), ("mu", "1", "mu", "مو", "mu"))),
        ("tx_atwood_a", "Atwood acceleration", "شتاب آتوود", "Atwoodin kiihtyvyys",
         "a = g*(m2 - m1)/(m1 + m2)", V(("a", "m/s^2", "a", "a", "a"), ("g", "m/s^2", "g", "g", "g"),
                                        ("m2", "kg", "heavy", "سنگین", "raskas"), ("m1", "kg", "light", "سبک", "kevy"))),
        ("tx_atwood_T", "Atwood tension", "کشش آتوود", "Atwoodin jannitys",
         "T = 2*m1*m2*g/(m1 + m2)", V(("T", "N", "tension", "کشش", "jannitys"), ("m1", "kg", "m1", "m1", "m1"),
                                      ("m2", "kg", "m2", "m2", "m2"), ("g", "m/s^2", "g", "g", "g"))),
        ("tx_centrip_F", "Centripetal force", "نیروی مرکزگرا", "Keskihakuvoima",
         "F = m*v**2/r", V(("F", "N", "F", "F", "F"), ("m", "kg", "mass", "جرم", "massa"),
                           ("v", "m/s", "speed", "سرعت", "nopeus"), ("r", "m", "radius", "شعاع", "sade"))),
        ("tx_drag_quad", "Quadratic drag", "پسا مربعی", "Neliodrag",
         "F = 0.5*Cd*rho*A*v**2", V(("F", "N", "drag", "پسا", "vastus"), ("Cd", "1", "Cd", "Cd", "Cd"),
                                    ("rho", "kg/m^3", "density", "چگالی", "tiheys"), ("A", "m^2", "area", "مساحت", "pinta"),
                                    ("v", "m/s", "speed", "سرعت", "nopeus"))),
        ("tx_impulse", "Impulse J=Ft", "ضربه", "Impulssi",
         "J = F*t", V(("J", "N*s", "impulse", "ضربه", "impulssi"), ("F", "N", "force", "نیرو", "voima"),
                      ("t", "s", "time", "زمان", "aika"))),
        ("tx_mom", "Linear momentum", "تکانه خطی", "Liikemaara",
         "p = m*v", V(("p", "kg*m/s", "p", "p", "p"), ("m", "kg", "mass", "جرم", "massa"), ("v", "m/s", "v", "v", "v"))),
        ("tx_com_two", "Two-mass COM 1D", "مرکز جرم دو جرم", "Kahden massan painopiste",
         "x = (m1*x1 + m2*x2)/(m1 + m2)", V(("x", "m", "COM", "مرکز جرم", "painopiste"),
                                            ("m1", "kg", "m1", "m1", "m1"), ("x1", "m", "x1", "x1", "x1"),
                                            ("m2", "kg", "m2", "m2", "m2"), ("x2", "m", "x2", "x2", "x2"))),
        ("tx_red_mass", "Reduced mass", "جرم کاهش‌یافته", "Redusoitu massa",
         "mu = m1*m2/(m1 + m2)", V(("mu", "kg", "mu", "مو", "mu"), ("m1", "kg", "m1", "m1", "m1"), ("m2", "kg", "m2", "m2", "m2"))),
        ("tx_bank_angle", "Banking angle no friction", "زاویه بَنک", "Kallistuskulma",
         "th = atan(v**2/(r*g))", V(("th", "rad", "angle", "زاویه", "kulma"), ("v", "m/s", "speed", "سرعت", "nopeus"),
                                    ("r", "m", "radius", "شعاع", "sade"), ("g", "m/s^2", "g", "g", "g"))),
        ("tx_inelastic_v", "Perfectly inelastic speed", "برخورد کاملاً ناکشسان", "Taysin kimmoton",
         "v = (m1*u1 + m2*u2)/(m1 + m2)", V(("v", "m/s", "common speed", "سرعت مشترک", "yhteisnopeus"),
                                            ("m1", "kg", "m1", "m1", "m1"), ("u1", "m/s", "u1", "u1", "u1"),
                                            ("m2", "kg", "m2", "m2", "m2"), ("u2", "m/s", "u2", "u2", "u2"))),
        ("tx_restitution", "Coefficient of restitution", "ضریب بازگشت", "Restituutiokerroin",
         "e = (v2 - v1)/(u1 - u2)", V(("e", "1", "e", "e", "e"), ("v2", "m/s", "v2", "v2", "v2"),
                                      ("v1", "m/s", "v1", "v1", "v1"), ("u1", "m/s", "u1", "u1", "u1"),
                                      ("u2", "m/s", "u2", "u2", "u2"))),
    ]
    for it in dyn:
        a(row(it[0], "physics.dynamics", it[1], it[2], it[3], it[4], it[5]))

    en = [
        ("tx_ke", "Translational KE", "انرژی جنبشی", "Liike-energia",
         "K = m*v**2/2", V(("K", "J", "KE", "جنبشی", "liike-energia"), ("m", "kg", "mass", "جرم", "massa"),
                           ("v", "m/s", "speed", "سرعت", "nopeus"))),
        ("tx_pe_g", "Gravitational PE near earth", "انرژی پتانسیل گرانشی", "Gravitaatiopotentiaali",
         "U = m*g*h", V(("U", "J", "PE", "پتانسیل", "potentiaali"), ("m", "kg", "mass", "جرم", "massa"),
                        ("g", "m/s^2", "g", "g", "g"), ("h", "m", "height", "ارتفاع", "korkeus"))),
        ("tx_spring_u", "Spring PE", "انرژی فنر", "Jousienergia",
         "U = k*x**2/2", V(("U", "J", "U", "U", "U"), ("k", "N/m", "k", "k", "k"), ("x", "m", "x", "x", "x"))),
        ("tx_power_fv", "Power F v", "توان نیرو سرعت", "Teho Fv",
         "P = F*v", V(("P", "W", "power", "توان", "teho"), ("F", "N", "force", "نیرو", "voima"),
                      ("v", "m/s", "speed", "سرعت", "nopeus"))),
        ("tx_work_fd", "Work F d cos", "کار", "Tyo",
         "W = F*d*cos(theta)", V(("W", "J", "work", "کار", "tyo"), ("F", "N", "F", "F", "F"),
                                 ("d", "m", "distance", "جابه‌جایی", "matka"), ("theta", "rad", "angle", "زاویه", "kulma"))),
        ("tx_eff", "Efficiency", "بازده", "Hyotysuhde",
         "e = 100*Wout/Win", V(("e", "1", "percent efficiency", "درصد بازده", "hyotysuhde %"),
                               ("Wout", "J", "useful", "مفید", "hyodyllinen"), ("Win", "J", "input", "ورودی", "otto"))),
        ("tx_springs_series", "Two springs series", "دو فنر سری", "Jouset sarjassa",
         "k = k1*k2/(k1 + k2)", V(("k", "N/m", "k eq", "معادل", "ekv"), ("k1", "N/m", "k1", "k1", "k1"),
                                  ("k2", "N/m", "k2", "k2", "k2"))),
        ("tx_springs_par", "Two springs parallel", "دو فنر موازی", "Jouset rinnan",
         "k = k1 + k2", V(("k", "N/m", "k eq", "معادل", "ekv"), ("k1", "N/m", "k1", "k1", "k1"),
                          ("k2", "N/m", "k2", "k2", "k2"))),
        ("tx_hooke", "Hooke F=kx", "هوک", "Hooke",
         "F = k*x", V(("F", "N", "F", "F", "F"), ("k", "N/m", "k", "k", "k"), ("x", "m", "x", "x", "x"))),
        ("tx_escape_from_ke", "Speed from KE", "سرعت از جنبشی", "Nopeus energiasta",
         "v = sqrt(2*K/m)", V(("v", "m/s", "v", "v", "v"), ("K", "J", "KE", "جنبشی", "K"), ("m", "kg", "mass", "جرم", "massa"))),
    ]
    for it in en:
        a(row(it[0], "physics.energy", it[1], it[2], it[3], it[4], it[5]))

    rot = [
        ("tx_torque", "Torque F r sin", "گشتاور", "Momentti",
         "T = F*r*sin(theta)", V(("T", "N*m", "torque", "گشتاور", "momentti"), ("F", "N", "F", "F", "F"),
                                 ("r", "m", "r", "r", "r"), ("theta", "rad", "angle", "زاویه", "kulma"))),
        ("tx_omega_rpm", "omega from rpm", "امگا از دور بر دقیقه", "omega rpm:sta",
         "w = rpm*2*pi/60", V(("w", "rad/s", "omega", "امگا", "omega"), ("rpm", "1/min", "rpm", "دور بر دقیقه", "rpm"))),
        ("tx_I_hoop", "Hoop I about center", "اینرسی حلقه", "Renkaan I",
         "Icm = m*r**2", V(("Icm", "kg*m^2", "I", "I", "I"), ("m", "kg", "mass", "جرم", "massa"), ("r", "m", "r", "r", "r"))),
        ("tx_I_disk", "Disk I about axis", "اینرسی دیسک", "Levyn I",
         "Icm = m*r**2/2", V(("Icm", "kg*m^2", "I", "I", "I"), ("m", "kg", "mass", "جرم", "massa"), ("r", "m", "r", "r", "r"))),
        ("tx_I_sphere", "Solid sphere I", "اینرسی کره توپر", "Pallon I",
         "Icm = 2*m*r**2/5", V(("Icm", "kg*m^2", "I", "I", "I"), ("m", "kg", "mass", "جرم", "massa"), ("r", "m", "r", "r", "r"))),
        ("tx_I_rod_cm", "Rod I about center", "اینرسی میله از مرکز", "Sauvan I keskelta",
         "Icm = m*L**2/12", V(("Icm", "kg*m^2", "I", "I", "I"), ("m", "kg", "mass", "جرم", "massa"), ("L", "m", "length", "طول", "pituus"))),
        ("tx_parallel_axis", "Parallel-axis theorem", "محور موازی", "Steiner",
         "Itot = Icm + m*d**2", V(("Itot", "kg*m^2", "I", "I", "I"), ("Icm", "kg*m^2", "Icm", "Icm", "Icm"),
                               ("m", "kg", "mass", "جرم", "massa"), ("d", "m", "distance", "فاصله", "etaisyys"))),
        ("tx_alpha_torque", "Angular accel from torque", "شتاب زاویه‌ای", "Kulmakiihtyvyys",
         "al = Tq/Icm", V(("al", "rad/s^2", "alpha", "آلفا", "alpha"), ("Tq", "N*m", "torque", "گشتاور", "momentti"),
                          ("Icm", "kg*m^2", "I", "I", "I"))),
        ("tx_rolling_K", "Rolling KE", "جنبشی غلتش", "Vierimisenergia",
         "K = m*v**2/2 + Icm*w**2/2", V(("K", "J", "K", "K", "K"), ("m", "kg", "mass", "جرم", "massa"),
                                        ("v", "m/s", "v_cm", "v", "v"), ("Icm", "kg*m^2", "I", "I", "I"),
                                        ("w", "rad/s", "omega", "امگا", "omega"))),
        ("tx_v_omega", "v = r omega", "v = rω", "v = r omega",
         "v = r*w", V(("v", "m/s", "v", "v", "v"), ("r", "m", "r", "r", "r"), ("w", "rad/s", "omega", "امگا", "omega"))),
        ("tx_ang_mom", "L = I omega", "تکانه زاویه‌ای", "Pyorimismaara",
         "L = Icm*w", V(("L", "kg*m^2/s", "L", "L", "L"), ("Icm", "kg*m^2", "I", "I", "I"),
                        ("w", "rad/s", "omega", "امگا", "omega"))),
        ("tx_lever", "Lever F1 d1 = F2 d2", "اهرُم", "Vipu",
         "F1*d1 = F2*d2", V(("F1", "N", "F1", "F1", "F1"), ("d1", "m", "d1", "d1", "d1"),
                            ("F2", "N", "F2", "F2", "F2"), ("d2", "m", "d2", "d2", "d2"))),
    ]
    for it in rot:
        a(row(it[0], "physics.rotation", it[1], it[2], it[3], it[4], it[5]))

    osc = [
        ("tx_pendulum", "Simple pendulum small", "آونگ ساده", "Yksinkertainen heiluri",
         "T = 2*pi*sqrt(L/g)", V(("T", "s", "period", "دوره", "jakso"), ("L", "m", "length", "طول", "pituus"),
                                 ("g", "m/s^2", "g", "g", "g"))),
        ("tx_mass_spring_T", "Mass-spring period", "دوره جرم-فنر", "Massa-jousi jakso",
         "T = 2*pi*sqrt(m/k)", V(("T", "s", "period", "دوره", "jakso"), ("m", "kg", "mass", "جرم", "massa"),
                                 ("k", "N/m", "k", "k", "k"))),
        ("tx_phys_pend", "Physical pendulum", "آونگ فیزیکی", "Fysikaalinen heiluri",
         "T = 2*pi*sqrt(Icm/(m*g*d))", V(("T", "s", "T", "T", "T"), ("Icm", "kg*m^2", "I about pivot use Steiner first", "I", "I"),
                                         ("m", "kg", "mass", "جرم", "massa"), ("g", "m/s^2", "g", "g", "g"),
                                         ("d", "m", "COM distance", "فاصله مرکز جرم", "etaisyys"))),
        ("tx_torsional", "Torsional oscillator", "نوسانگر پیچشی", "Vantioheiluri",
         "T = 2*pi*sqrt(Icm/kappa)", V(("T", "s", "T", "T", "T"), ("Icm", "kg*m^2", "I", "I", "I"),
                                       ("kappa", "N*m/rad", "torsion k", "ثابت پیچش", "vantio"))),
        ("tx_beats", "Beat period", "دوره ضربان", "Huojuntajakso",
         "Tb = 2*pi/abs(w1 - w2)", V(("Tb", "s", "beat period", "دوره ضربان", "huojunta"),
                                     ("w1", "rad/s", "w1", "w1", "w1"), ("w2", "rad/s", "w2", "w2", "w2"))),
        ("tx_sho_v", "SHO max speed", "حداکثر سرعت SHO", "SHO max nopeus",
         "vmax = A*w", V(("vmax", "m/s", "max v", "حداکثر v", "max v"), ("A", "m", "amplitude", "دامنه", "amplitudi"),
                         ("w", "rad/s", "omega", "امگا", "omega"))),
        ("tx_sho_E", "SHO total energy", "انرژی کل SHO", "SHO energia",
         "Etot = k*A**2/2", V(("Etot", "J", "energy", "انرژی", "energia"), ("k", "N/m", "k", "k", "k"),
                              ("A", "m", "amplitude", "دامنه", "amplitudi"))),
        ("tx_driven_amp", "Driven SHO amplitude undamped approx", "دامنه واداشته", "Pakotettu amplitudi",
         "A = F0/abs(k - m*w**2)", V(("A", "m", "A", "A", "A"), ("F0", "N", "F0", "F0", "F0"),
                                     ("k", "N/m", "k", "k", "k"), ("m", "kg", "m", "m", "m"),
                                     ("w", "rad/s", "drive omega", "امگای محرک", "omega"))),
    ]
    for it in osc:
        a(row(it[0], "physics.osc", it[1], it[2], it[3], it[4], it[5]))

    wav = [
        ("tx_wave_v", "v = f lambda", "v = fλ", "v = f lambda",
         "v = f*lam", V(("v", "m/s", "speed", "سرعت", "nopeus"), ("f", "Hz", "frequency", "بسامد", "taajuus"),
                        ("lam", "m", "wavelength", "طول موج", "aallonpituus"))),
        ("tx_string_harm", "String harmonic frequency", "هارمونیک سیم", "Kielen harmoninen",
         "f = n*v/(2*L)", V(("f", "Hz", "f_n", "f_n", "f_n"), ("n", "1", "n", "n", "n"),
                            ("v", "m/s", "wave speed", "سرعت موج", "nopeus"), ("L", "m", "length", "طول", "pituus"))),
        ("tx_string_v", "String wave speed", "سرعت موج سیم", "Kielen aaltonopeus",
         "v = sqrt(Tens/mu)", V(("v", "m/s", "v", "v", "v"), ("Tens", "N", "tension", "کشش", "jannitys"),
                                ("mu", "kg/m", "mu", "مو", "mu"))),
        ("tx_intensity", "Spherical intensity", "شدت کروی", "Pallosateily",
         "Int = P/(4*pi*r**2)", V(("Int", "W/m^2", "intensity", "شدت", "intensiteetti"), ("P", "W", "power", "توان", "teho"),
                                  ("r", "m", "r", "r", "r"))),
        ("tx_spl", "Sound level", "تراز صدا", "Aanitaso",
         "L = 10*log(Int/I0)/log(10)", V(("L", "dB", "level", "تراز", "taso"), ("Int", "W/m^2", "I", "I", "I"),
                                         ("I0", "W/m^2", "I0", "I0", "I0"))),
        ("tx_doppler_src", "Doppler source toward", "دوپلر چشمه نزدیک", "Doppler lahde",
         "f = f0*v/(v - vs)", V(("f", "Hz", "heard", "شنیده", "kuultu"), ("f0", "Hz", "source", "چشمه", "lahde"),
                                ("v", "m/s", "sound speed", "سرعت صوت", "aanen n."),
                                ("vs", "m/s", "source speed", "سرعت چشمه", "lahteen n."))),
        ("tx_doppler_obs", "Doppler observer toward", "دوپلر ناظر نزدیک", "Doppler havaitsija",
         "f = f0*(v + vo)/v", V(("f", "Hz", "heard", "شنیده", "kuultu"), ("f0", "Hz", "f0", "f0", "f0"),
                                ("v", "m/s", "sound", "صوت", "aani"), ("vo", "m/s", "observer", "ناظر", "havaitsija"))),
        ("tx_pipe_open", "Open pipe n=1", "لوله باز پایه", "Avoin putki",
         "f = v/(2*L)", V(("f", "Hz", "f", "f", "f"), ("v", "m/s", "v", "v", "v"), ("L", "m", "L", "L", "L"))),
        ("tx_pipe_closed", "Closed pipe n=1", "لوله بسته پایه", "Suljettu putki",
         "f = v/(4*L)", V(("f", "Hz", "f", "f", "f"), ("v", "m/s", "v", "v", "v"), ("L", "m", "L", "L", "L"))),
        ("tx_impedance_str", "String impedance", "امپدانس سیم", "Kielen impedanssi",
         "Z = mu*v", V(("Z", "kg/s", "Z", "Z", "Z"), ("mu", "kg/m", "mu", "مو", "mu"), ("v", "m/s", "v", "v", "v"))),
        ("tx_refl_coeff", "Amplitude reflection", "بازتاب دامنه", "Heijastuskerroin",
         "R = (Z2 - Z1)/(Z2 + Z1)", V(("R", "1", "R", "R", "R"), ("Z2", "kg/s", "Z2", "Z2", "Z2"),
                                      ("Z1", "kg/s", "Z1", "Z1", "Z1"))),
        ("tx_group_phase", "Phase velocity", "سرعت فاز", "Vaihenopeus",
         "vp = w/k", V(("vp", "m/s", "vp", "vp", "vp"), ("w", "rad/s", "omega", "امگا", "omega"),
                       ("k", "1/m", "k", "k", "k"))),
    ]
    for it in wav:
        a(row(it[0], "physics.waves", it[1], it[2], it[3], it[4], it[5]))

    # relativity dedicated
    rels = [
        ("tx_gamma_rel", "Lorentz gamma", "گامای لورنتس", "Lorentzin gamma",
         "gfac = 1/sqrt(1 - v**2/c**2)", V(("gfac", "1", "gamma", "گاما", "gamma"), ("v", "m/s", "v", "v", "v"),
                                           ("c", "m/s", "c", "c", "c"))),
        ("tx_time_dil", "Time dilation", "اتساع زمان", "Ajan venyminen",
         "t = t0*gfac", V(("t", "s", "lab time", "زمان آزمایشگاه", "lab-aika"), ("t0", "s", "proper", "ذاتی", "ominaisaika"),
                          ("gfac", "1", "gamma", "گاما", "gamma"))),
        ("tx_length_contr", "Length contraction", "انقباض طول", "Pituuden supistuminen",
         "L = L0/gfac", V(("L", "m", "contracted", "منقبض", "supistunut"), ("L0", "m", "proper length", "طول ذاتی", "ominaispituus"),
                          ("gfac", "1", "gamma", "گاما", "gamma"))),
        ("tx_rel_p", "Relativistic momentum", "تکانه نسبیتی", "Relativistinen liikemaara",
         "p = gfac*m*v", V(("p", "kg*m/s", "p", "p", "p"), ("gfac", "1", "gamma", "گاما", "gamma"),
                           ("m", "kg", "rest mass", "جرم سکون", "lepomassa"), ("v", "m/s", "v", "v", "v"))),
        ("tx_rel_K", "Relativistic KE", "جنبشی نسبیتی", "Relativistinen K",
         "K = (gfac - 1)*m*c**2", V(("K", "J", "K", "K", "K"), ("gfac", "1", "gamma", "گاما", "gamma"),
                                    ("m", "kg", "m", "m", "m"), ("c", "m/s", "c", "c", "c"))),
        ("tx_rel_E", "Total relativistic energy", "انرژی کل نسبیتی", "Kokonaisenergia",
         "Etot = gfac*m*c**2", V(("Etot", "J", "E", "E", "E"), ("gfac", "1", "gamma", "گاما", "gamma"),
                                 ("m", "kg", "m", "m", "m"), ("c", "m/s", "c", "c", "c"))),
        ("tx_rel_E2", "Energy-momentum", "انرژی-تکانه", "Energia-liikemaara",
         "Etot = sqrt((p*c)**2 + (m*c**2)**2)", V(("Etot", "J", "E", "E", "E"), ("p", "kg*m/s", "p", "p", "p"),
                                                  ("c", "m/s", "c", "c", "c"), ("m", "kg", "m", "m", "m"))),
        ("tx_vel_add", "Velocity addition collinear", "جمع سرعت همخط", "Nopeuksien summa",
         "u = (v + w)/(1 + v*w/c**2)", V(("u", "m/s", "u", "u", "u"), ("v", "m/s", "v frame", "v چارچوب", "v"),
                                         ("w", "m/s", "w in frame", "w", "w"), ("c", "m/s", "c", "c", "c"))),
        ("tx_rel_doppler", "Relativistic Doppler receding", "دوپلر نسبیتی دور", "Rel. Doppler",
         "f = f0*sqrt((1 - bet)/(1 + bet))", V(("f", "Hz", "observed", "مشاهده", "havaittu"),
                                               ("f0", "Hz", "rest", "سکون", "lepo"), ("bet", "1", "v/c", "v/c", "v/c"))),
        ("tx_beta_v", "beta = v/c", "بتا = v/c", "beta = v/c",
         "bet = v/c", V(("bet", "1", "beta", "بتا", "beta"), ("v", "m/s", "v", "v", "v"), ("c", "m/s", "c", "c", "c"))),
        ("tx_minkowski_s", "Minkowski interval 1+1", "بازه مینکوفسکی", "Minkowskin vali",
         "s2 = c**2*t**2 - x**2", V(("s2", "m^2", "s^2", "s^2", "s^2"), ("c", "m/s", "c", "c", "c"),
                                    ("t", "s", "t", "t", "t"), ("x", "m", "x", "x", "x"))),
        ("tx_grav_red", "Gravitational redshift weak", "انتقال به سرخ گرانشی", "Gravitaatiopunasiirtyma",
         "z = g*h/c**2", V(("z", "1", "z", "z", "z"), ("g", "m/s^2", "g", "g", "g"),
                           ("h", "m", "height", "ارتفاع", "korkeus"), ("c", "m/s", "c", "c", "c"))),
    ]
    for it in rels:
        a(row(it[0], "physics.relativity", it[1], it[2], it[3], it[4], it[5]))

    sm = [
        ("tx_mb_rms", "Maxwell rms speed", "سرعت rms ماکسول", "Maxwell rms",
         "v = sqrt(3*Rgas*T/M)", V(("v", "m/s", "v_rms", "v_rms", "v_rms"), ("Rgas", "J/(mol*K)", "R", "R", "R"),
                                   ("T", "K", "T", "T", "T"), ("M", "kg/mol", "molar mass", "جرم مولی", "moolimassa"))),
        ("tx_mb_mean", "Maxwell mean speed", "سرعت میانگین ماکسول", "Maxwell keski",
         "v = sqrt(8*Rgas*T/(pi*M))", V(("v", "m/s", "v_avg", "میانگین", "ka"), ("Rgas", "J/(mol*K)", "R", "R", "R"),
                                        ("T", "K", "T", "T", "T"), ("M", "kg/mol", "M", "M", "M"))),
        ("tx_mb_mp", "Maxwell most probable", "محتمل‌ترین سرعت", "Todennakoisin nopeus",
         "v = sqrt(2*Rgas*T/M)", V(("v", "m/s", "v_p", "v_p", "v_p"), ("Rgas", "J/(mol*K)", "R", "R", "R"),
                                   ("T", "K", "T", "T", "T"), ("M", "kg/mol", "M", "M", "M"))),
        ("tx_equipart", "Equipartition energy", "هم‌توزیع انرژی", "Energian tasajako",
         "U = f*n*Rgas*T/2", V(("U", "J", "U", "U", "U"), ("f", "1", "degrees of freedom", "درجه آزادی", "vapaus"),
                               ("n", "mol", "n", "n", "n"), ("Rgas", "J/(mol*K)", "R", "R", "R"), ("T", "K", "T", "T", "T"))),
        ("tx_boltz_fac", "Boltzmann factor", "عامل بولتزمن", "Boltzmannin kerroin",
         "p = exp(-En/(kB*T))", V(("p", "1", "factor", "عامل", "kerroin"), ("En", "J", "energy", "انرژی", "energia"),
                                  ("kB", "J/K", "k", "k", "k"), ("T", "K", "T", "T", "T"))),
        ("tx_sackur_lead", "Ideal gas entropy piece nR ln V", "آنتروپی گاز آرمانی قطعه", "Ideaali entropia",
         "S = n*Rgas*log(V)", V(("S", "J/K", "S piece", "قطعه S", "S"), ("n", "mol", "n", "n", "n"),
                                ("Rgas", "J/(mol*K)", "R", "R", "R"), ("V", "m^3", "V", "V", "V"))),
        ("tx_partition_two", "Two-level partition", "تابع پارش دو تراز", "Kaksitilainen Z",
         "Z = 1 + exp(-En/(kB*T))", V(("Z", "1", "Z", "Z", "Z"), ("En", "J", "gap", "گاف", "ero"),
                                      ("kB", "J/K", "k", "k", "k"), ("T", "K", "T", "T", "T"))),
        ("tx_free_energy", "Helmholtz from Z", "هلمهولتز از Z", "Helmholtz Z:sta",
         "F = -kB*T*log(Z)", V(("F", "J", "F", "F", "F"), ("kB", "J/K", "k", "k", "k"),
                               ("T", "K", "T", "T", "T"), ("Z", "1", "Z", "Z", "Z"))),
        ("tx_pressure_Z", "Ideal pressure from Z_trans V", "فشار از Z", "Paine Z:sta",
         "P = n*Rgas*T/V", V(("P", "Pa", "P", "P", "P"), ("n", "mol", "n", "n", "n"),
                             ("Rgas", "J/(mol*K)", "R", "R", "R"), ("T", "K", "T", "T", "T"), ("V", "m^3", "V", "V", "V"))),
    ]
    for it in sm:
        a(row(it[0], "physics.statmech", it[1], it[2], it[3], it[4], it[5]))

    return R


def chemistry():
    R = []
    a = R.append
    items = [
        ("tx_ideal_gas", "chem.gas", "Ideal gas law", "گاز آرمانی", "Ideaali kaasu",
         "P*V = n*Rgas*T",
         V(("P", "Pa", "P", "P", "P"), ("V", "m^3", "V", "V", "V"), ("n", "mol", "n", "n", "n"),
           ("Rgas", "J/(mol*K)", "R", "R", "R"), ("T", "K", "T", "T", "T"))),
        ("tx_vdw_p", "chem.gas", "van der Waals pressure", "فشار واندروالس", "van der Waals paine",
         "P = n*Rgas*T/(V - n*b) - a*n**2/V**2",
         V(("P", "Pa", "P", "P", "P"), ("n", "mol", "n", "n", "n"), ("Rgas", "J/(mol*K)", "R", "R", "R"),
           ("T", "K", "T", "T", "T"), ("V", "m^3", "V", "V", "V"), ("b", "m^3/mol", "b", "b", "b"),
           ("a", "Pa*m^6/mol^2", "a", "a", "a"))),
        ("tx_dalton_x", "chem.gas", "Partial pressure mole fraction", "فشار جزئی", "Osapaine",
         "pA = xA*P",
         V(("pA", "Pa", "pA", "pA", "pA"), ("xA", "1", "mole fraction", "کسر مولی", "mooliosuus"), ("P", "Pa", "P", "P", "P"))),
        ("tx_graham", "chem.gas", "Graham effusion ratio", "گراهام", "Graham",
         "rto = sqrt(M2/M1)",
         V(("rto", "1", "rate1/rate2", "نسبت آهنگ", "suhde"), ("M2", "g/mol", "M2", "M2", "M2"), ("M1", "g/mol", "M1", "M1", "M1"))),
        ("tx_rms_gas", "chem.gas", "rms molecular speed", "سرعت rms مولکولی", "rms-nopeus",
         "v = sqrt(3*Rgas*T/M)",
         V(("v", "m/s", "v_rms", "v_rms", "v_rms"), ("Rgas", "J/(mol*K)", "R", "R", "R"),
           ("T", "K", "T", "T", "T"), ("M", "kg/mol", "M", "M", "M"))),
        ("tx_molarity", "chem.solution", "Molarity", "مولاریته", "Molaarisuus",
         "Mconc = n/V",
         V(("Mconc", "mol/L", "M", "M", "M"), ("n", "mol", "moles", "مول", "moolit"), ("V", "L", "volume", "حجم", "tilavuus"))),
        ("tx_molality", "chem.solution", "Molality", "مولالیته", "Molaalisuus",
         "b = n/m",
         V(("b", "mol/kg", "molality", "مولالیته", "molaalisuus"), ("n", "mol", "solute", "حل‌شونده", "liuenneen"),
           ("m", "kg", "solvent kg", "حلال", "liuotin"))),
        ("tx_mole_frac", "chem.solution", "Mole fraction two", "کسر مولی دو جزء", "Mooliosuus",
         "xA = nA/(nA + nB)",
         V(("xA", "1", "xA", "xA", "xA"), ("nA", "mol", "nA", "nA", "nA"), ("nB", "mol", "nB", "nB", "nB"))),
        ("tx_dilute", "chem.solution", "Dilution", "رقیق‌سازی", "Laimennus",
         "M1*V1 = M2*V2",
         V(("M1", "mol/L", "M1", "M1", "M1"), ("V1", "L", "V1", "V1", "V1"),
           ("M2", "mol/L", "M2", "M2", "M2"), ("V2", "L", "V2", "V2", "V2"))),
        ("tx_raoult", "chem.solution", "Raoult's law", "رولت", "Raoult",
         "pA = xA*pAstar",
         V(("pA", "Pa", "pA", "pA", "pA"), ("xA", "1", "xA", "xA", "xA"), ("pAstar", "Pa", "pure vapor p", "فشار خالص", "puhdas"))),
        ("tx_henry", "chem.solution", "Henry's law", "هنری", "Henry",
         "pA = K*xA",
         V(("pA", "Pa", "pA", "pA", "pA"), ("K", "Pa", "Henry K", "K هنری", "Henry"), ("xA", "1", "xA", "xA", "xA"))),
        ("tx_fp_dep", "chem.collig", "Freezing-point depression", "کاهش نقطه انجماد", "Jaatymispisteen alenema",
         "dT = Kf*b*i",
         V(("dT", "K", "delta T", "دلتا تی", "dT"), ("Kf", "K*kg/mol", "Kf", "Kf", "Kf"),
           ("b", "mol/kg", "molality", "مولالیته", "molaalisuus"), ("i", "1", "van't Hoff i", "i", "i"))),
        ("tx_bp_elev", "chem.collig", "Boiling-point elevation", "افزایش نقطه جوش", "Kiehumispisteen nousu",
         "dT = Kb*b*i",
         V(("dT", "K", "delta T", "دلتا تی", "dT"), ("Kb", "K*kg/mol", "Kb", "Kb", "Kb"),
           ("b", "mol/kg", "molality", "مولالیته", "molaalisuus"), ("i", "1", "i", "i", "i"))),
        ("tx_osmotic", "chem.collig", "Osmotic pressure", "فشار اسمزی", "Osmoottinen paine",
         "Pi = i*Mconc*Rgas*T",
         V(("Pi", "Pa", "pi", "پی", "pi"), ("i", "1", "i", "i", "i"), ("Mconc", "mol/m^3", "c", "c", "c"),
           ("Rgas", "J/(mol*K)", "R", "R", "R"), ("T", "K", "T", "T", "T"))),
        ("tx_hh", "chem.acid", "Henderson-Hasselbalch", "هندرسون-هاسلبالخ", "Henderson-Hasselbalch",
         "pH = pKa + log(AoverHA)",
         V(("pH", "1", "pH", "pH", "pH"), ("pKa", "1", "pKa", "pKa", "pKa"),
           ("AoverHA", "1", "A-/HA", "A-/HA", "A-/HA"))),
        ("tx_kw", "chem.acid", "Water Kw at T", "Kw آب", "Kw",
         "Kw = H*OH",
         V(("Kw", "1", "Kw", "Kw", "Kw"), ("H", "mol/L", "[H+]", "[H+]", "[H+]"), ("OH", "mol/L", "[OH-]", "[OH-]", "[OH-]"))),
        ("tx_pH_strong", "chem.acid", "pH strong acid", "pH اسید قوی", "Vahvan hapon pH",
         "pH = -log(H)/log(10)",
         V(("pH", "1", "pH", "pH", "pH"), ("H", "mol/L", "[H+]", "[H+]", "[H+]"))),
        ("tx_ka_from_pka", "chem.acid", "Ka from pKa", "Ka از pKa", "Ka pKa:sta",
         "Ka = 10**(-pKa)",
         V(("Ka", "1", "Ka", "Ka", "Ka"), ("pKa", "1", "pKa", "pKa", "pKa"))),
        ("tx_buffer_cap", "chem.buf", "Van Slyke buffer capacity piece", "ظرفیت بافر", "Puskurikapasiteetti",
         "beta_c = 2.303*c*Ka*H/(Ka + H)**2",
         V(("beta_c", "1", "capacity", "ظرفیت", "kapasiteetti"), ("c", "mol/L", "total", "کل", "kokonais"),
           ("Ka", "1", "Ka", "Ka", "Ka"), ("H", "mol/L", "[H+]", "[H+]", "[H+]"))),
        ("tx_rate1", "chem.kinetics", "First-order integrated", "مرتبه اول انتگرالی", "1. kertaluku",
         "lnA = lnA0 - k*t",
         V(("lnA", "1", "ln[A]", "ln[A]", "ln[A]"), ("lnA0", "1", "ln[A]0", "ln[A]0", "ln[A]0"),
           ("k", "1/s", "k", "k", "k"), ("t", "s", "t", "t", "t"))),
        ("tx_rate2", "chem.kinetics", "Second-order integrated", "مرتبه دوم", "2. kertaluku",
         "invA = invA0 + k*t",
         V(("invA", "L/mol", "1/[A]", "1/[A]", "1/[A]"), ("invA0", "L/mol", "1/[A]0", "1/[A]0", "1/[A]0"),
           ("k", "L/(mol*s)", "k", "k", "k"), ("t", "s", "t", "t", "t"))),
        ("tx_arrhenius", "chem.kinetics", "Arrhenius k", "آرنیوس", "Arrhenius",
         "k = A0*exp(-Ea/(Rgas*T))",
         V(("k", "1/s", "k", "k", "k"), ("A0", "1/s", "A", "A", "A"), ("Ea", "J/mol", "Ea", "Ea", "Ea"),
           ("Rgas", "J/(mol*K)", "R", "R", "R"), ("T", "K", "T", "T", "T"))),
        ("tx_arrhenius_two", "chem.kinetics", "Two-T Arrhenius", "آرنیوس دو دما", "Kaksi T Arrhenius",
         "logk = logA - Ea/(Rgas*T)/log(10)*0 + (-Ea/(2.303*Rgas))*(1/T)",
         V(("logk", "1", "log k placeholder use ln form", "log k", "log k"),
           ("logA", "1", "log A", "log A", "log A"), ("Ea", "J/mol", "Ea", "Ea", "Ea"),
           ("Rgas", "J/(mol*K)", "R", "R", "R"), ("T", "K", "T", "T", "T"))),
        ("tx_halflife1", "chem.kinetics", "First-order half-life", "نیمه‌عمر مرتبه ۱", "1. kertaluvun puoliintuminen",
         "th = log(2)/k",
         V(("th", "s", "t1/2", "t1/2", "t1/2"), ("k", "1/s", "k", "k", "k"))),
        ("tx_halflife2", "chem.kinetics", "Second-order half-life", "نیمه‌عمر مرتبه ۲", "2. kertaluvun puoliintuminen",
         "th = 1/(k*A0)",
         V(("th", "s", "t1/2", "t1/2", "t1/2"), ("k", "L/(mol*s)", "k", "k", "k"), ("A0", "mol/L", "[A]0", "[A]0", "[A]0"))),
        ("tx_nernst", "chem.electro", "Nernst 25 C one e", "نرنست", "Nernst",
         "Ecell = E0 - (0.059/n)*log(Q)/log(10)",
         V(("Ecell", "V", "E", "E", "E"), ("E0", "V", "E0", "E0", "E0"), ("n", "1", "n e-", "n", "n"),
           ("Q", "1", "Q", "Q", "Q"))),
        ("tx_faraday_m", "chem.electro", "Faraday mass", "جرم فارادی", "Faradayn massa",
         "m = (M*Icur*t)/(n*Fara)",
         V(("m", "g", "mass", "جرم", "massa"), ("M", "g/mol", "M", "M", "M"), ("Icur", "A", "current", "جریان", "virta"),
           ("t", "s", "t", "t", "t"), ("n", "1", "n", "n", "n"), ("Fara", "C/mol", "F", "F", "F"))),
        ("tx_beers", "chem.spec", "Beer-Lambert", "بیر-لامبرت", "Beer-Lambert",
         "Aabs = eps*b*c",
         V(("Aabs", "1", "absorbance", "جذب", "absorbanssi"), ("eps", "L/(mol*cm)", "epsilon", "اپسیلون", "epsilon"),
           ("b", "cm", "path", "مسیر", "tie"), ("c", "mol/L", "c", "c", "c"))),
        ("tx_gibbs", "chem.thermo", "Gibbs G=H-TS", "گیبس", "Gibbs",
         "G = H - T*S",
         V(("G", "J", "G", "G", "G"), ("H", "J", "H", "H", "H"), ("T", "K", "T", "T", "T"), ("S", "J/K", "S", "S", "S"))),
        ("tx_gibbs_r", "chem.thermo", "dG = -RT ln K", "گیبس تعادلی", "dG = -RT ln K",
         "dG = -Rgas*T*log(K)",
         V(("dG", "J/mol", "delta G0", "دلتا گیبس", "dG"), ("Rgas", "J/(mol*K)", "R", "R", "R"),
           ("T", "K", "T", "T", "T"), ("K", "1", "K", "K", "K"))),
        ("tx_vant_hoff", "chem.thermo", "van't Hoff two T", "وانت‌هوف", "van 't Hoff",
         "logK2 = logK1 - (dH/Rgas)*(1/T2 - 1/T1)",
         V(("logK2", "1", "ln K2", "ln K2", "ln K2"), ("logK1", "1", "ln K1", "ln K1", "ln K1"),
           ("dH", "J/mol", "delta H", "دلتا اچ", "dH"), ("Rgas", "J/(mol*K)", "R", "R", "R"),
           ("T2", "K", "T2", "T2", "T2"), ("T1", "K", "T1", "T1", "T1"))),
        ("tx_clapeyron", "chem.thermo", "Clausius-Clapeyron", "کلازیوس-کلاپیرون", "Clausius-Clapeyron",
         "logP = -dH/(Rgas*T) + C",
         V(("logP", "1", "ln P", "ln P", "ln P"), ("dH", "J/mol", "delta Hvap", "دلتا اچ", "dH"),
           ("Rgas", "J/(mol*K)", "R", "R", "R"), ("T", "K", "T", "T", "T"), ("C", "1", "const", "ثابت", "vakio"))),
        ("tx_keq_conc", "chem.eq", "Kc two species aA=bB", "Kc", "Kc",
         "Kc = B**b / A**a",
         V(("Kc", "1", "Kc", "Kc", "Kc"), ("B", "mol/L", "[B]", "[B]", "[B]"), ("b", "1", "coeff B", "ضریب B", "B"),
           ("A", "mol/L", "[A]", "[A]", "[A]"), ("a", "1", "coeff A", "ضریب A", "A"))),
        ("tx_kp_kc", "chem.eq", "Kp from Kc", "Kp از Kc", "Kp Kc:sta",
         "Kp = Kc*(Rgas*T)**dn",
         V(("Kp", "1", "Kp", "Kp", "Kp"), ("Kc", "1", "Kc", "Kc", "Kc"),
           ("Rgas", "L*bar/(mol*K)", "R", "R", "R"), ("T", "K", "T", "T", "T"), ("dn", "1", "delta n gas", "دلتا n", "dn"))),
        ("tx_yield", "chem.stoich", "Percent yield", "بازده درصدی", "Saantoprosentti",
         "y = 100*actual/theo",
         V(("y", "1", "percent yield", "درصد بازده", "saanto %"), ("actual", "g", "actual", "واقعی", "todellinen"),
           ("theo", "g", "theoretical", "نظری", "teoreettinen"))),
        ("tx_limiting", "chem.stoich", "Moles from mass", "مول از جرم", "Moolit massasta",
         "n = m/M",
         V(("n", "mol", "n", "n", "n"), ("m", "g", "mass", "جرم", "massa"), ("M", "g/mol", "M", "M", "M"))),
        ("tx_density_crystal", "chem.stoich", "Crystal density", "چگالی بلور", "Kidetiheys",
         "rho = Z*M/(Nav*a**3)",
         V(("rho", "g/cm^3", "density", "چگالی", "tiheys"), ("Z", "1", "formula units", "واحد فرمول", "yksikot"),
           ("M", "g/mol", "M", "M", "M"), ("Nav", "1/mol", "N_A", "N_A", "N_A"), ("a", "cm", "cell edge", "ضلع سلول", "solu"))),
        ("tx_langmuir", "chem.surf", "Langmuir coverage", "پوشش لانگمویر", "Langmuir peitto",
         "theta = K*p/(1 + K*p)",
         V(("theta", "1", "coverage", "پوشش", "peitto"), ("K", "1/Pa", "K", "K", "K"), ("p", "Pa", "p", "p", "p"))),
        ("tx_bet_simp", "chem.surf", "BET linearized piece", "بت ساده", "BET",
         "y = 1/(v*(p0/p - 1))",
         V(("y", "1/m^3", "BET y", "y", "y"), ("v", "m^3", "adsorbed V", "حجم جذب", "V"),
           ("p0", "Pa", "p0", "p0", "p0"), ("p", "Pa", "p", "p", "p"))),
        ("tx_young_laplace", "chem.surf", "Young-Laplace sphere", "یانگ-لاپلاس", "Young-Laplace",
         "dP = 2*sig/r",
         V(("dP", "Pa", "delta P", "دلتا پی", "dP"), ("sig", "N/m", "surface tension", "کشش سطحی", "pintajannitys"),
           ("r", "m", "radius", "شعاع", "sade"))),
        ("tx_contact", "chem.surf", "Young contact angle", "زاویه تماس یانگ", "Youngin kulma",
         "cos(th) = (sg - sl)/lg",
         V(("th", "rad", "contact angle", "زاویه تماس", "kosketuskulma"), ("sg", "N/m", "solid-gas", "جامد-گاز", "kiintea-kaasu"),
           ("sl", "N/m", "solid-liquid", "جامد-مایع", "kiintea-neste"), ("lg", "N/m", "liquid-gas", "مایع-گاز", "neste-kaasu"))),
        ("tx_q_nuclear", "chem.nuclear", "Reaction Q-value MeV", "Q واکنش", "Q-arvo",
         "Q = (mi - mf)*931.494",
         V(("Q", "MeV", "Q", "Q", "Q"), ("mi", "u", "initial mass", "جرم اولیه", "alkumassa"),
           ("mf", "u", "final mass", "جرم نهایی", "loppumassa"))),
        ("tx_activity", "chem.nuclear", "Activity A=λN", "فعالیت", "Aktiivisuus",
         "Aact = lam*N",
         V(("Aact", "Bq", "activity", "فعالیت", "aktiivisuus"), ("lam", "1/s", "lambda", "لامبدا", "lambda"),
           ("N", "1", "nuclei", "هسته", "ytimet"))),
        ("tx_decay_N", "chem.nuclear", "Exponential decay N", "واپاشی نمایی", "Hajoaminen",
         "N = N0*exp(-lam*t)",
         V(("N", "1", "N", "N", "N"), ("N0", "1", "N0", "N0", "N0"), ("lam", "1/s", "lambda", "لامبدا", "lambda"),
           ("t", "s", "t", "t", "t"))),
    ]
    # drop the ugly two-T arrhenius
    items = [it for it in items if it[0] != "tx_arrhenius_two"]
    items.append(("tx_arrhenius_ln", "chem.kinetics", "Arrhenius ln k", "آرنیوس ln k", "Arrhenius ln k",
                  "lnk = lnA - Ea/(Rgas*T)",
                  V(("lnk", "1", "ln k", "ln k", "ln k"), ("lnA", "1", "ln A", "ln A", "ln A"),
                    ("Ea", "J/mol", "Ea", "Ea", "Ea"), ("Rgas", "J/(mol*K)", "R", "R", "R"), ("T", "K", "T", "T", "T"))))
    for it in items:
        a(row(*it))
    return R
