"""Engineering, medicine, finance, earth, everyday textbook rows plus harmonic families."""

from __future__ import annotations

from add_textbook_formulas import V, row


def harmonics_and_filters():
    R = []
    a = R.append
    for n in range(1, 21):
        a(row(f"tx_string_fn_{n}", "physics.waves",
              f"String f_{n}", f"بسامد سیم هارمونیک {n}", f"Kielen f_{n}",
              f"f = {n}*v/(2*L)",
              V(("f", "Hz", "frequency", "بسامد", "taajuus"), ("v", "m/s", "wave speed", "سرعت موج", "nopeus"),
                ("L", "m", "length", "طول", "pituus"))))
        a(row(f"tx_openpipe_fn_{n}", "phys.acoust",
              f"Open pipe f_{n}", f"لوله باز هارمونیک {n}", f"Avoimen putken f_{n}",
              f"f = {n}*v/(2*L)",
              V(("f", "Hz", "frequency", "بسامد", "taajuus"), ("v", "m/s", "sound speed", "سرعت صوت", "aanen n."),
                ("L", "m", "length", "طول", "pituus"))))
        if n % 2 == 1:
            a(row(f"tx_closedpipe_fn_{n}", "phys.acoust",
                  f"Closed pipe f_{n}", f"لوله بسته هارمونیک {n}", f"Suljetun putken f_{n}",
                  f"f = {n}*v/(4*L)",
                  V(("f", "Hz", "frequency", "بسامد", "taajuus"), ("v", "m/s", "sound speed", "سرعت صوت", "aanen n."),
                    ("L", "m", "length", "طول", "pituus"))))
    for n in (1, 2, 4, 12, 24, 52, 365):
        a(row(f"tx_compound_m_{n}", "math.finance",
              f"Compound m={n} periods/year", f"بهره مرکب m={n}", f"Korko m={n}",
              f"A = P*(1 + r/{n})**({n}*t)",
              V(("A", "1", "amount", "مبلغ", "maara"), ("P", "1", "principal", "اصل", "paaoma"),
                ("r", "1", "APR", "نرخ سالانه", "vuosikorko"), ("t", "yr", "years", "سال", "vuodet"))))
        a(row(f"tx_eff_rate_{n}", "math.finance",
              f"Effective annual rate m={n}", f"نرخ مؤثر سالانه m={n}", f"Todellinen vuosikorko m={n}",
              f"reffect = (1 + r/{n})**{n} - 1",
              V(("reffect", "1", "EAR", "نرخ مؤثر", "todellinen"), ("r", "1", "nominal", "اسمی", "nimellinen"))))
    for n in range(2, 13):
        a(row(f"tx_lp_butter_ord_{n}", "eng.signal",
              f"Butterworth |H| order {n} at wc", f"باتروورث مرتبه {n} در wc", f"Butterworth {n} wc:ssa",
              "H = 1/sqrt(2)",
              V(("H", "1", "|H(wc)|", "|H|", "|H|"))))
        a(row(f"tx_rc_fc_{n}", "eng.signal",
              f"n={n} cascaded RC fc scale", f"n={n} آRC آبشاری", f"n={n} RC-ketju",
              f"fc = 1/(2*pi*R*C*sqrt(2**(1/{n}) - 1))",
              V(("fc", "Hz", "cutoff", "قطع", "rajataajuus"), ("R", "ohm", "R", "R", "R"), ("C", "F", "C", "C", "C"))))
    return R


def engineering():
    R = []
    a = R.append
    elec = [
        ("tx_ohm", "Ohm's law", "اهم", "Ohm",
         "V = i*R", V(("V", "V", "voltage", "ولتاژ", "jannite"), ("i", "A", "current", "جریان", "virta"),
                      ("R", "ohm", "R", "R", "R"))),
        ("tx_power_vi", "Electric power VI", "توان الکتریکی", "Sahkoteho",
         "P = V*i", V(("P", "W", "power", "توان", "teho"), ("V", "V", "V", "V", "V"), ("i", "A", "current", "جریان", "virta"))),
        ("tx_series_r2", "Two resistors series", "دو مقاومت سری", "Kaksi vastusta sarjassa",
         "R = R1 + R2", V(("R", "ohm", "Req", "معادل", "ekv"), ("R1", "ohm", "R1", "R1", "R1"), ("R2", "ohm", "R2", "R2", "R2"))),
        ("tx_par_r2", "Two resistors parallel", "دو مقاومت موازی", "Kaksi vastusta rinnan",
         "R = R1*R2/(R1 + R2)", V(("R", "ohm", "Req", "معادل", "ekv"), ("R1", "ohm", "R1", "R1", "R1"),
                                  ("R2", "ohm", "R2", "R2", "R2"))),
        ("tx_divider", "Voltage divider", "مقسم ولتاژ", "Jannitejakaja",
         "Vout = Vin*R2/(R1 + R2)", V(("Vout", "V", "Vout", "خروجی", "lahto"), ("Vin", "V", "Vin", "ورودی", "otto"),
                                      ("R1", "ohm", "R1", "R1", "R1"), ("R2", "ohm", "R2", "R2", "R2"))),
        ("tx_xc", "Capacitive reactance", "راکتانس خازنی", "Kapasitiivinen reaktanssi",
         "Xc = 1/(2*pi*f*C)", V(("Xc", "ohm", "Xc", "Xc", "Xc"), ("f", "Hz", "f", "f", "f"), ("C", "F", "C", "C", "C"))),
        ("tx_xl", "Inductive reactance", "راکتانس سلفی", "Induktiivinen reaktanssi",
         "Xl = 2*pi*f*L", V(("Xl", "ohm", "Xl", "Xl", "Xl"), ("f", "Hz", "f", "f", "f"), ("L", "H", "L", "L", "L"))),
        ("tx_rlc_z", "Series RLC |Z|", "امپدانس RLC سری", "RLC |Z|",
         "Z = sqrt(R**2 + (Xl - Xc)**2)", V(("Z", "ohm", "Z", "Z", "Z"), ("R", "ohm", "R", "R", "R"),
                                            ("Xl", "ohm", "Xl", "Xl", "Xl"), ("Xc", "ohm", "Xc", "Xc", "Xc"))),
        ("tx_resonant", "LC resonant frequency", "تشدید LC", "LC-resonanssi",
         "f0 = 1/(2*pi*sqrt(L*C))", V(("f0", "Hz", "f0", "f0", "f0"), ("L", "H", "L", "L", "L"), ("C", "F", "C", "C", "C"))),
        ("tx_tau_rc", "RC time constant", "ثابت زمانی RC", "RC-aikavakio",
         "tau = R*C", V(("tau", "s", "tau", "تاو", "tau"), ("R", "ohm", "R", "R", "R"), ("C", "F", "C", "C", "C"))),
        ("tx_tau_rl", "RL time constant", "ثابت زمانی RL", "RL-aikavakio",
         "tau = L/R", V(("tau", "s", "tau", "تاو", "tau"), ("L", "H", "L", "L", "L"), ("R", "ohm", "R", "R", "R"))),
        ("tx_xf_turns", "Transformer turns", "دور ترانسفورماتور", "Muuntajan kierrokset",
         "Vs/Vp = Ns/Np", V(("Vs", "V", "Vs", "ثانویه", "sek"), ("Vp", "V", "Vp", "اولیه", "prim"),
                            ("Ns", "1", "Ns", "Ns", "Ns"), ("Np", "1", "Np", "Np", "Np"))),
        ("tx_three_p", "3-phase active power", "توان سه‌فاز", "Kolmivaiheinen teho",
         "P = sqrt(3)*VL*IL*pf", V(("P", "W", "P", "P", "P"), ("VL", "V", "line V", "ولتاژ خط", "paitejannite"),
                                   ("IL", "A", "line I", "جریان خط", "paitevirta"), ("pf", "1", "power factor", "ضریب توان", "tehokerroin"))),
        ("tx_star_vl", "Star VL", "ستاره VL", "Tahden VL",
         "VL = sqrt(3)*Vph", V(("VL", "V", "line", "خط", "johdin"), ("Vph", "V", "phase", "فاز", "vaihe"))),
        ("tx_cap_parallel_plate", "Parallel-plate C", "خازن صفحات موازی", "Levykondensaattori",
         "C = eps*A/d", V(("C", "F", "C", "C", "C"), ("eps", "F/m", "epsilon", "اپسیلون", "epsilon"),
                          ("A", "m^2", "area", "مساحت", "pinta"), ("d", "m", "gap", "فاصله", "vali"))),
        ("tx_energy_C", "Capacitor energy", "انرژی خازن", "Kondensaattorin energia",
         "U = C*V**2/2", V(("U", "J", "U", "U", "U"), ("C", "F", "C", "C", "C"), ("V", "V", "V", "V", "V"))),
        ("tx_energy_L", "Inductor energy", "انرژی سلف", "Kelan energia",
         "U = L*i**2/2", V(("U", "J", "U", "U", "U"), ("L", "H", "L", "L", "L"), ("i", "A", "current", "جریان", "virta"))),
        ("tx_rms_sine", "Sine RMS", "RMS سینوسی", "Sinin RMS",
         "Vrms = Vp/sqrt(2)", V(("Vrms", "V", "Vrms", "Vrms", "Vrms"), ("Vp", "V", "peak", "قله", "huippu"))),
        ("tx_pwm", "PWM duty", "وظیفه PWM", "PWM-suhde",
         "D = 100*ton/T", V(("D", "1", "duty %", "درصد وظیفه", "suhde %"), ("ton", "s", "on time", "زمان روشن", "paalla"),
                            ("T", "s", "period", "دوره", "jakso"))),
        ("tx_thevenin_I", "Norton from Thevenin", "norton از تونن", "Norton Theveninista",
         "IN = Vth/Rth", V(("IN", "A", "Norton I", "جریان نورتون", "Norton"), ("Vth", "V", "Vth", "Vth", "Vth"),
                           ("Rth", "ohm", "Rth", "Rth", "Rth"))),
        ("tx_max_power", "Max power transfer load", "حداکثر توان بار", "Max teho",
         "PL = Vth**2/(4*Rth)", V(("PL", "W", "Pmax", "Pmax", "Pmax"), ("Vth", "V", "Vth", "Vth", "Vth"),
                                  ("Rth", "ohm", "Rth", "Rth", "Rth"))),
        ("tx_resistivity", "Resistance from resistivity", "مقاومت از مقاومت ویژه", "Resistanssi",
         "R = rho*L/A", V(("R", "ohm", "R", "R", "R"), ("rho", "ohm*m", "rho", "رو", "rho"),
                          ("L", "m", "length", "طول", "pituus"), ("A", "m^2", "area", "سطح مقطع", "pinta"))),
        ("tx_j_sigma", "Ohm J=sigma E", "چگالی جریان", "J = sigma E",
         "J = sig*Ef", V(("J", "A/m^2", "J", "J", "J"), ("sig", "S/m", "conductivity", "رسانایی", "johtavuus"),
                         ("Ef", "V/m", "E field", "میدان", "kenta"))),
    ]
    for it in elec:
        a(row(it[0], "eng.elec", it[1], it[2], it[3], it[4], it[5]))

    ctrl = [
        ("tx_wn_2nd", "Second-order wn", "wn مرتبه ۲", "2. kertaluvun wn",
         "wn = sqrt(k/m)", V(("wn", "rad/s", "wn", "wn", "wn"), ("k", "N/m", "k", "k", "k"), ("m", "kg", "m", "m", "m"))),
        ("tx_zeta_2nd", "Second-order zeta", "زتا مرتبه ۲", "2. kertaluvun zeta",
         "z = c/(2*sqrt(k*m))", V(("z", "1", "zeta", "زتا", "zeta"), ("c", "N*s/m", "c", "c", "c"),
                                  ("k", "N/m", "k", "k", "k"), ("m", "kg", "m", "m", "m"))),
        ("tx_ts_2pct", "2% settling time", "زمان نشست ۲٪", "2 % asettumisaika",
         "ts = 4/(z*wn)", V(("ts", "s", "ts", "ts", "ts"), ("z", "1", "zeta", "زتا", "zeta"),
                            ("wn", "rad/s", "wn", "wn", "wn"))),
        ("tx_tp_2nd", "Peak time underdamped", "زمان قله", "Huippuaika",
         "tp = pi/(wn*sqrt(1 - z**2))", V(("tp", "s", "tp", "tp", "tp"), ("wn", "rad/s", "wn", "wn", "wn"),
                                          ("z", "1", "zeta", "زتا", "zeta"))),
        ("tx_os_2nd", "Percent overshoot", "فراجهش درصدی", "Ylitys %",
         "os = 100*exp(-pi*z/sqrt(1 - z**2))", V(("os", "1", "OS %", "فراجهش", "ylitys"), ("z", "1", "zeta", "زتا", "zeta"))),
        ("tx_kp_step", "Position error Kp type0", "خطای ماندگار نوع ۰", "Pysyva virhe tyyppi 0",
         "ess = 1/(1 + Kp)", V(("ess", "1", "ess", "خطای ماندگار", "pysyva"), ("Kp", "1", "Kp", "Kp", "Kp"))),
        ("tx_pid_u", "PID parallel u", "PID موازی", "PID",
         "u = Kp*e + Ki*ei + Kd*ed", V(("u", "1", "u", "u", "u"), ("Kp", "1", "Kp", "Kp", "Kp"),
                                       ("e", "1", "error", "خطا", "virhe"), ("Ki", "1", "Ki", "Ki", "Ki"),
                                       ("ei", "1", "int e", "انتگرال خطا", "int"), ("Kd", "1", "Kd", "Kd", "Kd"),
                                       ("ed", "1", "de/dt", "مشتق خطا", "der"))),
        ("tx_gain_db", "Gain in dB", "بهره دسی‌بل", "Vahvistus dB",
         "gdb = 20*log(A)/log(10)", V(("gdb", "dB", "dB", "dB", "dB"), ("A", "1", "linear gain", "بهره خطی", "vahvistus"))),
        ("tx_bode_pole", "Single-pole |G|", "اندازه قطب ساده", "Yhden navan |G|",
         "mag = 1/sqrt(1 + (w/w0)**2)", V(("mag", "1", "|G|", "|G|", "|G|"), ("w", "rad/s", "w", "w", "w"),
                                          ("w0", "rad/s", "corner", "گوشه", "kulma"))),
        ("tx_marg_pm", "Phase margin from phase", "حاشیه فاز", "Vaihemarginaali",
         "pm = 180 + ph", V(("pm", "deg", "PM", "حاشیه فاز", "PM"), ("ph", "deg", "angle at gain crossover", "فاز", "vaihe"))),
    ]
    for it in ctrl:
        a(row(it[0], "eng.control", it[1], it[2], it[3], it[4], it[5]))

    beams = [
        ("tx_beam_cant_endP", "Cantilever end load deflection", "خیز تیر یک‌سرگیردار بار انتها", "Ulokepalkin taipuma",
         "d = P*L**3/(3*Emod*Izz)", V(("d", "m", "deflection", "خیز", "taipuma"), ("P", "N", "load", "بار", "kuorma"),
                                      ("L", "m", "length", "طول", "pituus"), ("Emod", "Pa", "E", "E", "E"),
                                      ("Izz", "m^4", "I", "I", "I"))),
        ("tx_beam_cant_endM", "Cantilever end moment deflection", "خیز با گشتاور انتها", "Uloke momentilla",
         "d = M*L**2/(2*Emod*Izz)", V(("d", "m", "deflection", "خیز", "taipuma"), ("M", "N*m", "moment", "گشتاور", "momentti"),
                                      ("L", "m", "L", "L", "L"), ("Emod", "Pa", "E", "E", "E"), ("Izz", "m^4", "I", "I", "I"))),
        ("tx_beam_ss_mid", "Simply supported mid load", "تیر ساده بار وسط", "Vapaasti tuettu keski",
         "d = P*L**3/(48*Emod*Izz)", V(("d", "m", "deflection", "خیز", "taipuma"), ("P", "N", "P", "P", "P"),
                                       ("L", "m", "L", "L", "L"), ("Emod", "Pa", "E", "E", "E"), ("Izz", "m^4", "I", "I", "I"))),
        ("tx_beam_ss_udl", "Simply supported UDL mid", "تیر ساده بار گسترده", "Tasainen kuorma",
         "d = 5*w*L**4/(384*Emod*Izz)", V(("d", "m", "deflection", "خیز", "taipuma"), ("w", "N/m", "w", "w", "w"),
                                          ("L", "m", "L", "L", "L"), ("Emod", "Pa", "E", "E", "E"), ("Izz", "m^4", "I", "I", "I"))),
        ("tx_beam_cant_udl", "Cantilever UDL tip", "یک‌سرگیردار گسترده", "Uloke tasainen",
         "d = w*L**4/(8*Emod*Izz)", V(("d", "m", "deflection", "خیز", "taipuma"), ("w", "N/m", "w", "w", "w"),
                                      ("L", "m", "L", "L", "L"), ("Emod", "Pa", "E", "E", "E"), ("Izz", "m^4", "I", "I", "I"))),
        ("tx_bending_stress", "Bending stress", "تنش خمشی", "Taivutusjannitys",
         "sig = M*c/Izz", V(("sig", "Pa", "sigma", "تنش", "jannitys"), ("M", "N*m", "M", "M", "M"),
                            ("c", "m", "c", "c", "c"), ("Izz", "m^4", "I", "I", "I"))),
        ("tx_shear_avg", "Average shear stress", "تنش برشی متوسط", "Keskim. leikkaus",
         "tau = Vshr/A", V(("tau", "Pa", "tau", "برش", "leikkaus"), ("Vshr", "N", "shear", "برش", "leikkausvoima"),
                           ("A", "m^2", "area", "سطح", "pinta"))),
        ("tx_torsion_stress", "Round shaft torsion stress", "تنش پیچش شفت", "Vantiojannitys",
         "tau = Tq*r/J", V(("tau", "Pa", "tau", "برش پیچشی", "vantio"), ("Tq", "N*m", "T", "T", "T"),
                           ("r", "m", "r", "r", "r"), ("J", "m^4", "J", "J", "J"))),
        ("tx_polar_J", "Solid circle polar J", "J قطبی دایره", "Napajatka",
         "J = pi*r**4/2", V(("J", "m^4", "J", "J", "J"), ("r", "m", "r", "r", "r"))),
        ("tx_euler_buckle", "Euler buckle pinned", "کمانش اویلر دو سر مفصل", "Euler nurjahdus",
         "Pcr = pi**2*Emod*Izz/L**2", V(("Pcr", "N", "Pcr", "Pcr", "Pcr"), ("Emod", "Pa", "E", "E", "E"),
                                        ("Izz", "m^4", "I", "I", "I"), ("L", "m", "L", "L", "L"))),
        ("tx_slenderness", "Slenderness ratio", "لاغری", "Hoikkuus",
         "s = L/k", V(("s", "1", "L/k", "L/k", "L/k"), ("L", "m", "effective L", "طول مؤثر", "pituus"),
                      ("k", "m", "radius of gyration", "شعاع ژیراسیون", "hitaussade"))),
        ("tx_hooke_axial", "Axial stress-strain", "تنش-کرنش محوری", "Aksiaalinen Hooke",
         "sig = Emod*eps", V(("sig", "Pa", "stress", "تنش", "jannitys"), ("Emod", "Pa", "E", "E", "E"),
                             ("eps", "1", "strain", "کرنش", "venyma"))),
        ("tx_axial_dL", "Axial elongation", "ازدیاد طول محوری", "Aksiaalinen pitenema",
         "dL = P*L/(A*Emod)", V(("dL", "m", "delta L", "ازدیاد طول", "pitenema"), ("P", "N", "P", "P", "P"),
                                ("L", "m", "L", "L", "L"), ("A", "m^2", "A", "A", "A"), ("Emod", "Pa", "E", "E", "E"))),
        ("tx_poisson", "Poisson lateral strain", "پواسون", "Poisson",
         "ey = -nu*ex", V(("ey", "1", "lateral strain", "کرنش جانبی", "sivuvvenyma"),
                          ("nu", "1", "Poisson", "پواسون", "Poisson"), ("ex", "1", "axial strain", "کرنش محوری", "aks. venyma"))),
        ("tx_mohr_center", "Mohr circle center", "مرکز دایره مور", "Mohr keskipiste",
         "c = (sx + sy)/2", V(("c", "Pa", "center", "مرکز", "keski"), ("sx", "Pa", "sx", "sx", "sx"),
                              ("sy", "Pa", "sy", "sy", "sy"))),
        ("tx_mohr_R", "Mohr circle radius", "شعاع دایره مور", "Mohr sade",
         "R = sqrt(((sx - sy)/2)**2 + txy**2)", V(("R", "Pa", "R", "R", "R"), ("sx", "Pa", "sx", "sx", "sx"),
                                                  ("sy", "Pa", "sy", "sy", "sy"), ("txy", "Pa", "txy", "txy", "txy"))),
        ("tx_vonmises_2d", "von Mises plane stress", "فون‌میزس تنش صفحه‌ای", "von Mises",
         "seq = sqrt(s1**2 - s1*s2 + s2**2)", V(("seq", "Pa", "seq", "معادل", "ekv"),
                                                ("s1", "Pa", "s1", "s1", "s1"), ("s2", "Pa", "s2", "s2", "s2"))),
        ("tx_goodman", "Goodman endurance line", "گودمن", "Goodman",
         "sa/se + sm/sut = 1", V(("sa", "Pa", "alt stress", "تنش متناوب", "vaihtelu"),
                                 ("se", "Pa", "endurance", "دوام", "kestavyys"),
                                 ("sm", "Pa", "mean stress", "تنش میانگین", "keskijannitys"),
                                 ("sut", "Pa", "ultimate", "نهایی", "murtolujuus"))),
        ("tx_lewis", "Lewis gear bending", "لوئیس چرخ‌دنده", "Lewis",
         "sig = Ft/(b*p*y)", V(("sig", "Pa", "bending", "خمش", "taivutus"), ("Ft", "N", "tangential", "مماسی", "tangentiaalinen"),
                               ("b", "m", "face width", "پهنای دندانه", "leveys"), ("p", "m", "circular pitch", "گام", "jako"),
                               ("y", "1", "Lewis y", "y", "y"))),
        ("tx_hertz_cyl", "Hertz two cylinders contact half-width", "هرتز دو استوانه", "Hertz",
         "b = sqrt(4*F*R/(pi*L*Estar))", V(("b", "m", "half-width", "نیم‌عرض", "puolileveys"),
                                           ("F", "N", "load", "بار", "kuorma"), ("R", "m", "equiv R", "R معادل", "R"),
                                           ("L", "m", "length", "طول", "pituus"), ("Estar", "Pa", "E*", "E*", "E*"))),
    ]
    for it in beams:
        a(row(it[0], "eng.mech", it[1], it[2], it[3], it[4], it[5]))

    heat = [
        ("tx_conduction", "Fourier conduction 1D", "هدایت فوریه", "Johtuminen",
         "q = -k*A*dT/dx", V(("q", "W", "q", "q", "q"), ("k", "W/(m*K)", "k", "k", "k"),
                             ("A", "m^2", "A", "A", "A"), ("dT", "K", "dT", "dT", "dT"), ("dx", "m", "dx", "dx", "dx"))),
        ("tx_convection", "Newton cooling", "جابهجایی نیوتن", "Konvektio",
         "q = h*A*dT", V(("q", "W", "q", "q", "q"), ("h", "W/(m^2*K)", "h", "h", "h"),
                         ("A", "m^2", "A", "A", "A"), ("dT", "K", "dT", "dT", "dT"))),
        ("tx_lmtd", "LMTD counterflow", "LMTD ناهمسو", "LMTD",
         "dt = (dT1 - dT2)/log(dT1/dT2)", V(("dt", "K", "LMTD", "LMTD", "LMTD"),
                                            ("dT1", "K", "end 1", "سر ۱", "paa 1"), ("dT2", "K", "end 2", "سر ۲", "paa 2"))),
        ("tx_hx_q", "Heat exchanger Q", "مبدل گرما Q", "Lammonsiirrin Q",
         "Q = U*A*dt", V(("Q", "W", "Q", "Q", "Q"), ("U", "W/(m^2*K)", "U", "U", "U"),
                         ("A", "m^2", "A", "A", "A"), ("dt", "K", "LMTD", "LMTD", "LMTD"))),
        ("tx_ntu", "NTU", "NTU", "NTU",
         "N = U*A/(m*cp)", V(("N", "1", "NTU", "NTU", "NTU"), ("U", "W/(m^2*K)", "U", "U", "U"),
                             ("A", "m^2", "A", "A", "A"), ("m", "kg/s", "mass flow", "دبی جرمی", "massa"),
                             ("cp", "J/(kg*K)", "cp", "cp", "cp"))),
        ("tx_fin_m", "Fin m parameter", "پارامتر پره m", "Evan m",
         "mfin = sqrt(h*P/(k*Ac))", V(("mfin", "1/m", "m", "m", "m"), ("h", "W/(m^2*K)", "h", "h", "h"),
                                      ("P", "m", "perimeter", "محیط", "piiri"), ("k", "W/(m*K)", "k", "k", "k"),
                                      ("Ac", "m^2", "area", "سطح مقطع", "pinta"))),
        ("tx_fin_inf", "Infinite fin heat", "گرمای پره بی‌نهایت", "Aareton evä",
         "q = sqrt(h*P*k*Ac)*(Tb - Tinf)", V(("q", "W", "q", "q", "q"), ("h", "W/(m^2*K)", "h", "h", "h"),
                                             ("P", "m", "P", "P", "P"), ("k", "W/(m*K)", "k", "k", "k"),
                                             ("Ac", "m^2", "Ac", "Ac", "Ac"), ("Tb", "K", "base T", "دمای پایه", "tyvi"),
                                             ("Tinf", "K", "fluid T", "سیال", "neste"))),
        ("tx_biot", "Biot number", "بیو", "Biot",
         "Bi = h*Lc/k", V(("Bi", "1", "Bi", "Bi", "Bi"), ("h", "W/(m^2*K)", "h", "h", "h"),
                          ("Lc", "m", "Lc", "Lc", "Lc"), ("k", "W/(m*K)", "k", "k", "k"))),
        ("tx_fourier_no", "Fourier number", "فوریه", "Fourier-luku",
         "Fo = alpha*t/Lc**2", V(("Fo", "1", "Fo", "Fo", "Fo"), ("alpha", "m^2/s", "alpha", "آلفا", "alpha"),
                                 ("t", "s", "t", "t", "t"), ("Lc", "m", "Lc", "Lc", "Lc"))),
        ("tx_rad_net", "Net radiation two gray", "تابش خالص", "Sateily",
         "q = sig*A*(T1**4 - T2**4)/(1/eps1 + 1/eps2 - 1)",
         V(("q", "W", "q", "q", "q"), ("sig", "W/(m^2*K^4)", "sigma", "سیگما", "sigma"),
           ("A", "m^2", "A", "A", "A"), ("T1", "K", "T1", "T1", "T1"), ("T2", "K", "T2", "T2", "T2"),
           ("eps1", "1", "eps1", "اپسیلون۱", "eps1"), ("eps2", "1", "eps2", "اپسیلون۲", "eps2"))),
    ]
    for it in heat:
        a(row(it[0], "eng.heatx", it[1], it[2], it[3], it[4], it[5]))

    pipe = [
        ("tx_manning", "Manning velocity", "مانینگ", "Manning",
         "v = (1/n)*Rh**(2/3)*S**0.5", V(("v", "m/s", "v", "v", "v"), ("n", "1", "n", "n", "n"),
                                         ("Rh", "m", "hydraulic radius", "شعاع هیدرولیکی", "hydraulinen sade"),
                                         ("S", "1", "slope", "شیب", "kaltevuus"))),
        ("tx_darcy_hf", "Darcy-Weisbach head", "دارسی-وایسباخ", "Darcy-Weisbach",
         "hf = f*L*v**2/(2*g*D)", V(("hf", "m", "head loss", "افت", "häviö"), ("f", "1", "f", "f", "f"),
                                    ("L", "m", "L", "L", "L"), ("v", "m/s", "v", "v", "v"),
                                    ("g", "m/s^2", "g", "g", "g"), ("D", "m", "D", "D", "D"))),
        ("tx_re_pipe", "Pipe Reynolds", "رینولدز لوله", "Reynoldsin luku",
         "Rey = rho*v*D/mu", V(("Rey", "1", "Re", "Re", "Re"), ("rho", "kg/m^3", "rho", "رو", "rho"),
                               ("v", "m/s", "v", "v", "v"), ("D", "m", "D", "D", "D"),
                               ("mu", "Pa*s", "mu", "گرانروی", "viskositeetti"))),
        ("tx_conti", "Continuity incompressible", "پیوستگی", "Jatkuvuus",
         "A1*v1 = A2*v2", V(("A1", "m^2", "A1", "A1", "A1"), ("v1", "m/s", "v1", "v1", "v1"),
                            ("A2", "m^2", "A2", "A2", "A2"), ("v2", "m/s", "v2", "v2", "v2"))),
        ("tx_orifice", "Orifice flow", "روزنه", "Kuristin",
         "Q = Cd*A*sqrt(2*g*h)", V(("Q", "m^3/s", "Q", "Q", "Q"), ("Cd", "1", "Cd", "Cd", "Cd"),
                                   ("A", "m^2", "A", "A", "A"), ("g", "m/s^2", "g", "g", "g"), ("h", "m", "h", "h", "h"))),
        ("tx_weir_rect", "Rectangular weir", "سرریز مستطیلی", "Suorakulmainen pato",
         "Q = Cd*(2/3)*sqrt(2*g)*b*H**1.5", V(("Q", "m^3/s", "Q", "Q", "Q"), ("Cd", "1", "Cd", "Cd", "Cd"),
                                              ("g", "m/s^2", "g", "g", "g"), ("b", "m", "width", "عرض", "leveys"),
                                              ("H", "m", "head", "بار آبی", "padotus"))),
        ("tx_pump_affinity_q", "Pump affinity Q", "مشابهت پمپ دبی", "Pumpun Q",
         "Q2 = Q1*(n2/n1)", V(("Q2", "m^3/s", "Q2", "Q2", "Q2"), ("Q1", "m^3/s", "Q1", "Q1", "Q1"),
                              ("n2", "1/s", "n2", "n2", "n2"), ("n1", "1/s", "n1", "n1", "n1"))),
        ("tx_pump_affinity_h", "Pump affinity H", "مشابهت پمپ هد", "Pumpun H",
         "H2 = H1*(n2/n1)**2", V(("H2", "m", "H2", "H2", "H2"), ("H1", "m", "H1", "H1", "H1"),
                                 ("n2", "1/s", "n2", "n2", "n2"), ("n1", "1/s", "n1", "n1", "n1"))),
        ("tx_pump_power", "Pump hydraulic power", "توان هیدرولیک پمپ", "Pumpun teho",
         "P = rho*g*Q*H/eta", V(("P", "W", "P", "P", "P"), ("rho", "kg/m^3", "rho", "رو", "rho"),
                                ("g", "m/s^2", "g", "g", "g"), ("Q", "m^3/s", "Q", "Q", "Q"),
                                ("H", "m", "H", "H", "H"), ("eta", "1", "efficiency", "بازده", "hyotysuhde"))),
        ("tx_hazen", "Hazen-Williams SI", "هیزن-ویلیامز", "Hazen-Williams",
         "v = 0.849*C*Rh**0.63*S**0.54", V(("v", "m/s", "v", "v", "v"), ("C", "1", "C", "C", "C"),
                                           ("Rh", "m", "Rh", "Rh", "Rh"), ("S", "1", "S", "S", "S"))),
    ]
    for it in pipe:
        a(row(it[0], "eng.pipe", it[1], it[2], it[3], it[4], it[5]))

    rf = [
        ("tx_friis", "Friis transmission", "فریس", "Friis",
         "Pr = Pt*Gt*Gr*lam**2/((4*pi*d)**2)",
         V(("Pr", "W", "received", "دریافتی", "vastaanotto"), ("Pt", "W", "transmit", "ارسال", "lahetys"),
           ("Gt", "1", "Gt", "Gt", "Gt"), ("Gr", "1", "Gr", "Gr", "Gr"),
           ("lam", "m", "wavelength", "طول موج", "aallonpituus"), ("d", "m", "distance", "فاصله", "etaisyys"))),
        ("tx_fspl", "Free-space path loss", "افت مسیر فضای آزاد", "Vapaan tilan vaimennus",
         "L = (4*pi*d/lam)**2",
         V(("L", "1", "L", "L", "L"), ("d", "m", "d", "d", "d"), ("lam", "m", "lambda", "لامبدا", "lambda"))),
        ("tx_antenna_G", "Antenna gain from directivity", "بهره آنتن", "Antennivahvistus",
         "G = eta*D",
         V(("G", "1", "G", "G", "G"), ("eta", "1", "efficiency", "بازده", "hyotysuhde"), ("D", "1", "directivity", "جهت‌مندی", "suuntaavuus"))),
        ("tx_dipole_R", "Short dipole radiation R approx", "مقاومت تابش دوقطبی کوتاه", "Dipolin R",
         "Rr = 20*pi**2*(dl/lam)**2",
         V(("Rr", "ohm", "Rr", "Rr", "Rr"), ("dl", "m", "length", "طول", "pituus"), ("lam", "m", "lambda", "لامبدا", "lambda"))),
        ("tx_parabolic_G", "Parabolic dish gain", "بهره بشقاب", "Lautasantenni",
         "G = eta*(pi*D/lam)**2",
         V(("G", "1", "G", "G", "G"), ("eta", "1", "aperture eff", "بازده دهانه", "aukko"),
           ("D", "m", "diameter", "قطر", "halkaisija"), ("lam", "m", "lambda", "لامبدا", "lambda"))),
        ("tx_beamwidth_dish", "Dish beamwidth approx", "پهنای پرتو بشقاب", "Keilan leveys",
         "th = 70*lam/D",
         V(("th", "deg", "HPBW", "پهنای نیم‌توان", "HPBW"), ("lam", "m", "lambda", "لامبدا", "lambda"),
           ("D", "m", "D", "D", "D"))),
        ("tx_erp", "ERP from power and gain", "ERP", "ERP",
         "erp = Pt*G",
         V(("erp", "W", "ERP", "ERP", "ERP"), ("Pt", "W", "Pt", "Pt", "Pt"), ("G", "1", "gain vs dipole", "بهره", "vahvistus"))),
        ("tx_vswr", "VSWR from |Gamma|", "VSWR", "VSWR",
         "s = (1 + g)/(1 - g)",
         V(("s", "1", "VSWR", "VSWR", "VSWR"), ("g", "1", "|Gamma|", "|گاما|", "|Gamma|"))),
        ("tx_gamma_z", "Reflection from Z", "ضریب بازتاب از Z", "Heijastus Z:sta",
         "g = (ZL - Z0)/(ZL + Z0)",
         V(("g", "1", "Gamma", "گاما", "Gamma"), ("ZL", "ohm", "ZL", "ZL", "ZL"), ("Z0", "ohm", "Z0", "Z0", "Z0"))),
        ("tx_return_loss", "Return loss", "افت برگشتی", "Paluuvaimennus",
         "RL = -20*log(g)/log(10)",
         V(("RL", "dB", "RL", "RL", "RL"), ("g", "1", "|Gamma|", "|گاما|", "|Gamma|"))),
    ]
    for it in rf:
        a(row(it[0], "eng.rf", it[1], it[2], it[3], it[4], it[5]))

    tl = [
        ("tx_z0_lossless", "Lossless Z0", "Z0 بی‌تلف", "Z0",
         "Z0 = sqrt(L/C)",
         V(("Z0", "ohm", "Z0", "Z0", "Z0"), ("L", "H/m", "L'", "L'", "L'"), ("C", "F/m", "C'", "C'", "C'"))),
        ("tx_vp_tl", "TL phase velocity", "سرعت فاز خط", "Vaihenopeus",
         "vp = 1/sqrt(L*C)",
         V(("vp", "m/s", "vp", "vp", "vp"), ("L", "H/m", "L'", "L'", "L'"), ("C", "F/m", "C'", "C'", "C'"))),
        ("tx_beta_tl", "TL phase constant", "ثابت فاز خط", "Vakiovaihe",
         "bet = w*sqrt(L*C)",
         V(("bet", "1/m", "beta", "بتا", "beta"), ("w", "rad/s", "omega", "امگا", "omega"),
           ("L", "H/m", "L'", "L'", "L'"), ("C", "F/m", "C'", "C'", "C'"))),
        ("tx_delay_tl", "Delay of a line", "تأخیر خط", "Viive",
         "td = Llen/vp",
         V(("td", "s", "delay", "تأخیر", "viive"), ("Llen", "m", "length", "طول", "pituus"),
           ("vp", "m/s", "vp", "vp", "vp"))),
        ("tx_quarterwave", "Quarter-wave transformer", "ترانسفورماتور ربع‌موج", "Neljannesaalto",
         "Z1 = sqrt(Z0*ZL)",
         V(("Z1", "ohm", "Z1", "Z1", "Z1"), ("Z0", "ohm", "Z0", "Z0", "Z0"), ("ZL", "ohm", "ZL", "ZL", "ZL"))),
        ("tx_coax_z0", "Coax Z0", "Z0 کواکسیال", "Koaksiaali Z0",
         "Z0 = 60*log(b/a)/sqrt(epsr)",
         V(("Z0", "ohm", "Z0", "Z0", "Z0"), ("b", "m", "outer", "بیرونی", "ulko"),
           ("a", "m", "inner", "درونی", "sisa"), ("epsr", "1", "eps_r", "اپسیلون نسبی", "eps_r"))),
        ("tx_microstrip_approx", "Microstrip Z0 wide", "میکرو استریپ پهن", "Mikroliuskajohto",
         "Z0 = 120*pi/(sqrt(epsr)*(w/h + 1.393))",
         V(("Z0", "ohm", "Z0", "Z0", "Z0"), ("epsr", "1", "eps_r", "اپسیلون", "eps"),
           ("w", "m", "width", "عرض", "leveys"), ("h", "m", "height", "ارتفاع", "korkeus"))),
        ("tx_attn_neper", "Attenuation Np to dB", "نپر به دسی‌بل", "Neper dB:ksi",
         "adb = 8.686*anp",
         V(("adb", "dB", "dB", "dB", "dB"), ("anp", "Np", "neper", "نپر", "neper"))),
    ]
    for it in tl:
        a(row(it[0], "eng.tl", it[1], it[2], it[3], it[4], it[5]))
    return R


def applied():
    R = []
    a = R.append
    med = [
        ("tx_bmi", "health.fit", "Body mass index", "شاخص توده بدنی", "BMI",
         "bmi = w/(h**2)",
         V(("bmi", "kg/m^2", "BMI", "BMI", "BMI"), ("w", "kg", "mass", "جرم", "massa"), ("h", "m", "height", "قد", "pituus"))),
        ("tx_bsa_mosteller", "health.fit", "Mosteller BSA", "سطح بدن موستلر", "Mosteller",
         "bsa = sqrt(h*w/3600)",
         V(("bsa", "m^2", "BSA", "BSA", "BSA"), ("h", "cm", "height cm", "قد cm", "pituus cm"),
           ("w", "kg", "mass", "جرم", "massa"))),
        ("tx_map", "med.cardio", "Mean arterial pressure", "فشار شریانی میانگین", "Keskivaltimopaine",
         "map_ = (2*dbp + sbp)/3",
         V(("map_", "mmHg", "MAP", "MAP", "MAP"), ("dbp", "mmHg", "diastolic", "دیاستول", "dia"),
           ("sbp", "mmHg", "systolic", "سیستول", "sys"))),
        ("tx_pp", "med.cardio", "Pulse pressure", "فشار نبض", "Pulssipaine",
         "pp = sbp - dbp",
         V(("pp", "mmHg", "PP", "PP", "PP"), ("sbp", "mmHg", "SBP", "سیستول", "sys"),
           ("dbp", "mmHg", "DBP", "دیاستول", "dia"))),
        ("tx_co_fick", "med.cardio", "Fick cardiac output", "برون‌ده فیک", "Fick",
         "CO = vo2/(Ca - Cv)",
         V(("CO", "L/min", "CO", "CO", "CO"), ("vo2", "mL/min", "VO2", "VO2", "VO2"),
           ("Ca", "mL/L", "CaO2", "CaO2", "CaO2"), ("Cv", "mL/L", "CvO2", "CvO2", "CvO2"))),
        ("tx_svr", "med.cardio", "Systemic vascular resistance", "مقاومت عروق سیستمیک", "SVR",
         "svr = 80*(map_ - cvp)/CO",
         V(("svr", "dyn", "SVR", "SVR", "SVR"), ("map_", "mmHg", "MAP", "MAP", "MAP"),
           ("cvp", "mmHg", "CVP", "CVP", "CVP"), ("CO", "L/min", "CO", "CO", "CO"))),
        ("tx_qtc_bazett", "med.cardio", "QTc Bazett", "QTc بازت", "QTc Bazett",
         "qtc = qt/sqrt(rr)",
         V(("qtc", "s", "QTc", "QTc", "QTc"), ("qt", "s", "QT", "QT", "QT"), ("rr", "s", "RR", "RR", "RR"))),
        ("tx_qtc_frid", "med.cardio", "QTc Fridericia", "QTc فریدریسیا", "QTc Fridericia",
         "qtc = qt/(rr**(1/3))",
         V(("qtc", "s", "QTc", "QTc", "QTc"), ("qt", "s", "QT", "QT", "QT"), ("rr", "s", "RR", "RR", "RR"))),
        ("tx_gfr_cg", "med.clinic", "Cockcroft-Gault male", "کاککرافت مرد", "Cockcroft-Gault",
         "gfr = (140 - age)*w/(72*scr)",
         V(("gfr", "mL/min", "CrCl", "CrCl", "CrCl"), ("age", "yr", "age", "سن", "ika"),
           ("w", "kg", "mass", "جرم", "massa"), ("scr", "mg/dL", "SCr", "کراتینین", "krea"))),
        ("tx_anion", "med.clinic", "Anion gap", "گپ آنیونی", "Anionivaje",
         "ag = na - (cl + hco3)",
         V(("ag", "mmol/L", "AG", "AG", "AG"), ("na", "mmol/L", "Na", "سدیم", "Na"),
           ("cl", "mmol/L", "Cl", "کلر", "Cl"), ("hco3", "mmol/L", "HCO3", "بی‌کربنات", "HCO3"))),
        ("tx_osm", "med.clinic", "Calculated osmolarity", "اسمولاریته محاسبه‌ای", "Osmolaarisuus",
         "osm = 2*na + glu/18 + bun/2.8",
         V(("osm", "mOsm/L", "osm", "اسمول", "osm"), ("na", "mmol/L", "Na", "سدیم", "Na"),
           ("glu", "mg/dL", "glucose", "قند", "glukoosi"), ("bun", "mg/dL", "BUN", "BUN", "BUN"))),
        ("tx_aa_grad", "med.clinic", "A-a gradient room air approx", "گرادیان A-a", "A-a-gradientti",
         "aa = PAO2 - PaO2",
         V(("aa", "mmHg", "A-a", "A-a", "A-a"), ("PAO2", "mmHg", "PAO2", "PAO2", "PAO2"),
           ("PaO2", "mmHg", "PaO2", "PaO2", "PaO2"))),
        ("tx_alveolar", "med.clinic", "Alveolar gas PAO2", "گاز آلوئولی", "Alveolikaasu",
         "PAO2 = fio2*(Patm - 47) - PaCO2/0.8",
         V(("PAO2", "mmHg", "PAO2", "PAO2", "PAO2"), ("fio2", "1", "FiO2", "FiO2", "FiO2"),
           ("Patm", "mmHg", "Patm", "Patm", "Patm"), ("PaCO2", "mmHg", "PaCO2", "PaCO2", "PaCO2"))),
        ("tx_pk_vd", "med.pk", "Volume of distribution", "حجم توزیع", "Jakautumistilavuus",
         "Vd = dose/C0",
         V(("Vd", "L", "Vd", "Vd", "Vd"), ("dose", "mg", "dose", "دوز", "annos"), ("C0", "mg/L", "C0", "C0", "C0"))),
        ("tx_pk_cl", "med.pk", "Clearance from k and Vd", "کلیرانس", "Puhdistuma",
         "CL = k*Vd",
         V(("CL", "L/h", "CL", "CL", "CL"), ("k", "1/h", "k", "k", "k"), ("Vd", "L", "Vd", "Vd", "Vd"))),
        ("tx_pk_th", "med.pk", "Half-life from k", "نیمه‌عمر از k", "Puoliintumisaika",
         "th = log(2)/k",
         V(("th", "h", "t1/2", "t1/2", "t1/2"), ("k", "1/h", "k", "k", "k"))),
        ("tx_pk_css", "med.pk", "Infusion Css", "Css انفوزیون", "Css",
         "Css = R0/CL",
         V(("Css", "mg/L", "Css", "Css", "Css"), ("R0", "mg/h", "infusion rate", "آهنگ انفوزیون", "infuusio"),
           ("CL", "L/h", "CL", "CL", "CL"))),
        ("tx_pk_F", "med.pk", "Bioavailability", "زیست‌دسترسی", "Biologinen hyotyosuus",
         "F = (AUCev/AUCiv)*(DOSEiv/DOSEev)",
         V(("F", "1", "F", "F", "F"), ("AUCev", "mg*h/L", "AUC ev", "AUC غیروریدی", "AUC ev"),
           ("AUCiv", "mg*h/L", "AUC iv", "AUC وریدی", "AUC iv"),
           ("DOSEiv", "mg", "iv dose", "دوز وریدی", "iv"), ("DOSEev", "mg", "ev dose", "دوز غیروریدی", "ev"))),
        ("tx_mm_rate", "bio.enzyme", "Michaelis-Menten", "میکائلیس-منتن", "Michaelis-Menten",
         "v = Vmax*s/(Km + s)",
         V(("v", "1/s", "rate", "آهنگ", "nopeus"), ("Vmax", "1/s", "Vmax", "Vmax", "Vmax"),
           ("s", "mol/L", "[S]", "[S]", "[S]"), ("Km", "mol/L", "Km", "Km", "Km"))),
        ("tx_lb_y", "bio.enzyme", "Lineweaver-Burk y", "لاین‌ویور-برک", "Lineweaver-Burk",
         "invv = 1/Vmax + (Km/Vmax)*invs",
         V(("invv", "s", "1/v", "1/v", "1/v"), ("Vmax", "1/s", "Vmax", "Vmax", "Vmax"),
           ("Km", "mol/L", "Km", "Km", "Km"), ("invs", "L/mol", "1/[S]", "1/[S]", "1/[S]"))),
        ("tx_hw_p", "bio.genetics", "Hardy-Weinberg p^2", "هاردی-واینبرگ", "Hardy-Weinberg",
         "p2 = p**2",
         V(("p2", "1", "AA freq", "فراوانی AA", "AA"), ("p", "1", "allele p", "آلل p", "alleeli p"))),
        ("tx_hw_2pq", "bio.genetics", "Hardy-Weinberg 2pq", "هاردی-واینبرگ هتروزیگوت", "2pq",
         "h = 2*p*(1 - p)",
         V(("h", "1", "Aa freq", "فراوانی Aa", "Aa"), ("p", "1", "p", "p", "p"))),
        ("tx_logistic_pop", "bio.ecology", "Logistic dN/dt max", "رشد لجستیک بیشینه", "Logistinen max",
         "dN = r*K/4",
         V(("dN", "1/yr", "max dN/dt", "حداکثر رشد", "max kasvu"), ("r", "1/yr", "r", "r", "r"),
           ("K", "1", "K", "K", "K"))),
        ("tx_allometric", "bio.physio", "Allometric Y=a M^b", "آلومتریک", "Allometria",
         "Y = a0*M**b",
         V(("Y", "1", "Y", "Y", "Y"), ("a0", "1", "a", "a", "a"), ("M", "kg", "mass", "جرم", "massa"),
           ("b", "1", "exponent", "توان", "eksponentti"))),
        ("tx_nernst_neuron", "bio.neuro", "Nernst 61 mV", "نرنست نورون", "Nernst hermo",
         "Eion = (61/z)*log(Cout/Cin)/log(10)",
         V(("Eion", "mV", "E", "E", "E"), ("z", "1", "charge", "بار", "varaus"),
           ("Cout", "mmol/L", "out", "بیرون", "ulko"), ("Cin", "mmol/L", "in conc", "درون", "sisa"))),
        ("tx_goldman_kna", "bio.neuro", "Goldman K/Na piece", "گلدمن", "Goldman",
         "V = 61*log((Pk*Ko + Pna*Nao)/(Pk*Ki + Pna*Nai))/log(10)",
         V(("V", "mV", "Vm", "Vm", "Vm"), ("Pk", "1", "Pk", "Pk", "Pk"), ("Ko", "mmol/L", "Ko", "Ko", "Ko"),
           ("Pna", "1", "PNa", "PNa", "PNa"), ("Nao", "mmol/L", "Nao", "Nao", "Nao"),
           ("Ki", "mmol/L", "Ki", "Ki", "Ki"), ("Nai", "mmol/L", "Nai", "Nai", "Nai"))),
    ]
    for it in med:
        a(row(*it))

    fin = [
        ("tx_npv1", "fin.invest", "NPV one cash flow", "NPV یک جریان", "NPV",
         "NPV = -C0 + C1/(1 + r)",
         V(("NPV", "1", "NPV", "NPV", "NPV"), ("C0", "1", "C0", "C0", "C0"),
           ("C1", "1", "C1", "C1", "C1"), ("r", "1", "r", "r", "r"))),
        ("tx_gordon", "fin.invest", "Gordon growth", "گوردون", "Gordon",
         "P = D1/(k - g)",
         V(("P", "1", "price", "قیمت", "hinta"), ("D1", "1", "next dividend", "سود بعدی", "osinko"),
           ("k", "1", "required return", "بازده لازم", "tuotto"), ("g", "1", "growth", "رشد", "kasvu"))),
        ("tx_duration_mac", "fin.invest", "Macaulay duration one coupon approx", "دیرش مکالی", "Macaulay",
         "D = (1 + y)/y - (1 + y + T*(c - y))/(c*((1 + y)**T - 1) + y)",
         V(("D", "yr", "duration", "دیرش", "duraatio"), ("y", "1", "yield", "بازده", "tuotto"),
           ("T", "yr", "maturity", "سررسید", "erapaiva"), ("c", "1", "coupon rate", "کوپن", "kuponki"))),
        ("tx_mod_dur", "fin.invest", "Modified duration", "دیرش اصلاح‌شده", "Modifioitu duraatio",
         "Dmod = D/(1 + y)",
         V(("Dmod", "yr", "mod duration", "دیرش اصلاح", "mod. duraatio"), ("D", "yr", "Macaulay", "مکالی", "Macaulay"),
           ("y", "1", "yield", "بازده", "tuotto"))),
        ("tx_bond_approx", "fin.invest", "Bond % change from duration", "تغییر قیمت اوراق", "Joukkovelan muutos",
         "dp = -Dmod*dy*100",
         V(("dp", "1", "percent dP", "درصد تغییر", "% muutos"), ("Dmod", "yr", "mod duration", "دیرش", "duraatio"),
           ("dy", "1", "dy", "dy", "dy"))),
        ("tx_pcp", "fin.invest", "Put-call parity", "برابری اختیار", "Put-call",
         "c + K/(1 + r)**T = p + S",
         V(("c", "1", "call", "کال", "call"), ("K", "1", "strike", "اعمال", "toteutus"),
           ("r", "1", "rate", "نرخ", "korko"), ("T", "yr", "T", "T", "T"),
           ("p", "1", "put", "پوت", "put"), ("S", "1", "spot", "نقد", "spot"))),
        ("tx_bs_d1", "fin.invest", "Black-Scholes d1", "بلک-شولز d1", "Black-Scholes d1",
         "d1 = (log(S/K) + (r + sig**2/2)*T)/(sig*sqrt(T))",
         V(("d1", "1", "d1", "d1", "d1"), ("S", "1", "S", "S", "S"), ("K", "1", "K", "K", "K"),
           ("r", "1", "r", "r", "r"), ("sig", "1", "sigma", "سیگما", "sigma"), ("T", "yr", "T", "T", "T"))),
        ("tx_wacc", "fin.invest", "WACC two sources", "WACC", "WACC",
         "wacc = E/(E + D)*ke + D/(E + D)*kd*(1 - tc)",
         V(("wacc", "1", "WACC", "WACC", "WACC"), ("E", "1", "equity", "حقوق", "oma"),
           ("D", "1", "debt", "بدهی", "velka"), ("ke", "1", "ke", "ke", "ke"),
           ("kd", "1", "kd", "kd", "kd"), ("tc", "1", "tax", "مالیات", "vero"))),
        ("tx_capm_erp", "fin.invest", "CAPM expected", "CAPM", "CAPM",
         "er = rfr + bet*(rm - rfr)",
         V(("er", "1", "E[r]", "E[r]", "E[r]"), ("rfr", "1", "rf", "بدون ریسک", "rf"),
           ("bet", "1", "beta", "بتا", "beta"), ("rm", "1", "market", "بازار", "markkina"))),
        ("tx_elasticity", "econ.micro", "Price elasticity", "کشش قیمت", "Hintajousto",
         "e = (dq/q)/(dp/p)",
         V(("e", "1", "elasticity", "کشش", "jousto"), ("dq", "1", "dq", "dq", "dq"),
           ("q", "1", "q", "q", "q"), ("dp", "1", "dp", "dp", "dp"), ("p", "1", "p", "p", "p"))),
        ("tx_cobb", "econ.micro", "Cobb-Douglas Y", "کاب-داگلاس", "Cobb-Douglas",
         "Y = A0*K**a*Llab**b",
         V(("Y", "1", "Y", "Y", "Y"), ("A0", "1", "A", "A", "A"), ("K", "1", "K", "K", "K"),
           ("a", "1", "alpha", "آلفا", "alpha"), ("Llab", "1", "labor", "کار", "tyo"), ("b", "1", "beta", "بتا", "beta"))),
        ("tx_fisher", "econ.macro", "Fisher equation", "فیشر", "Fisher",
         "i = r + pi_e",
         V(("i", "1", "nominal", "اسمی", "nimellinen"), ("r", "1", "real", "واقعی", "reaalinen"),
           ("pi_e", "1", "expected inflation", "تورم انتظاری", "odotusinflaatio"))),
        ("tx_qty_money", "econ.macro", "Quantity theory", "نظریه مقداری پول", "Rahamaara",
         "M*Vmon = P*Y",
         V(("M", "1", "money", "پول", "raha"), ("Vmon", "1", "velocity", "گردش", "kiertonopeus"),
           ("P", "1", "price", "قیمت", "hinta"), ("Y", "1", "output", "تولید", "tuotos"))),
        ("tx_gdp_exp", "econ.macro", "GDP expenditure", "GDP هزینه‌ای", "BKT",
         "Y = C + Iinv + G + NX",
         V(("Y", "1", "Y", "Y", "Y"), ("C", "1", "C", "مصرف", "kulutus"), ("Iinv", "1", "I", "سرمایه‌گذاری", "invest"),
           ("G", "1", "G", "دولت", "julkinen"), ("NX", "1", "NX", "خالص صادرات", "nettovienti"))),
        ("tx_sl_book", "fin.invest", "Straight-line book", "دفتر خط مستقیم", "Tasaerapoisto",
         "B = cost - D*t",
         V(("B", "1", "book", "دفتر", "kirja"), ("cost", "1", "cost", "بهای تمام‌شده", "hankinta"),
           ("D", "1", "annual dep", "استهلاک سالانه", "poisto"), ("t", "yr", "years", "سال", "vuodet"))),
        ("tx_annuity_pv", "fin.interest", "Ordinary annuity PV", "ارزش فعلی اقساط", "Annuiteetin NA",
         "PV = PMT*(1 - (1 + r)**(-n))/r",
         V(("PV", "1", "PV", "PV", "PV"), ("PMT", "1", "payment", "قسط", "era"),
           ("r", "1", "rate", "نرخ", "korko"), ("n", "1", "n", "n", "n"))),
        ("tx_annuity_fv", "fin.interest", "Ordinary annuity FV", "ارزش آتی اقساط", "Annuiteetin TA",
         "FV = PMT*((1 + r)**n - 1)/r",
         V(("FV", "1", "FV", "FV", "FV"), ("PMT", "1", "payment", "قسط", "era"),
           ("r", "1", "rate", "نرخ", "korko"), ("n", "1", "n", "n", "n"))),
        ("tx_pmt_loan", "fin.interest", "Loan payment", "قسط وام", "Lainan era",
         "PMT = PV*r/(1 - (1 + r)**(-n))",
         V(("PMT", "1", "PMT", "قسط", "era"), ("PV", "1", "principal", "اصل", "paaoma"),
           ("r", "1", "rate", "نرخ", "korko"), ("n", "1", "n", "n", "n"))),
    ]
    for it in fin:
        a(row(*it))

    earth = [
        ("tx_rational", "geo.hydro", "Rational runoff", "رواناب عقلی", "Rationaalinen",
         "Q = C*i*A",
         V(("Q", "m^3/s", "Q", "Q", "Q"), ("C", "1", "C", "C", "C"),
           ("i", "m/s", "intensity", "شدت", "intensiteetti"), ("A", "m^2", "area", "مساحت", "pinta"))),
        ("tx_scs_cn", "geo.hydro", "SCS potential S from CN", "SCS از CN", "SCS",
         "S = 25400/CN - 254",
         V(("S", "mm", "S", "S", "S"), ("CN", "1", "curve number", "شماره منحنی", "CN"))),
        ("tx_scs_q", "geo.hydro", "SCS runoff", "رواناب SCS", "SCS valunta",
         "Q = (P - 0.2*S)**2/(P + 0.8*S)",
         V(("Q", "mm", "runoff", "رواناب", "valunta"), ("P", "mm", "rain", "باران", "sade"),
           ("S", "mm", "S", "S", "S"))),
        ("tx_darcy", "geo.hydro", "Darcy law", "دارسی", "Darcy",
         "q = -K*dh",
         V(("q", "m/s", "specific discharge", "دبی ویژه", "vuo"), ("K", "m/s", "K", "K", "K"),
           ("dh", "1", "head gradient", "گرادیان بار", "gradientti"))),
        ("tx_hypsometric", "geo.earth", "Hypsometric thickness", "هیپسومتریک", "Hypsometrinen",
         "dz = (Rgas*T/g)*log(p1/p2)",
         V(("dz", "m", "thickness", "ضخامت", "paksuus"), ("Rgas", "J/(kg*K)", "R", "R", "R"),
           ("T", "K", "T", "T", "T"), ("g", "m/s^2", "g", "g", "g"),
           ("p1", "Pa", "p1", "p1", "p1"), ("p2", "Pa", "p2", "p2", "p2"))),
        ("tx_lapse", "meteo.air", "Dry adiabatic lapse", "گرادیان بی‌دررو خشک", "Kuiva adiabaatti",
         "G = g/cp",
         V(("G", "K/m", "lapse", "گرادیان", "gradientti"), ("g", "m/s^2", "g", "g", "g"),
           ("cp", "J/(kg*K)", "cp", "cp", "cp"))),
        ("tx_void", "geo.rock", "Void ratio", "نسبت تخلخل", "Tyhjayssuhde",
         "e = n/(1 - n)",
         V(("e", "1", "e", "e", "e"), ("n", "1", "porosity", "تخلخل", "huokoisuus"))),
        ("tx_porosity", "geo.rock", "Porosity from void", "تخلخل از نسبت خلل", "Huokoisuus",
         "n = e/(1 + e)",
         V(("n", "1", "n", "n", "n"), ("e", "1", "e", "e", "e"))),
        ("tx_sr", "geo.rock", "Degree of saturation", "درجه اشباع", "Kyllastysaste",
         "Sr = w*Gs/e",
         V(("Sr", "1", "Sr", "Sr", "Sr"), ("w", "1", "water content", "رطوبت", "vesipitoisuus"),
           ("Gs", "1", "Gs", "Gs", "Gs"), ("e", "1", "e", "e", "e"))),
        ("tx_terzaghi", "geo.rock", "Terzaghi bearing strip", "ظرفیت باربری ترزاقی", "Terzaghi",
         "qult = c*Nc + q*Nq + 0.5*gamw*B*Ngam",
         V(("qult", "Pa", "qult", "qult", "qult"), ("c", "Pa", "c", "c", "c"),
           ("Nc", "1", "Nc", "Nc", "Nc"), ("q", "Pa", "overburden", "سربار", "kuorma"),
           ("Nq", "1", "Nq", "Nq", "Nq"), ("gamw", "N/m^3", "gamma", "گاما", "gamma"),
           ("B", "m", "width", "عرض", "leveys"), ("Ngam", "1", "Ngamma", "Ngamma", "Ngamma"))),
        ("tx_stokes_set", "env.water", "Stokes settling", "ته‌نشینی استوکس", "Stokes laskeutuminen",
         "v = 2*r**2*(rho - rhof)*g/(9*eta)",
         V(("v", "m/s", "v", "v", "v"), ("r", "m", "r", "r", "r"),
           ("rho", "kg/m^3", "particle", "ذره", "hiukkanen"), ("rhof", "kg/m^3", "fluid", "سیال", "neste"),
           ("g", "m/s^2", "g", "g", "g"), ("eta", "Pa*s", "viscosity", "گرانروی", "viskositeetti"))),
        ("tx_bod", "env.water", "BOD remaining", "BOD باقی", "BOD",
         "L = L0*exp(-k*t)",
         V(("L", "mg/L", "L", "L", "L"), ("L0", "mg/L", "L0", "L0", "L0"),
           ("k", "1/d", "k", "k", "k"), ("t", "d", "t", "t", "t"))),
        ("tx_chezy", "geo.hydro", "Chezy velocity", "شزی", "Chezy",
         "v = C*sqrt(Rh*S)",
         V(("v", "m/s", "v", "v", "v"), ("C", "m^0.5/s", "C", "C", "C"),
           ("Rh", "m", "Rh", "Rh", "Rh"), ("S", "1", "S", "S", "S"))),
        ("tx_kepler3", "physics.astro", "Kepler 3 for two planets", "کپلر ۳", "Kepler 3",
         "T2 = T1*(a2/a1)**1.5",
         V(("T2", "s", "T2", "T2", "T2"), ("T1", "s", "T1", "T1", "T1"),
           ("a2", "m", "a2", "a2", "a2"), ("a1", "m", "a1", "a1", "a1"))),
        ("tx_hubble", "physics.astro", "Hubble v=H d", "هابل", "Hubble",
         "v = H0*d",
         V(("v", "m/s", "recession", "دور شدن", "loittoneminen"), ("H0", "1/s", "H0", "H0", "H0"),
           ("d", "m", "distance", "فاصله", "etaisyys"))),
        ("tx_mag_dist", "physics.astro", "Distance modulus", "مدول فاصله", "Etaisyysmoduli",
         "d = 10**((m - M + 5)/5)",
         V(("d", "pc", "d", "d", "d"), ("m", "1", "apparent", "ظاهری", "näennainen"),
           ("M", "1", "absolute", "مطلق", "absoluuttinen"))),
        ("tx_schwarz", "physics.astro", "Schwarzschild radius", "شوارتسشیلد", "Schwarzschild",
         "rs = 2*G*M/c**2",
         V(("rs", "m", "rs", "rs", "rs"), ("G", "m^3/(kg*s^2)", "G", "G", "G"),
           ("M", "kg", "M", "M", "M"), ("c", "m/s", "c", "c", "c"))),
    ]
    for it in earth:
        a(row(*it))

    daily = [
        ("tx_mpg", "daily.util", "Fuel L/100km from km/L", "مصرف از کیلومتر بر لیتر", "Kulutus",
         "c = 100/kpl",
         V(("c", "L/100km", "L/100km", "لیتر در ۱۰۰", "L/100km"), ("kpl", "km/L", "km per L", "کیلومتر بر لیتر", "km/L"))),
        ("tx_mix_paint", "daily.util", "Paint mix parts", "مخلوط رنگ", "Maaliseos",
         "b = a*rto",
         V(("b", "L", "part B", "جزء B", "osa B"), ("a", "L", "part A", "جزء A", "osa A"),
           ("rto", "1", "ratio B/A", "نسبت", "suhde"))),
        ("tx_scale_map", "daily.util", "Map scale distance", "مقیاس نقشه", "Kartta-asteikko",
         "real = mapd*s",
         V(("real", "m", "ground", "زمین", "maasto"), ("mapd", "m", "on map", "روی نقشه", "kartalla"),
           ("s", "1", "scale 1:s use s", "مقیاس", "mittakaava"))),
        ("tx_eqtemp", "music.acoust", "Equal temperament", "فواصل مساوی", "Tasa temperamentti",
         "f = 440*2**((n - 69)/12)",
         V(("f", "Hz", "frequency", "بسامد", "taajuus"), ("n", "1", "MIDI note", "نت MIDI", "MIDI"))),
        ("tx_ev_photo", "photo.exp", "Exposure value", "مقدار نوردهی", "EV",
         "EV = log(N**2/t)/log(2)",
         V(("EV", "1", "EV", "EV", "EV"), ("N", "1", "f-number", "دیافراگم", "aukko"),
           ("t", "s", "shutter", "شاتر", "suljin"))),
        ("tx_raid5", "cs.net", "RAID5 usable", "ظرفیت RAID5", "RAID5",
         "U = (n - 1)*d",
         V(("U", "1", "usable", "قابل استفاده", "kaytettava"), ("n", "1", "disks", "دیسک", "levyt"),
           ("d", "1", "disk size", "اندازه دیسک", "levyn koko"))),
        ("tx_amdahl", "cs.info", "Amdahl speedup", "آمدال", "Amdahl",
         "S = 1/((1 - p) + p/n)",
         V(("S", "1", "speedup", "شتاب", "nopeutus"), ("p", "1", "parallel fraction", "سهم موازی", "rinnakkais"),
           ("n", "1", "processors", "پردازنده", "suorittimet"))),
        ("tx_little_cs", "cs.info", "Little's law jobs", "لیتل کارها", "Little tyot",
         "L = lam*W",
         V(("L", "1", "jobs", "کار", "tyot"), ("lam", "1/s", "arrival", "ورود", "saapuminen"),
           ("W", "s", "latency", "تأخیر", "viive"))),
        ("tx_cache_amat", "cs.info", "AMAT", "زمان میانگین حافظه", "AMAT",
         "t = thit + m*tmiss",
         V(("t", "s", "AMAT", "AMAT", "AMAT"), ("thit", "s", "hit time", "زمان اصابت", "osuma"),
           ("m", "1", "miss rate", "نرخ ازدست", "huti"), ("tmiss", "s", "miss penalty", "جریمه ازدست", "huti"))),
        ("tx_yield_die", "eng.manuf", "Die yield simple", "بازده ویفر", "Sirusaanto",
         "Y = exp(-A*D)",
         V(("Y", "1", "yield", "بازده", "saanto"), ("A", "m^2", "die area", "مساحت دای", "pinta"),
           ("D", "1/m^2", "defect density", "چگالی نقص", "viat"))),
        ("tx_ohms_thermal", "eng.heat", "Thermal resistance", "مقاومت گرمایی", "Lampovastus",
         "dT = q*Rth",
         V(("dT", "K", "delta T", "دلتا تی", "dT"), ("q", "W", "q", "q", "q"),
           ("Rth", "K/W", "Rth", "Rth", "Rth"))),
        ("tx_pv_cell", "eng.power", "PV power", "توان فتوولتائیک", "Aurinkokenno",
         "P = eta*G*A",
         V(("P", "W", "P", "P", "P"), ("eta", "1", "efficiency", "بازده", "hyotysuhde"),
           ("G", "W/m^2", "irradiance", "تابش", "sateily"), ("A", "m^2", "area", "مساحت", "pinta"))),
        ("tx_carnot_cop_c", "physics.thermo", "Carnot refrigerator COP", "COP یخچال کارنو", "Carnot COP",
         "COP = Tc/(Th - Tc)",
         V(("COP", "1", "COP", "COP", "COP"), ("Tc", "K", "cold", "سرد", "kylma"),
           ("Th", "K", "hot", "گرم", "kuuma"))),
        ("tx_wind_p", "eng.power", "Wind turbine power", "توان توربین بادی", "Tuulivoima",
         "P = 0.5*rho*A*v**3*cp",
         V(("P", "W", "P", "P", "P"), ("rho", "kg/m^3", "air density", "چگالی هوا", "tiheys"),
           ("A", "m^2", "swept area", "سطح جاروب", "pinta"), ("v", "m/s", "wind", "باد", "tuuli"),
           ("cp", "1", "power coeff", "ضریب توان", "tehokerroin"))),
        ("tx_orifice_gas", "eng.chem", "Orifice mass from Cd", "دبی روزنه", "Kuristin massa",
         "m = Cd*A*sqrt(2*rho*dP)",
         V(("m", "kg/s", "mass flow", "دبی جرمی", "massa"), ("Cd", "1", "Cd", "Cd", "Cd"),
           ("A", "m^2", "A", "A", "A"), ("rho", "kg/m^3", "rho", "رو", "rho"), ("dP", "Pa", "dP", "dP", "dP"))),
        ("tx_ntu_eps_counter", "eng.heatx", "Counterflow eps C=1", "اثربخشی ناهمسو C=1", "Vastavirta eps",
         "eps = N/(N + 1)",
         V(("eps", "1", "effectiveness", "اثربخشی", "tehokkuus"), ("N", "1", "NTU", "NTU", "NTU"))),
    ]
    for it in daily:
        a(row(*it))
    return R
