"""Web UI strings. Separate copy from the desktop i18n module."""

UI = {
    "en": {
        "title": "Ultra Calculator",
        "calc": "Calculator",
        "formulas": "Formulas",
        "poly": "Polynomial",
        "numeric": "Numerical",
        "search": "Search",
        "solve": "Solve",
        "unknown": "Unknown",
        "single": "One unknown",
        "system": "Several equations",
        "add": "Add equation",
        "remove": "Remove equation",
        "result": "Result",
        "deg": "DEG",
        "rad": "RAD",
        "eng": "ENG",
        "evaluate": "Evaluate",
        "roots": "Roots",
        "run": "Run",
        "root": "Root",
        "integral": "Integral",
        "deriv": "Derivative",
        "ode": "ODE",
        "history": "History",
        "ready": "Ready",
        "pick": "Pick a formula.",
        "lang": "Language",
        "chem": "Chemistry",
        "elements": "Elements",
        "balance": "Balance",
        "molar": "Molar mass",
        "atomic_n": "Z",
        "atomic_m": "Mass",
        "isotopes": "Isotopes",
        "sources": "Sources",
        "lookup": "Lookup",
        "lookup_hint": "H2O, Fe, Fe-56, R, g",
        "insert": "Insert",
        "lookup_need_field": "Click the field you want, then insert.",
        "kbd_hint": "Type in the screen. Enter calculates. Esc clears. Alt+1 to Alt+7 switch pages. Alt+L or / opens lookup. You do not have to use the mouse.",
    },
    "fa": {
        "title": "ماشین حساب اولترا",
        "calc": "ماشین حساب",
        "formulas": "فرمول ها",
        "poly": "چندجمله ای",
        "numeric": "عددی",
        "search": "جستجو",
        "solve": "حل",
        "unknown": "مجهول",
        "single": "یک مجهول",
        "system": "چند معادله",
        "add": "افزودن معادله",
        "remove": "حذف معادله",
        "result": "نتیجه",
        "deg": "درجه",
        "rad": "رادیان",
        "eng": "مهندسی",
        "evaluate": "مقدار",
        "roots": "ریشه ها",
        "run": "اجرا",
        "root": "ریشه",
        "integral": "انتگرال",
        "deriv": "مشتق",
        "ode": "دیفرانسیل",
        "history": "تاریخچه",
        "ready": "آماده",
        "pick": "یک فرمول انتخاب کن.",
        "lang": "زبان",
        "chem": "شیمی",
        "elements": "عنصرها",
        "balance": "موازنه",
        "molar": "جرم مولی",
        "atomic_n": "Z",
        "atomic_m": "جرم",
        "isotopes": "ایزوتوپ",
        "sources": "منبع ها",
        "lookup": "جستجوی سریع",
        "lookup_hint": "H2O, Fe, Fe-56, R, g",
        "insert": "بگذار",
        "lookup_need_field": "اول خانه را انتخاب کن، بعد بگذار.",
        "kbd_hint": "توی صفحه تایپ کن. Enter حساب می‌کند. Esc پاک می‌کند. Alt+1 تا Alt+7 صفحه را عوض می‌کند. Alt+L یا / جستجوی سریع است. لازم نیست با موس بنویسی.",
    },
    "fi": {
        "title": "Ultra-laskin",
        "calc": "Laskin",
        "formulas": "Kaavat",
        "poly": "Polynomi",
        "numeric": "Numeerinen",
        "search": "Haku",
        "solve": "Ratkaise",
        "unknown": "Tuntematon",
        "single": "Yksi tuntematon",
        "system": "Useita yhtaloita",
        "add": "Lisaa yhtalo",
        "remove": "Poista yhtalo",
        "result": "Tulos",
        "deg": "ASTE",
        "rad": "RAD",
        "eng": "ENG",
        "evaluate": "Laske",
        "roots": "Juuret",
        "run": "Suorita",
        "root": "Juuri",
        "integral": "Integraali",
        "deriv": "Derivaatta",
        "ode": "DY",
        "history": "Historia",
        "ready": "Valmis",
        "pick": "Valitse kaava.",
        "lang": "Kieli",
        "chem": "Kemia",
        "elements": "Alkuaineet",
        "balance": "Tasapainota",
        "molar": "Moolimassa",
        "atomic_n": "Z",
        "atomic_m": "Massa",
        "isotopes": "Isotoopit",
        "sources": "Lahteet",
        "lookup": "Haku",
        "lookup_hint": "H2O, Fe, Fe-56, R, g",
        "insert": "Lisaa",
        "lookup_need_field": "Napsauta kenttaa, sitten Lisaa.",
        "kbd_hint": "Kirjoita nayttoon. Enter laskee. Esc tyhjentaa. Alt+1–7 vaihtaa sivua. Alt+L tai / avaa haun. Hiirta ei tarvita.",
    },
}


def ui_text(lang, key):
    pack = UI.get(lang) or UI["en"]
    return pack.get(key) or UI["en"].get(key, key)
