"""Web UI strings. Separate copy from the desktop i18n module."""

UI = {
    "en": {
        "title": "Ultra Calculator",
        "calc": "Calculator",
        "formulas": "Formulas",
        "poly": "Polynomial",
        "numeric": "Numerical",
        "algo": "Algorithms",
        "pick_algo": "Pick an algorithm.",
        "algo_hint": "Fill the fields and press Enter. Matrices: 1, 2; 3, 4. Lists: 1, 2, 3.",
        "search": "Search",
        "categories": "Categories",
        "all": "All",
        "solve": "Solve",
        "unknown": "Unknown",
        "single": "One unknown",
        "system": "Several equations",
        "add": "Add equation",
        "remove": "Remove equation",
        "result": "Result",
        "deg": "DEG",
        "rad": "RAD",
        "eng": "ENG",
        "evaluate": "Evaluate",
        "roots": "Roots",
        "run": "Run",
        "root": "Root",
        "integral": "Integral",
        "deriv": "Derivative",
        "ode": "ODE",
        "history": "History",
        "ready": "Ready",
        "pick": "Pick a formula.",
        "lang": "Language",
        "chem": "Chemistry",
        "elements": "Elements",
        "balance": "Balance",
        "molar": "Molar mass",
        "atomic_n": "Z",
        "atomic_m": "Mass",
        "isotopes": "Isotopes",
        "sources": "Sources",
        "lookup": "Lookup",
        "lookup_hint": "H2O, Fe, Fe-56, R, g",
        "insert": "Insert",
        "lookup_need_field": "Click the field you want, then insert.",
        "kbd_hint": "Type in the screen. Enter calculates. Esc clears. Alt+1 to Alt+9 switch pages. Alt+0 is Circuits. You can type summation(k,k,1,100), diff(x**3,x), integrate(x**2,x,0,1).",
        "problems": "Problems",
        "inverse": "Inverse",
        "at_value": "at",
        "problem_hint": "Type an equation (2*x+3=11) or paste a textbook word problem (two charges, where E is zero, Ohm, motion). Solve. Inverse is for functions. Matrices: 1, 2; 3, 4.",
        "circuits": "Circuits",
        "circuit_freq": "f (Hz)",
        "circuit_hint": "Type a netlist (node 0 is ground): V1 1 0 12 / R1 1 2 1k / R2 2 0 2k. Or shortcuts: series 1k 2k, parallel 1k 1k, divider 12 1k 2k, V=12 R=1k. AC: fill f or write .ac 50. Unknown: R2 2 0 ? and .eq V(2)=4 then Inverse. Thevenin: .thevenin 2 0. Controlled: E/G  n+ n- nc+ nc- gain. Diode D1 1 0. BJT Q1 c b e npn. MOSFET M1 d g s nmos. Transient: .tran 1u 2m.",
        "graph": "Graph",
        "matrix": "Matrix",
        "stats": "Stats",
        "triangle": "Triangle",
        "plot": "Plot",
        "bode": "Bode",
        "parametric": "Parametric",
        "data": "Data",
        "xmin": "xmin",
        "xmax": "xmax",
        "save": "Save",
        "load": "Load",
        "latex": "LaTeX",
        "ode2": "ODE 2nd",
        "odesys": "ODE system",
        "yp0": "y'(x0)",
        "copy_latex": "LaTeX copied.",
        "session_saved": "Session saved.",
        "det": "det",
        "invm": "Inverse",
        "trans": "Transpose",
        "eig": "Eigen",
        "rref": "RREF",
        "mul": "Multiply",
        "solve_axb": "Solve Ax=b",
        "graph_hint": "One function per line, e.g. sin(x) and x**2. Parametric: cos(t), sin(t). Data: x y pairs. Bode: paste a netlist and a node.",
        "matrix_hint": "Matrix A as 1, 2; 3, 4. B is the second matrix or the vector b.",
        "stats_hint": "Paste numbers, one per line or 1, 2, 3. Two columns x y give a linear fit.",
        "triangle_hint": "Fill what you know. Sides a,b,c opposite angles A,B,C in degrees. SSS, SAS, ASA, AAS, SSA.",
        "lookup_hint": "H2O, Fe, sin, matrix, series 1k, R, g",
        "kbd_hint": "Type in the screen. Units work: 12 V / 2 kohm. Enter calculates. Esc clears. Alt+1 to Alt+9 switch pages. Alt+0 Circuits, Alt+G Graph, Alt+M Matrix, Alt+D Stats, Alt+T Triangle.",
    },
    "fa": {
        "title": "ماشین حساب اولترا",
        "calc": "ماشین حساب",
        "formulas": "فرمول ها",
        "poly": "چندجمله ای",
        "numeric": "عددی",
        "algo": "الگوریتم ها",
        "pick_algo": "یک الگوریتم انتخاب کن.",
        "algo_hint": "خانه‌ها را پر کن و Enter بزن. ماتریس: 1, 2; 3, 4.",
        "search": "جستجو",
        "categories": "دسته ها",
        "all": "همه",
        "solve": "حل",
        "unknown": "مجهول",
        "single": "یک مجهول",
        "system": "چند معادله",
        "add": "افزودن معادله",
        "remove": "حذف معادله",
        "result": "نتیجه",
        "deg": "درجه",
        "rad": "رادیان",
        "eng": "مهندسی",
        "evaluate": "مقدار",
        "roots": "ریشه ها",
        "run": "اجرا",
        "root": "ریشه",
        "integral": "انتگرال",
        "deriv": "مشتق",
        "ode": "دیفرانسیل",
        "history": "تاریخچه",
        "ready": "آماده",
        "pick": "یک فرمول انتخاب کن.",
        "lang": "زبان",
        "chem": "شیمی",
        "elements": "عنصرها",
        "balance": "موازنه",
        "molar": "جرم مولی",
        "atomic_n": "Z",
        "atomic_m": "جرم",
        "isotopes": "ایزوتوپ",
        "sources": "منبع ها",
        "lookup": "جستجوی سریع",
        "lookup_hint": "H2O, Fe, Fe-56, R, g",
        "insert": "بگذار",
        "lookup_need_field": "اول خانه را انتخاب کن، بعد بگذار.",
        "kbd_hint": "توی صفحه تایپ کن. Enter حساب می‌کند. Esc پاک می‌کند. Alt+1 تا Alt+9 صفحه را عوض می‌کند. Alt+0 مدارهاست. می‌توانی بنویسی summation(k,k,1,100) یا diff(x**3,x).",
        "problems": "مسائل",
        "inverse": "حل عکس",
        "at_value": "در",
        "problem_hint": "معادله بنویس (2*x+3=11) یا صورت مسئله را عیناً بچسبان: دو بار و نقطهٔ صفر میدان، نیروی کولن، اهم، حرکت. دکمهٔ حل. حل عکس برای تابع است.",
        "circuits": "مدارها",
        "circuit_freq": "f (هرتز)",
        "circuit_hint": "نت‌لیست بنویس (گره ۰ زمین است): V1 1 0 12 سپس R1 1 2 1k سپس R2 2 0 2k. میانبر: series 1k 2k. منبع کنترل‌شده E/G، دیود D1، ترانزیستور Q1، ماسفت M1. پاسخ زمانی: .tran 1u 2m.",
        "graph": "نمودار",
        "matrix": "ماتریس",
        "stats": "آمار",
        "triangle": "مثلث",
        "plot": "رسم",
        "bode": "بود",
        "parametric": "پارامتری",
        "data": "داده",
        "xmin": "xmin",
        "xmax": "xmax",
        "save": "ذخیره",
        "load": "باز کردن",
        "latex": "لاتک",
        "ode2": "دیفرانسیل ۲",
        "odesys": "دستگاه دیفرانسیل",
        "yp0": "y'(x0)",
        "copy_latex": "لاتک کپی شد.",
        "session_saved": "نشست ذخیره شد.",
        "det": "دترمینان",
        "invm": "وارون",
        "trans": "ترانهاده",
        "eig": "ویژه",
        "rref": "پلکانی",
        "mul": "ضرب",
        "solve_axb": "حل Ax=b",
        "graph_hint": "هر خط یک تابع، مثلاً sin(x). پارامتری: cos(t), sin(t). داده: جفت x y. بود: نت‌لیست و گره.",
        "matrix_hint": "ماتریس A مثل 1, 2; 3, 4. B ماتریس دوم یا بردار b است.",
        "stats_hint": "عددها را بچسبان. دو ستون x y رگرسیون می‌دهد.",
        "triangle_hint": "آنچه می‌دانی را پر کن. ضلع a روبه‌روی زاویه A است. درجه.",
        "lookup_hint": "H2O, Fe, sin, ماتریس, series 1k, R, g",
        "kbd_hint": "توی صفحه تایپ کن. واحد هم کار می‌کند: 12 V / 2 kohm. Enter حساب می‌کند. Alt+G نمودار، Alt+M ماتریس، Alt+D آمار، Alt+T مثلث.",
    },
    "fi": {
        "title": "Ultra-laskin",
        "calc": "Laskin",
        "formulas": "Kaavat",
        "poly": "Polynomi",
        "numeric": "Numeerinen",
        "search": "Haku",
        "categories": "Luokat",
        "all": "Kaikki",
        "solve": "Ratkaise",
        "unknown": "Tuntematon",
        "single": "Yksi tuntematon",
        "system": "Useita yhtaloita",
        "add": "Lisaa yhtalo",
        "remove": "Poista yhtalo",
        "result": "Tulos",
        "deg": "ASTE",
        "rad": "RAD",
        "eng": "ENG",
        "evaluate": "Laske",
        "roots": "Juuret",
        "run": "Suorita",
        "root": "Juuri",
        "integral": "Integraali",
        "deriv": "Derivaatta",
        "ode": "DY",
        "history": "Historia",
        "ready": "Valmis",
        "pick": "Valitse kaava.",
        "lang": "Kieli",
        "chem": "Kemia",
        "elements": "Alkuaineet",
        "balance": "Tasapainota",
        "molar": "Moolimassa",
        "atomic_n": "Z",
        "atomic_m": "Massa",
        "isotopes": "Isotoopit",
        "sources": "Lahteet",
        "lookup": "Haku",
        "lookup_hint": "H2O, Fe, Fe-56, R, g",
        "insert": "Lisaa",
        "lookup_need_field": "Napsauta kenttaa, sitten Lisaa.",
        "kbd_hint": "Kirjoita nayttoon. Enter laskee. Esc tyhjentaa. Alt+1–9 vaihtaa sivua. Voit kirjoittaa summation(k,k,1,100) tai diff(x**3,x).",
        "algo": "Algoritmit",
        "problems": "Tehtavat",
        "inverse": "Kaanteinen",
        "at_value": "kohdassa",
        "problem_hint": "Kirjoita yhtalo (2*x+3=11) tai liita sanallinen tehtava (kaksi varausta, E=0, Ohm, liike). Ratkaise. Kaanteinen on funktioille.",
        "circuits": "Piirit",
        "circuit_freq": "f (Hz)",
        "circuit_hint": "Kirjoita nettilista (solmu 0 on maa): V1 1 0 12 / R1 1 2 1k / R2 2 0 2k. Diodi D1, transistori Q1, MOSFET M1. Transientti: .tran 1u 2m.",
        "graph": "Kuvaaja",
        "matrix": "Matriisi",
        "stats": "Tilastot",
        "triangle": "Kolmio",
        "plot": "Piirra",
        "bode": "Bode",
        "parametric": "Parametrinen",
        "data": "Data",
        "save": "Tallenna",
        "load": "Avaa",
        "latex": "LaTeX",
        "ode2": "DY 2.",
        "odesys": "DY-ryhma",
        "det": "det",
        "invm": "Kaanteinen",
        "trans": "Transpoosi",
        "eig": "Ominais",
        "rref": "RREF",
        "mul": "Kerro",
        "solve_axb": "Ratkaise Ax=b",
        "graph_hint": "Yksi funktio riville, esim. sin(x). Parametrinen: cos(t), sin(t).",
        "matrix_hint": "Matriisi A: 1, 2; 3, 4.",
        "stats_hint": "Liita lukuja. Kaksi saraketta x y antaa suoran.",
        "triangle_hint": "Tayta tunnetut. Sivu a vastaa kulmaa A. Asteet.",
        "kbd_hint": "Kirjoita nayttoon. Yksikot: 12 V / 2 kohm. Enter laskee. Alt+G kuvaaja, Alt+M matriisi.",
    },
}


def ui_text(lang, key):
    pack = UI.get(lang) or UI["en"]
    return pack.get(key) or UI["en"].get(key, key)
